---
title: A map of current machine learning frameworks
frontlogo: /img/sfudrac.png
author: Marie-Hélène Burle
date: 2023-10-03
date-format: long
execute:
  error: true
  echo: true
format:
  revealjs:
    # embed-resources: true
    theme: [default, ../revealjs.scss]
    logo: /img/sfudrac_logo.png
    highlight-style: monokai
    code-line-numbers: false
    template-partials:
      - ../title-slide.html
    pointer:
      color: "#b5111b"
      pointerSize: 32
    link-external-newwindow: true
    footer: <a href="frameworks.html"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="rgb(153, 153, 153)" class="bi bi-arrow-90deg-up" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M4.854 1.146a.5.5 0 0 0-.708 0l-4 4a.5.5 0 1 0 .708.708L4 2.707V12.5A2.5 2.5 0 0 0 6.5 15h8a.5.5 0 0 0 0-1h-8A1.5 1.5 0 0 1 5 12.5V2.707l3.146 3.147a.5.5 0 1 0 .708-.708l-4-4z"/></svg>&nbsp;Back to the course</a>
    auto-stretch: false
revealjs-plugins:
  - pointer
---

```{dot}
//| echo: false

strict graph {
  
bgcolor="transparent"
graph [fontname="Inconsolata, sans-serif"]
node [fontname="Inconsolata, sans-serif", shape=plaintext]

"Traditional machine learning\n(ML)\n→ computational statistics\n→ predictive analytics" [URL="https://en.wikipedia.org/wiki/Computational_statistics", fontsize=8, fontcolor=darkolivegreen]
"Deep learning\n(DL)\n→ artificial neural networks" [URL="https://en.wikipedia.org/wiki/Deep_learning", fontsize=8, fontcolor=darkcyan]

Type -- {"Traditional machine learning\n(ML)\n→ computational statistics\n→ predictive analytics" "Deep learning\n(DL)\n→ artificial neural networks"}

}
```

---

```{dot}
//| echo: false

strict graph {
  
bgcolor="transparent"
graph [fontname="Inconsolata, sans-serif"]
node [fontname="Inconsolata, sans-serif", shape=plaintext]

Python [fontcolor=darkgoldenrod, URL="https://www.python.org/"]
Julia [fontcolor=darkorchid2, URL="https://julialang.org/"]
R [fontcolor=cornflowerblue, URL="https://www.r-project.org/"]

Language -- {Python Julia R}

}
```

<!-- --- -->

<!-- ```{dot} -->
<!-- //| echo: false -->

<!-- strict graph { -->
  
<!-- bgcolor="transparent" -->
<!-- graph [fontname="Inconsolata, sans-serif"] -->
<!-- node [fontname="Inconsolata, sans-serif"] -->
<!-- label="Overall map\n\n" -->
<!-- labelloc=t -->
<!-- fontsize=27 -->

<!-- subgraph cluster_ml {	 -->
<!--   peripheries=0 -->
<!--   label="Traditional machine learning\n\n" -->
<!--   fontcolor=darkolivegreen -->
<!--   fontsize=20 -->
<!--   "scikit-learn" "Several Julia ML packages" "Many R ML packages" -->
<!-- } -->

<!-- subgraph cluster_dl {	 -->
<!--   peripheries=0 -->
<!--   label="\nDeep learning" -->
<!--   fontcolor=darkcyan -->
<!--   fontsize=20 -->
<!--   labelloc=b -->
<!--   Torch TensorFlow Jax Keras MXNET "Several Julia DL packages" "Several R DL packages" -->
<!-- } -->

<!-- Python [color=darkgoldenrod, fontcolor=darkgoldenrod, URL="https://www.python.org/"] -->
<!-- Julia [color=darkorchid2, fontcolor=darkorchid2, URL="https://julialang.org/"] -->
<!-- R [color=cornflowerblue, fontcolor=cornflowerblue, URL="https://www.r-project.org/"] -->

<!-- "scikit-learn" -- Python [color=darkgoldenrod] -->
<!-- Python -- {Torch TensorFlow Jax Keras MXNET} [color=darkgoldenrod] -->

<!-- {"Several Julia ML packages" "scikit-learn"} -- Julia [color=darkorchid2] -->
<!-- Julia -- {"Several Julia DL packages" Torch TensorFlow Keras MXNET} [color=darkorchid2] -->

<!-- {"scikit-learn" "Many R ML packages"} -- R [color=cornflowerblue] -->
<!-- R -- {"Several R DL packages" Torch TensorFlow Keras MXNET} [color=cornflowerblue] -->

<!-- } -->
<!-- ``` -->

---

```{dot}
//| echo: false

strict graph {
  
bgcolor="transparent"
graph [fontname="Inconsolata, sans-serif"]
node [fontname="Inconsolata, sans-serif"]
label="Most classic frameworks\n\n"
labelloc=t
fontsize=27

subgraph cluster_ml {	
  peripheries=0
  label="Traditional machine learning\n\n"
  fontcolor=darkolivegreen
  fontsize=20
  "scikit-learn" "Several Julia ML packages" "Many R ML packages"
}

subgraph cluster_dl {	
  peripheries=0
  label="\nDeep learning"
  fontcolor=darkcyan
  fontsize=20
  labelloc=b
  Torch TensorFlow Jax Keras "Several Julia DL packages" "Several R DL packages"
}

Python [color=darkgoldenrod, fontcolor=darkgoldenrod, URL="https://www.python.org/"]
Julia [color=darkorchid2, fontcolor=darkorchid2, URL="https://julialang.org/"]
R [color=cornflowerblue, fontcolor=cornflowerblue, URL="https://www.r-project.org/"]

"scikit-learn" -- Python [color=darkgoldenrod]
Python -- {Torch TensorFlow Jax Keras} [color=darkgoldenrod]

{"Several Julia ML packages" "scikit-learn"} -- Julia [color=darkorchid2]
Julia -- {"Several Julia DL packages" Torch TensorFlow Keras} [color=darkorchid2]

{"scikit-learn" "Many R ML packages"} -- R [color=cornflowerblue]
R -- {"Several R DL packages" Torch TensorFlow Keras} [color=cornflowerblue]

"Several Julia ML packages" [color=gray55, fontcolor=gray55]
"Several Julia DL packages" [color=gray55, fontcolor=gray55]
"Many R ML packages" [color=gray55, fontcolor=gray55]
"Several R DL packages" [color=gray55, fontcolor=gray55]
Jax [color=gray55, fontcolor=gray55, URL="https://jax.readthedocs.io/en/latest/index.html"]

"scikit-learn" [URL="https://scikit-learn.org/stable/"]
Keras [URL="https://keras.io/"]
TensorFlow [URL="https://www.tensorflow.org/"]
Torch [URL="https://pytorch.org/"]

}
```

A fast evolving field: \
- [MXNET](https://github.com/apache/mxnet) was *just* retired a few days ago \
- [caffe2](https://github.com/facebookarchive/caffe2) is now part of [PyTorch](https://github.com/pytorch/pytorch/) \
- [keras](https://github.com/keras-team/keras-core) has been the high-level frontend for a shifting list of backends (currently [TensorFlow](https://github.com/tensorflow/tensorflow), [PyTorch](https://github.com/pytorch/pytorch?fbclid=IwAR3mdJ6akutefkkOuCbzhsSRqrJPumMkpGIZvCxz-xRWcdYU2uw63yn2_ig), [jax](https://github.com/google/jax))

---

```{dot}
//| echo: false

strict graph {

  label="Python\n\n"
  labelloc=t
  fontsize=30
  
  bgcolor="transparent"
  graph [fontname="Inconsolata, sans-serif"]
  node [fontname="Inconsolata, sans-serif"]

  subgraph cluster_ml {
	peripheries=0
	label="Traditional machine learning\n\n"
	fontcolor=darkolivegreen
	fontsize=20
	"scikit-learn" "Several Julia ML packages" "Many R ML packages"
  }

  subgraph cluster_dl {
	peripheries=0
	label="\nDeep learning"
	fontcolor=darkcyan
	fontsize=20
	labelloc=b
	Torch TensorFlow Jax Keras "Several Julia DL packages" "Several R DL packages"
  }

  Python [color=darkgoldenrod, fontcolor=darkgoldenrod, URL="https://www.python.org/"]
  Julia [color=gray55, fontcolor=gray55, URL="https://julialang.org/"]
  R [color=gray55, fontcolor=gray55, URL="https://www.r-project.org/"]

  "scikit-learn" [color=darkgoldenrod, URL="https://scikit-learn.org/stable/"]
  Keras [color=darkgoldenrod, URL="https://keras.io/"]
  TensorFlow [color=darkgoldenrod, URL="https://www.tensorflow.org/"]
  Torch [color=darkgoldenrod, URL="https://pytorch.org/"]
  Jax [color=darkgoldenrod, URL="https://jax.readthedocs.io/en/latest/index.html"]
  
  "scikit-learn" -- Python [color=darkgoldenrod]
  Python -- {Torch TensorFlow Jax Keras} [color=darkgoldenrod]

  {"Several Julia ML packages" "scikit-learn"} -- Julia [color=gray55]
  Julia -- {"Several Julia DL packages" Torch TensorFlow Keras} [color=gray55]

  {"scikit-learn" "Many R ML packages"} -- R [color=gray55]
  R -- {"Several R DL packages" Torch TensorFlow Keras} [color=gray55]

  "Several Julia ML packages" [color=gray55, fontcolor=gray55]
  "Several Julia DL packages" [color=gray55, fontcolor=gray55]
  "Many R ML packages" [color=gray55, fontcolor=gray55]
  "Several R DL packages" [color=gray55, fontcolor=gray55]
  
}
```

Several classic packages written *for* Python, but [not]{.underline} *in* Python (too slow) \
→ written in Fortran, C, or C++

---

```{dot}
//| echo: false

strict graph {

  label="Julia\n\n"
  labelloc=t
  fontsize=30
  
  bgcolor="transparent"
  graph [fontname="Inconsolata, sans-serif"]
  node [fontname="Inconsolata, sans-serif"]

  subgraph cluster_ml {
	peripheries=0
	label="Traditional machine learning\n\n"
	fontcolor=darkolivegreen
	fontsize=20
	"scikit-learn" "Several Julia ML packages" "Many R ML packages"
  }

  subgraph cluster_dl {
	peripheries=0
	label="\nDeep learning"
	fontcolor=darkcyan
	fontsize=20
	labelloc=b
	Torch TensorFlow Jax Keras "Several Julia DL packages" "Several R DL packages"
  }

  Python [color=gray55, fontcolor=gray55, URL="https://www.python.org/"]
  Julia [color=darkorchid2, fontcolor=darkorchid2, URL="https://julialang.org/"]
  R [color=gray55, fontcolor=gray55, URL="https://www.r-project.org/"]

  "Several Julia ML packages" [color=darkorchid2, fontcolor=darkorchid2]
  "Several Julia DL packages" [color=darkorchid2, fontcolor=darkorchid2]
  Keras [color=darkorchid2, fontcolor=darkorchid2, URL="https://github.com/ayush1999/Keras.jl"]
  "scikit-learn" [color=darkorchid2, URL="https://github.com/cstjean/ScikitLearn.jl"]
  TensorFlow [color=darkorchid2, URL="https://malmaud.github.io/tfdocs/"]
  Torch [color=darkorchid2, URL="https://github.com/FluxML/Torch.jl"]

  "scikit-learn" -- Python [color=gray55]
  Python -- {Torch TensorFlow Jax Keras} [color=gray55]

  {"Several Julia ML packages" "scikit-learn"} -- Julia [color=darkorchid2]
  Julia -- {"Several Julia DL packages" Torch TensorFlow Keras} [color=darkorchid2]

  {"scikit-learn" "Many R ML packages"} -- R [color=gray55]
  R -- {"Several R DL packages" Torch TensorFlow Keras} [color=gray55]

  "Many R ML packages" [color=gray55, fontcolor=gray55]
  "Several R DL packages" [color=gray55, fontcolor=gray55]
  Jax [color=gray55, fontcolor=gray55]
  
}
```

Classic Python packages available in Julia thanks to wrappers \
In addition <font color="#b23aee">many packages written in Julia</font> (fast enough)

---

```{dot}
//| echo: false

strict graph {
  
label="Julia\n\n"
labelloc=t
fontsize=30

bgcolor="transparent"
graph [fontname="Inconsolata, sans-serif"]
node [fontname="Inconsolata, sans-serif"]

subgraph cluster_ml {
  peripheries=0
  label="Traditional machine learning\n\n"
  fontcolor=darkolivegreen
  fontsize=20
  "scikit-learn" "Several Julia ML packages" "Many R ML packages"
}

subgraph cluster_dl {
  peripheries=0
  label="\nDeep learning"
  fontcolor=darkcyan
  fontsize=20
  labelloc=b
  Torch TensorFlow Jax Keras "Several Julia DL packages" "Several R DL packages"
}

Python [color=gray55, fontcolor=gray55, URL="https://www.python.org/"]
Julia [color=darkorchid2, fontcolor=darkorchid2, URL="https://julialang.org/"]
R [color=gray55, fontcolor=gray55, URL="https://www.r-project.org/"]

"Several Julia ML packages" [color=darkorchid2, fontcolor=darkorchid2]
"Several Julia DL packages" [color=darkorchid2, fontcolor=darkorchid2]
Keras [color=gray55, fontcolor=gray55, URL="https://github.com/ayush1999/Keras.jl"]
"scikit-learn" [color=gray55, fontcolor=gray55, URL="https://github.com/cstjean/ScikitLearn.jl"]
TensorFlow [color=gray55, fontcolor=gray55, URL="https://malmaud.github.io/tfdocs/"]
Torch [color=gray55, fontcolor=gray55, URL="https://github.com/FluxML/Torch.jl"]

"scikit-learn" -- Python [color=gray55]
Python -- {Torch TensorFlow Jax Keras} [color=gray55]

{"Several Julia ML packages" "scikit-learn"} -- Julia [color=darkorchid2]
Julia -- {"Several Julia DL packages" Torch TensorFlow Keras} [color=darkorchid2]

{"scikit-learn" "Many R ML packages"} -- R [color=gray55]
R -- {"Several R DL packages" Torch TensorFlow Keras} [color=gray55]

"Many R ML packages" [color=gray55, fontcolor=gray55]
"Several R DL packages" [color=gray55, fontcolor=gray55]
Jax [color=gray55, fontcolor=gray55]

}
```

---

```{dot}
//| echo: false

strict graph {

  bgcolor="transparent"
  graph [fontname="Inconsolata, sans-serif"]
  node [fontname="Inconsolata, sans-serif", color=darkorchid2]
  compound=true
  
  subgraph cluster_ml {
	label="Traditional machine learning\n\n"
	color=darkorchid2
	fontcolor=darkolivegreen
	fontsize=20
	edge [style=invis]
	node [fontsize=20]
	{rank=same; AugmentedGaussianProcesses MachineLearning TSML DecisionTree}
	{rank=same; EvoTrees ZigZagBoomerang LightGBM BayesianOptimization}
	{rank=same; MLJ GLMNet LIBSVM MLBase MLKernels Clustering ForneyLab}
	AugmentedGaussianProcesses -- EvoTrees -- MLJ
  }

  subgraph cluster_dl {	
	label="\nDeep learning"
	color=darkorchid2
	fontcolor=darkcyan
	fontsize=20
	labelloc=b
	node [fontsize=20]
	Flux Lux Knet Merlin MLJFlux FluxTraining GraphNeuralNetworks
  }

  Julia [fontsize=18]
  Julia [fontcolor=darkorchid2, URL="https://julialang.org/"]

  MLBase -- Julia [ltail=cluster_ml, color=darkorchid2]
  Julia -- MLJFlux [lhead=cluster_dl, color=darkorchid2]
  
}
```

---

```{dot}
//| echo: false

strict graph {

  bgcolor="transparent"
  graph [fontname="Inconsolata, sans-serif"]
  node [fontname="Inconsolata, sans-serif", color=darkorchid2]
  compound=true
  
  subgraph cluster_ml {
	label="Traditional machine learning\n\n"
	color=darkorchid2
	fontcolor=darkolivegreen
	fontsize=20
	edge [style=invis]
	node [fontsize=28]
	{rank=same; AugmentedGaussianProcesses MachineLearning TSML DecisionTree}
	{rank=same; EvoTrees ZigZagBoomerang LightGBM BayesianOptimization}
	{rank=same; MLJ GLMNet LIBSVM MLBase MLKernels Clustering ForneyLab}
	AugmentedGaussianProcesses -- EvoTrees -- MLJ
  }

  subgraph cluster_dl {	
	label="\nDeep learning"
	color=darkorchid2
	fontcolor=darkcyan
	fontsize=20
	labelloc=b
	edge [style=invis]
	node [fontsize=28]
	Flux Lux Knet Merlin MLJFlux FluxTraining GraphNeuralNetworks
	subgraph cluster_utilities {
	  label="Utilities"
	  node [fontsize=19]
	  DataLoaders MLUtils MLDataUtils MLDatasets TensorBoardLogger ObjectDetector Metalhead
	}
	GraphNeuralNetworks -- Metalhead
  }

  Flux [URL="https://github.com/FluxML/Flux.jl"]
  Lux [URL="https://github.com/LuxDL/"]
  Knet [URL="https://github.com/denizyuret/Knet.jl"]
  Merlin [URL=""]
  MLJFlux [URL=""]
  FluxTraining [URL=""]
  GraphNeuralNetworks [URL=""]
  MLJ [URL="https://github.com/alan-turing-institute/MLJ.jl"]

  Julia [fontsize=18, fontcolor=darkorchid2, URL="https://julialang.org/"]

  MLBase -- Julia [ltail=cluster_ml, color=darkorchid2]
  Julia -- MLJFlux [lhead=cluster_dl, color=darkorchid2]
  
}
```

---

```{dot}
//| echo: false

strict graph {

  bgcolor="transparent"
  graph [fontname="Inconsolata, sans-serif"]
  node [fontname="Inconsolata, sans-serif", color=darkorchid2]
  compound=true
  
  subgraph cluster_ml {
	label="Traditional machine learning\n\n"
	color=darkorchid2
	fontcolor=darkolivegreen
	fontsize=24
	edge [style=invis]
	node [fontsize=36]
	{rank=same; AugmentedGaussianProcesses MachineLearning TSML DecisionTree}
	{rank=same; EvoTrees ZigZagBoomerang LightGBM BayesianOptimization}
	{rank=same; MLJ GLMNet LIBSVM MLBase MLKernels Clustering ForneyLab}
	AugmentedGaussianProcesses -- EvoTrees -- MLJ
  }

  subgraph cluster_dl {	
	label="\nDeep learning"
	color=darkorchid2
	fontcolor=darkcyan
	fontsize=24
	labelloc=b
	edge [style=invis]
	node [fontsize=36]
	Flux Lux Knet Merlin MLJFlux FluxTraining GraphNeuralNetworks
	subgraph cluster_utilities {
	  label="Utilities"
	  node [fontsize=25]
	  DataLoaders MLUtils MLDataUtils MLDatasets TensorBoardLogger ObjectDetector Metalhead
	}
	subgraph cluster_autodiff {
	  label="Autodiff"
	  node [fontsize=30]
	  ForwardDiff ReverseDiff Zygote Enzyme ChainRules TaylorDiff StochasticAD
	}
	GraphNeuralNetworks -- Metalhead
	Metalhead -- StochasticAD
  }

  Flux [URL="https://github.com/FluxML/Flux.jl"]
  Lux [URL="https://github.com/LuxDL/"]
  Knet [URL="https://github.com/denizyuret/Knet.jl"]
  Merlin [URL=""]
  MLJFlux [URL=""]
  FluxTraining [URL=""]
  GraphNeuralNetworks [URL=""]
  MLJ [URL="https://github.com/alan-turing-institute/MLJ.jl"]
  ForwardDiff [URL="https://github.com/JuliaDiff/ForwardDiff.jl"]
  ReverseDiff [URL="https://github.com/JuliaDiff/ReverseDiff.jl"]
  Zygote [URL="https://github.com/FluxML/Zygote.jl"]
  Enzyme [URL="https://github.com/EnzymeAD/Enzyme.jl"]
  ChainRules [URL="https://github.com/JuliaDiff/ChainRules.jl"]
  TaylorDiff [URL="https://github.com/JuliaDiff/TaylorDiff.jl"]
  StochasticAD [URL="https://github.com/gaurav-arya/StochasticAD.jl"]

  Julia [fontsize=22, fontcolor=darkorchid2, URL="https://julialang.org/"]

  MLBase -- Julia [ltail=cluster_ml, color=darkorchid2]
  Julia -- MLJFlux [lhead=cluster_dl, color=darkorchid2]
  
}
```

---

```{dot}
//| echo: false

strict graph {

  label="R\n\n"
  labelloc=t
  fontsize=30
  
  bgcolor="transparent"
  graph [fontname="Inconsolata, sans-serif"]
  node [fontname="Inconsolata, sans-serif"]

  subgraph cluster_ml {
	peripheries=0
	label="Traditional machine learning\n\n"
	fontcolor=darkolivegreen
	fontsize=20
	"scikit-learn" "Several Julia ML packages" "Many R ML packages"
  }

  subgraph cluster_dl {
	peripheries=0
	label="\nDeep learning"
	fontcolor=darkcyan
	fontsize=20
	labelloc=b
	Torch TensorFlow Jax Keras "Several Julia DL packages" "Several R DL packages"
  }

  Python [color=gray55, fontcolor=gray55, URL="https://www.python.org/"]
  Julia [color=gray55, fontcolor=gray55, URL="https://julialang.org/"]
  R [color=cornflowerblue, fontcolor=cornflowerblue, URL="https://www.r-project.org/"]

  "Many R ML packages" [color=cornflowerblue]
  "Several R DL packages" [color=cornflowerblue]
  "scikit-learn" [color=cornflowerblue, URL="https://saraswatmks.github.io/superml/"]
  Keras [color=cornflowerblue, URL="https://github.com/rstudio/keras"]
  TensorFlow [color=cornflowerblue, URL="https://tensorflow.rstudio.com/"]
  Torch [color=cornflowerblue, URL="https://torch.mlverse.org/"]

  "scikit-learn" -- Python [color=gray55]
  Python -- {Torch TensorFlow Jax Keras} [color=gray55]

  {"Several Julia ML packages" "scikit-learn"} -- Julia [color=gray55]
  Julia -- {"Several Julia DL packages" Torch TensorFlow Keras} [color=gray55]

  {"scikit-learn" "Many R ML packages"} -- R [color=cornflowerblue]
	R -- {"Several R DL packages" Torch TensorFlow Keras} [color=cornflowerblue]

	"Several Julia ML packages" [color=gray55, fontcolor=gray55]
	"Several Julia DL packages" [color=gray55, fontcolor=gray55]
	Jax [color=gray55, fontcolor=gray55]
	
}
```

Classic Python packages available in R thanks to wrappers \
In addition many packages written *for* R, but [not]{.underline} *in* R (too slow) \
→ written in C

---

```{dot}
//| echo: false

strict graph {

  label="R\n\n"
  labelloc=t
  fontsize=30
  
  bgcolor="transparent"
  graph [fontname="Inconsolata, sans-serif"]
  node [fontname="Inconsolata, sans-serif"]

  subgraph cluster_ml {
	peripheries=0
	label="Traditional machine learning\n\n"
	fontcolor=darkolivegreen
	fontsize=20
	"scikit-learn" "Several Julia ML packages" "Many R ML packages"
  }

  subgraph cluster_dl {
	peripheries=0
	label="\nDeep learning"
	fontcolor=darkcyan
	fontsize=20
	labelloc=b
	Torch TensorFlow Jax Keras "Several Julia DL packages" "Several R DL packages"
  }

  Python [color=gray55, fontcolor=gray55, URL="https://www.python.org/"]
  Julia [color=gray55, fontcolor=gray55, URL="https://julialang.org/"]
  R [color=cornflowerblue, fontcolor=cornflowerblue, URL="https://www.r-project.org/"]

  "Many R ML packages" [color=cornflowerblue]
  "Several R DL packages" [color=cornflowerblue]
  "scikit-learn" [color=gray55, fontcolor=gray55, URL="https://saraswatmks.github.io/superml/"]
  Keras [color=gray55, fontcolor=gray55, URL="https://github.com/rstudio/keras"]
  TensorFlow [color=gray55, fontcolor=gray55, URL="https://tensorflow.rstudio.com/"]
  Torch [color=gray55, fontcolor=gray55, URL="https://torch.mlverse.org/"]

  "scikit-learn" -- Python [color=gray55]
  Python -- {Torch TensorFlow Jax Keras} [color=gray55]

  {"Several Julia ML packages" "scikit-learn"} -- Julia [color=gray55]
  Julia -- {"Several Julia DL packages" Torch TensorFlow Keras} [color=gray55]

  {"scikit-learn" "Many R ML packages"} -- R [color=cornflowerblue]
  R -- {"Several R DL packages" Torch TensorFlow Keras} [color=cornflowerblue]

  "Several Julia ML packages" [color=gray55, fontcolor=gray55]
  "Several Julia DL packages" [color=gray55, fontcolor=gray55]
  Jax [color=gray55, fontcolor=gray55]
  
}
```

---

```{dot}
//| echo: false

strict graph {

  bgcolor="transparent"
  graph [fontname="Inconsolata, sans-serif"]
  node [fontname="Inconsolata, sans-serif", color=cornflowerblue]
  compound=true
  
  subgraph cluster_ml {
	label="Traditional machine learning\n\n"
	color=cornflowerblue
	fontcolor=darkolivegreen
	fontsize=20
	edge [style=invis]
	node [fontsize=18]
	{rank=same; e1071 kernlab rpart party caret gmodels randomForest ranger}
	{rank=same; ipred gbm xgboost C50 cluster class mclust naivebayes glmnet}
	e1071 -- ipred
  }

  subgraph cluster_dl {	
	label="\nDeep learning"
	color=cornflowerblue
	fontcolor=darkcyan
	fontsize=20
	labelloc=b
	node [fontsize=18]
	RSNNS h2o darch deepr RCNN4R rcppDL rnn neuralnet deepnet
  }

  ranger [URL=""]
  randomForest [URL=""]
  gmodels [URL="https://cran.r-project.org/web/packages/gmodels/index.html"]
  caret [URL=""]
  party [URL="https://cran.r-project.org/web/packages/party/index.html"]
  rpart [URL=""]
  kernlab [URL=""]
  e1071 [URL=""]
  glmnet [URL=""]
  naivebayes [URL=""]
  mclust [URL=""]
  class [URL=""]
  cluster [URL=""]
  C50 [URL=""]
  xgboost [URL=""]
  gbm [URL=""]
  ipred [URL=""]
  deepnet [URL=""]
  neuralnet [URL=""]
  rnn [URL=""]
  rcppDL [URL=""]
  RCNN4R [URL=""]
  deepr [URL=""]
  darch [URL=""]
  h2o [URL=""]
  RSNNS [URL=""]
  
  R [fontcolor=cornflowerblue, URL="https://www.r-project.org/"]
  
  cluster -- R [ltail=cluster_ml, color=cornflowerblue]
  R -- RCNN4R [lhead=cluster_dl, color=cornflowerblue]
  
}
```

The [Machine Learning CRAN Task View](https://cran.r-project.org/web/views/MachineLearning.html) is a good resource

---

|  | Python | Julia | R |
|---------|:-----|------:|:------:|
| Strengths      |    |    |      |
| Weaknesses     | 123  |    |     |

---

Language strengths:

Julia: fastest language by far, several very strong packages not available in other languages, all common packages ported through wrappers. Great for ML and DL
Python: used by most people, most common packages developed for it. Great for DL, more limited options in ML
R: largest library by far for stats and modelling, meaning incredible amount of options for ML. Slowest language, limited options for DL. Great for ML, limited for DL

data:
http://archive.ics.uci.edu/

slide on automatic differentiation:
in Python:
https://github.com/HIPS


https://juliahub.com/ui/Search?t=machine-learning
https://juliapackages.com/c/machine-learning?order=asc&sort=created&page=4
https://sciml.ai/

https://forem.julialang.org/jacobusmmsmit/thoughts-on-using-jax-and-julia-2f0b

https://stackoverflow.com/questions/54527439/differences-in-scikit-learn-keras-or-pytorch

https://pytorch-geometric.readthedocs.io/en/latest/
https://juliapackages.com/c/machine-learning
https://graphviz.org/docs/attrs/href/
