---
title: Tools for a friendlier Git
aliases:
  - tools.html
author: Marie-Hélène Burle
---

:::{.def}

A number of tools make Git a lot more friendly to use. There are several GUIs, there are integrations into IDEs (e.g. RStudio or VS Code), but the tools I really like make working with Git visually pleasing while remaining in the command line.

:::

## Better diffs

### diff-so-fancy

[diff-so-fancy](https://github.com/so-fancy/diff-so-fancy) replaces the obscure `git diff` markers into human-readable ones and highlight the parts that actually changed in modified lines.

### delta

[delta](https://github.com/dandavison/delta) additionally provides a pager and syntax highlighting for common languages. It is highly customizable, meaning that colour blind people can change the red and green colours into whatever works best for them. It is really a great tool!

## Better UI

### lazygit

[lazygit](https://github.com/jesseduffield/lazygit) is an excellent multi-platform [terminal user interface](https://en.wikipedia.org/wiki/Text-based_user_interface) for Git. It integrates with either of diff-so-fancy or delta for diffs and it is my favourite Git interface. You can find the installation instructions [here](https://github.com/jesseduffield/lazygit?tab=readme-ov-file#installation).

I gave a webinar on it that you can find [here](wb_lazygit.qmd) (video below).

{{< video https://www.youtube.com/embed/1a2nrwfqNGI >}}

### Fuzzy finders

If you don't want to use a full TUI for Git, you can use fuzzy finders to make searching and previewing commits, stashes, or other Git objects a lot nicer.

#### fzf

[fzf](https://github.com/junegunn/fzf) is a fantastic multi-platform command line fuzzy finder with a huge versatility.

It is [easy to install on your machine](https://github.com/junegunn/fzf?tab=readme-ov-file#installation) and it is already installed on the Alliance clusters.

:::{.example}

In this video, I demo quickly how it can be used with Git:

:::

{{< video https://www.youtube.com/embed/WFy6JXBRSJc >}}

#### skim

[skim](https://github.com/skim-rs/skim) is an alternative to fzf written in Rust that can be used in a similar way to search and preview Git objects.
