---
title: "A great Git TUI: lazygit"
author: Marie-Hélène Burle
---

:::{.def}

*Content from [the webinar slides](wb_lazygit_slides.qmd) for easier browsing.*

:::

## Git interfaces

There are 3 main ways to use Git:

- Through a Git GUI
- From the command line
- Integrated within IDE

They all have downsides:

- Through a Git GUI &emsp;&emsp;&emsp;&ensp;&nbsp;➔ &ensp;*Slow and buggy*
- From the command line &ensp;&ensp;➔ &ensp;*Austere and unintuitive*
- Integrated within IDE &emsp;&emsp;&nbsp;&nbsp;➔ &ensp;*Limited*

## On the beauty of TUIs

[Terminal user interfaces (TUIs)](https://en.wikipedia.org/wiki/Text-based_user_interface) were precursors to [graphical user interfaces (GUIs)](https://en.wikipedia.org/wiki/Graphical_user_interface), but they did not disappear

People continue to build TUIs because they uniquely provide the speed of the command line and the easy of use of GUIs

[GitHub is full of sleek, modern, open source TUIs for all sorts of applications](https://github.com/rothgar/awesome-tuis)

Several of them provide an interface to Git

My personal TUIs of choice are [ranger](https://github.com/ranger/ranger) as file manager and [lazygit](https://github.com/jesseduffield/lazygit) for Git

## lazygit

With over 52k stars on GitHub, [lazygit](https://github.com/jesseduffield/lazygit), created and maintained by [Jesse Duffield](https://github.com/jesseduffield) is probably the most polished Git TUI

I followed it as it grew and developed over the past 5 years. It was great from the start, but by now, it is a truly beautiful mature tool

It is cross-platform. You can find [installation instructions](https://github.com/jesseduffield/lazygit?tab=readme-ov-file#installation) in the README

Get command options:

```{.bash}
lazygit -h
```

Print default configurations with:

```{.bash}
lazygit -c
```

:::{.note}

lazygit is fully customizable

:::

## Resources

- [Repo](https://github.com/jesseduffield/lazygit)
- [Default kbds](https://github.com/jesseduffield/lazygit/blob/master/docs/keybindings/Keybindings_en.md)
- [Configuration options](https://github.com/jesseduffield/lazygit/blob/v0.44.1/docs/Config.md)

## Time for a demo!

I will spend the rest of this webinar showing you how to use Git through lazygit
