project:
  type: website
  output-dir: _site

website:
  title: WestDRI
  image: /img/sfudrac_logo.png
  favicon: /img/sfu_favicon.png
  site-url: https://arc-training.westdri.ca
  repo-url: https://github.com/WestDRI/arc-training
  # repo-actions: [edit, issue]
  reader-mode: true
  page-footer:
    left:
      Please also visit our [main website](https://training.westdri.ca/){target="_blank"}
    center:
      # © 2022 [SFU](https://www.sfu.ca/){target="_blank"} & [DRAC](https://alliancecan.ca/){target="_blank"}
      - text: About
        href: about.qmd
      - text: Calendar
        href: calendar.qmd
        aria-label: WestDRI training calendar
      - text: Newsletter
        href: newsletter.qmd
        aria-label: WestDRI Newsletter
      - href: contact.qmd
        aria-label: WestDRI Contact
    right:
      - icon: github
        href: https://github.com/WestDRI
        aria-label: WestDRI GitHub
      - icon: youtube
        href: https://www.youtube.com/channel/UCfgds4Qf7VFOv4ORRvFFmhw
        aria-label: WestDRI YouTube
  navbar:
    background: light
    logo: /img/sfudrac_logo.png
    logo-alt: "SFU & DRAC logos"
    left:
      - text: Git
        href: git/index.qmd
      - text: R
        href: r/index.qmd
      - text: Julia
        href: julia/index.qmd
      - text: Python
        href: python/index.qmd
      - text: ML
        href: ml/index.qmd
      - text: Bash
        href: bash/index.qmd
      - text: Research tools
        href: tools/index.qmd
  sidebar:
    - id: git
      collapse-level: 1
      contents:
        - section:
          contents:
            - git/index.qmd
        - section: Workshops
          contents:
            - text: Intro Git & GitHub
              href: git/intro.qmd
        - "---"
        - section: Courses
    - id: r
      collapse-level: 1
      contents:
        - section:
          contents:
            - r/index.qmd
        - section: Webinars
          contents:
            - text: HPC in R
              href: r/parallel.qmd
            - text: GIS mapping in R
              href: r/gis_mapping.qmd
        - "---"
        - section: Courses
    - id: julia
      collapse-level: 1
      contents:
        - section:
          contents:
            - julia/index.qmd
        - section: Workshops
          contents: 
        - "---"
        - section: Webinars
          contents:
            - text: Data visualization with Makie
              href: julia/makie.qmd
            - text: Machine learning with Flux
              href: julia/flux.qmd
            - text: First dab at Julia
              href: julia/firstdab.qmd
        - "---"
        - section: Courses
    - id: python
      collapse-level: 1
      contents:
        - section:
          contents:
            - python/index.qmd
        - section: Courses
    - id: ml
      collapse-level: 1
      contents:
        - section:
          contents:
            - ml/index.qmd
        - section: Workshops
          contents: 
        - "---"
        - section: Webinars
          contents:
            - text: PyTorch tensors
              href: ml/torchtensors.qmd
            - text: Image upscaling
              href: ml/upscaling.qmd
            - text: fastai
              href: ml/fastai.qmd
            - text: ML in Julia with Flux
              href: ml/flux.qmd
        - "---"
        - section: Courses
    - id: bash
      collapse-level: 1
      contents:
        - section:
          contents:
            - bash/index.qmd
        - section: Workshops
          contents: 
        - "---"
        - section: Webinars
          contents:
            - text: Fun tools
              href: bash/tools1.qmd
            - text: More tools
              href: bash/tools2.qmd
        - "---"
        - section: Courses
    - id: tools
      collapse-level: 1
      contents:
        - section:
          contents:
            - tools/index.qmd
        - section: Workshops
          contents: 
        - "---"
        - section: Webinars
          contents:
            - text: Getting help
              href: tools/help.qmd
        - "---"
        - section: Courses

format:
  html:
    toc: true
    toc-title: Table of contents
    theme:
      light: [cosmo, theme.scss]
    code-overflow: wrap
    css: styles.css
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
    link-external-newwindow: true

execute:
  freeze: auto
