project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!/tools/quarto/"

website:
  title: WestDRI
  image: /img/sfudrac_logo.png
  favicon: /img/sfu_favicon.png
  site-url: https://mint.westdri.ca/
  repo-url: https://github.com/WestDRI/arc-training
  reader-mode: true
  page-navigation: true
  page-footer:
    left:
      Please also visit our **[main website](https://training.westdri.ca/){target="_blank"}**
    center:
      - text: About
        href: about.qmd
      - text: Calendar
        href: calendar.qmd
        aria-label: WestDRI training calendar
      - text: Newsletter
        href: newsletter.qmd
        aria-label: WestDRI Newsletter
      - href: contact.qmd
        aria-label: WestDRI Contact
      - text: Wiki
        href: https://docs.alliancecan.ca/wiki/Technical_documentation
    right:
      - icon: github
        href: https://github.com/WestDRI
        aria-label: WestDRI GitHub
      - icon: youtube
        href: https://www.youtube.com/channel/UCfgds4Qf7VFOv4ORRvFFmhw
        aria-label: WestDRI YouTube
  navbar:
    background: light
    logo: /img/sfudrac_logo.png
    logo-alt: "SFU & DRAC logos"
    left:
      - text: Git
        href: git/index.qmd
      - text: R
        href: r/index.qmd
      - text: Julia
        href: julia/index.qmd
      - text: Python
        href: python/index.qmd
      - text: ML
        href: ml/index.qmd
      - text: Bash
        href: bash/index.qmd
      - text: Research tools
        href: tools/index.qmd
  sidebar:
    - id: git
      collapse-level: 2
      contents:
        - section:
          contents:
            - git/index.qmd
        - text: "<em>All Git pages:</em>"
          href: git/index.qmd
        - "---"
        - section: <b><em>Getting started with Git</em></b>
          href: git/top_intro.qmd
          contents:
            - text: Introduction to Git
              href: git/intro.qmd
            - text: The three trees of Git
              href: git/three_trees.qmd
            - text: Remotes
              href: git/remotes.qmd
            - text: Excluding from version control
              href: git/ignore.qmd
            - text: Branches
              href: git/branches.qmd
            - text: Stashing
              href: git/stash.qmd
            - text: Tags
              href: git/tags.qmd
            - text: Time travel
              href: git/time_travel.qmd
            - text: Undoing
              href: git/undo.qmd
            - text: Tools for a friendlier Git
              href: git/tools.qmd
        - "---"
        - section: <b><em>Git workshops</em></b>
          href: git/practice_repo/search.qmd
          contents:
            - text: Searching a Git project
              href: git/practice_repo/search.qmd
            - text: Collaborating through Git
              href: git/collab.qmd
            - text: Contributing to projects
              href: git/contrib.qmd
    - id: r
      collapse-level: 2
      contents:
        - section:
          contents:
            - r/index.qmd
        - text: "<em>All R pages:</em>"
          href: r/index.qmd
        - "---"
        - section: <em><b>Getting started with R</b></em>
          href: r/top_intro.qmd
          contents: 
            - text: Running R for this course
              href: r/run_r_intro.qmd
            - text: "R: why and for whom?"
              href: r/why.qmd
            - text: "R: the basics"
              href: r/basics.qmd
            - text: Packages
              href: r/packages.qmd
            - text: Glimpse at the tidyverse
              href: r/tidyverse.qmd
            - text: Resources
              href: r/resources.qmd
        - "---"
        - section: <b><em>High-performance R</em></b>
          href: r/top_hpc.qmd
          contents: 
            - text: Running R for this course
              href: r/run_r_hpc.qmd
            - text: Measuring performance
              href: r/performance.qmd
            - text: Optimizations
              href: r/optimizations.qmd
            - text: Memory management
              href: r/memory.qmd
            - text: Running R on HPC clusters
              href: r/clusters.qmd
            - text: Types of parallelism
              href: r/parallel_types.qmd
            # - text: Running R code in parallel
            #   href: r/parallel_r.qmd
            - text: Parallel loops
              href: r/parallel_loops.qmd
            - text: Data on HPC clusters
              href: r/data.qmd
            # - text: Partitioning data
              # href: r/partition.qmd
            - text: Writing C++ in R with Rcpp
              href: r/rcpp.qmd
            - text: Resources for HPC in R
              href: r/resources_hpc.qmd
        - "---"
        - section: <b><em>R workshops</em></b>
          href: r/webscraping.qmd
          contents: 
           - text: Web scraping with R
             href: r/webscraping.qmd
           - text: GIS with R
             href: r/intro_gis.qmd
           - text: Intro R for the humanities
             href: r/intro_hss.qmd
        - "---"
        - section: <em><b>R webinars</b></em>
          href: r/gis_mapping.qmd
          contents:
            - text: GIS mapping with R
              href: r/gis_mapping.qmd
            - text: HPC in R
              href: r/intro_hpc.qmd
    - id: julia
      collapse-level: 2
      contents:
        - section:
          contents:
            - julia/index.qmd
        - text: "<em>All Julia pages:</em>"
          href: julia/index.qmd
        - "---"
        - section: <b><em>Getting started with Julia</em></b>
          href: julia/top_intro.qmd
          contents: 
            - text: Introduction to Julia
              href: julia/intro.qmd
            - text: Basics of the Julia language
              href: julia/basics.qmd
            - text: Collections
              href: julia/collections.qmd
            - text: Types
              href: julia/types.qmd
            - text: Functions
              href: julia/functions.qmd
            - text: Control flow
              href: julia/control_flow.qmd
            - text: Macros
              href: julia/macros.qmd
            - text: Packages
              href: julia/packages.qmd
            - text: Plotting
              href: julia/plotting.qmd
            - text: Working with tabular data
              href: julia/tabular.qmd
            - text: Non interactive execution
              href: julia/non_interactive.qmd
        - "---"
        - section: <b><em>High-performance Julia</em></b>
          href: julia/top_hpc.qmd
          contents: 
            - text: Intro to HPC in Julia
              href: julia/intro_hpc.qmd
            - text: Performance
              href: julia/performance.qmd
            - text: Multi-threading
              href: julia/multithreading.qmd
            - text: Distributed computing
              href: julia/distributed.qmd
            - text: Resources
              href: julia/resources.qmd
        - "---"
        - section: <b><em>Julia webinars</em></b>
          href: julia/makie.qmd
          contents:
            - text: Data visualization with Makie
              href: julia/makie.qmd
            - text: First dab at Julia
              href: julia/firstdab.qmd
            - text: Machine learning with Flux
              href: julia/flux.qmd
    - id: python
      collapse-level: 2
      contents:
        - section:
          contents:
            - python/index.qmd
        - text: "<em>All Python pages:</em>"
          href: python/index.qmd
        - "---"
        - section: <b><em>Getting started</em></b>
          href: python/top_intro.qmd
          contents: 
            - text: Running Python
              href: python/run.qmd
            - text: "Python: the basics"
              href: python/basics.qmd
            - text: Collections
              href: python/collections.qmd
            - text: Control flow
              href: python/control_flow.qmd
            - text: Functions
              href: python/functions.qmd
            # - text: Modules and libraries
            #   href: python/packages.qmd
            # - text: Intro to Pandas
            #   href: python/pandas.qmd
            # - text: Intro HPC in Python
            #   href: python/intro_hpc.qmd
            # - text: Resources
            #   href: python/resources.qmd
        - "---"
        - section: <em><b>Python workshops</b></em>
          href: python/webscraping.qmd
          contents: 
            - text: Web scraping with Python
              href: python/webscraping.qmd
    - id: ml
      collapse-level: 2
      contents:
        - section:
          contents:
            - ml/index.qmd
        - text: "<em>All ML pages:</em>"
          href: ml/index.qmd
        - "---"
        - section: <b><em>Getting started</em></b>
          href: ml/top_intro.qmd
          contents: 
            - text: "Concepts: AI, ML, DL, NN"
              href: ml/intro.qmd
            - text: Understanding supervised learning
              href: ml/supervised_learning.qmd
            - text: Which framework to choose?
              href: ml/choosing_frameworks.qmd
            - text: High-level frameworks
              href: ml/high_level_frameworks.qmd
            - text: Automatic differentiation
              href: ml/autograd.qmd
            - text: Classifying the MNIST
              href: ml/mnist.qmd
            - text: Building a model
              href: ml/nn_building.qmd
            - text: Training a model
              href: ml/nn_training.qmd
            - text: Audio DataLoader
              href: ml/audio_dataloader.qmd
            - text: ML on production clusters
              href: ml/hpc.qmd
            - text: Finding pre-trained models
              href: ml/pretrained_models.qmd
            - text: Creating checkpoints
              href: ml/checkpoints.qmd
            - text: Resources
              href: ml/resources.qmd
        - "---"
        - section: <b><em>ML workshops</em></b>
          href: ml/intro_hss.qmd
          contents: 
            - text: Intro ML for the humanities
              href: ml/intro_hss.qmd
        - "---"
        - section: <b><em>ML webinars</em></b>
          href: ml/torchtensors.qmd
          contents:
            - text: PyTorch tensors
              href: ml/torchtensors.qmd
            - text: Image upscaling
              href: ml/upscaling.qmd
            - text: fastai
              href: ml/fastai.qmd
            - text: ML in Julia with Flux
              href: ml/flux.qmd
    - id: bash
      collapse-level: 2
      contents:
        - section:
          contents:
            - bash/index.qmd
        - text: "<em>All Bash pages:</em>"
          href: bash/index.qmd
        - "---"
        - section: <b><em>Getting started with Bash</em></b>
          href: bash/top_intro.qmd
          contents: 
            - text: Transferring files
              href: bash/transfer.qmd
            - text: Pipes and redirections
              href: bash/molecules/redirections.qmd
            - text: Writing scripts
              href: bash/molecules/script.qmd
            - text: Control flow
              href: bash/molecules/control_flow.qmd
            - text: Functions
              href: bash/functions.qmd
            - text: Searching for files
              href: bash/molecules/search.qmd
        - "---"
        - section: <b><em>Bash workshops</em></b>
          href: bash/intro_scripting.qmd
          contents: 
            - text: Scripting for beginners
              href: bash/intro_scripting.qmd
            - text: Searching & manipulating text
              href: bash/text.qmd
        - "---"
        - section: <b><em>Bash webinars</em></b>
          href: bash/tools1.qmd
          contents:
            - text: Fun tools
              href: bash/tools1.qmd
            - text: More fun tools
              href: bash/tools2.qmd
    - id: tools
      collapse-level: 2
      contents:
        - section:
          contents:
            - tools/index.qmd
        - text: "<em>All tools pages:</em>"
          href: tools/index.qmd
        - "---"
        - section: <em><b>Tools workshops</b></em>
          href: tools/quarto.qmd
          contents: 
            - text: Authoring with Quarto
              href: tools/quarto.qmd
        - "---"
        - section: <b><em>Tools webinars</em></b>
          href: tools/quarto_webinar.qmd
          contents:
            - text: "Quarto: the new R Markdown"
              href: tools/quarto_webinar.qmd
            - text: Getting help
              href: tools/help.qmd

format:
  html:
    toc: true
    toc-title: "<em>On this page:</em>"
    toc-depth: 5
    theme:
      light: [cosmo, theme.scss]
    code-overflow: wrap
    css: styles.css
    link-external-newwindow: true
    reference-location: margin
    fig-cap-location: margin

execute:
  freeze: auto
  cache: true
  error: true
  echo: true
