project:
  type: website
  output-dir: _site

website:
  title: WestDRI
  image: images/sfudrac.png
  favicon: images/sfu_favicon.png
  site-url: https://arc-training.westdri.ca/
  repo-url: https://github.com/WestDRI/arc-training
  repo-actions: [edit, issue]
  reader-mode: true
  page-footer:
    left: For our main site, see [https://training.westdri.ca/](https://training.westdri.ca/){target="_blank"}
    center:
      © 2022 [SFU](https://www.sfu.ca/){target="_blank"} & [DRAC](https://alliancecan.ca/){target="_blank"}
    right:
      - icon: github
        href: https://github.com/WestDRI
        aria-label: WestDRI GitHub
      - icon: youtube
        href: https://www.youtube.com/channel/UCfgds4Qf7VFOv4ORRvFFmhw
        aria-label: WestDRI YouTube
      - icon: calendar-event
        href: https://github.com/WestDRI/arc-training/calendar
        aria-label: WestDRI training calendar
      - icon: envelope-paper-fill
        href: https://github.com/WestDRI/arc-training/newsletter
        aria-label: WestDRI Newsletter
      - icon: mailbox2
        href: https://github.com/WestDRI/arc-training/contact
        aria-label: WestDRI Contact
  navbar:
    background: light
    logo: images/sfudrac.png
    logo-alt: "SFU & DRAC logos"
    left:
      - text: Git
        href: git/map.qmd
      - text: R
        href: r/map.qmd
      - text: Julia
        href: julia/map.qmd
      - text: Python
        href: python/map.qmd
      - text: ML
        href: ml/map.qmd
      - text: Shell
        href: shell/map.qmd
      - text: Other
        href: other/map.qmd
    right:
      - text: About
        href: about.qmd
      - icon: grid-3x3-gap
        href: https://github.com/WestDRI/arc-training/sitemap
        # href: sitemap/index.qmd
  sidebar:
    - id: git
      collapse-level: 1
      contents:
        - section:
          contents:
            - git/map.qmd
        - section: Workshops
          contents:
            - text: Intro Git & GitHub
              href: git/2022_git_sfu.qmd
        - "---"
        - section: Webinars
          contents:
        - "---"
        - section: Courses
    - id: r
      collapse-level: 1
      contents:
        - section:
          contents:
            - r/map.qmd
        - section: Workshops
          contents: 
        - "---"
        - section: Webinars
          contents:
        - "---"
        - section: Courses
    - id: julia
      collapse-level: 1
      contents:
        - section:
          contents:
            - julia/map.qmd
        - section: Workshops
          contents: 
        - "---"
        - section: Webinars
          contents:
        - "---"
        - section: Courses
    - id: python
      collapse-level: 1
      contents:
        - section:
          contents:
            - python/map.qmd
        - section: Workshops
          contents: 
        - "---"
        - section: Webinars
          contents:
        - "---"
        - section: Courses
    - id: ml
      collapse-level: 1
      contents:
        - section:
          contents:
            - ml/map.qmd
        - section: Workshops
          contents: 
        - "---"
        - section: Webinars
          contents:
        - "---"
        - section: Courses
    - id: shell
      collapse-level: 1
      contents:
        - section:
          contents:
            - shell/map.qmd
        - section: Workshops
          contents: 
        - "---"
        - section: Webinars
          contents:
        - "---"
        - section: Courses
    - id: other
      collapse-level: 1
      contents:
        - section:
          contents:
            - other/map.qmd
        - section: Workshops
          contents: 
        - "---"
        - section: Webinars
          contents:
        - "---"
        - section: Courses
format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss]
    code-overflow: wrap
    css: styles.css
    # grid:
      # sidebar-width: 50px
      # body-width: 1100px
    smooth-scroll: true
    link-external-newwindow: true
    fig-cap-location: margin
    reference-location: margin
