project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!/tools/quarto/"

website:
  title: WestDRI
  image: /img/sfudrac_logo.png
  favicon: /img/sfu_favicon.png
  site-url: https://mint.westdri.ca/
  repo-url: https://github.com/WestDRI/arc-training
  reader-mode: true
  page-navigation: true
  page-footer:
    left:
      Please also visit our **[main website](https://training.westdri.ca/){target="_blank"}**
    center:
      - text: About
        href: about.qmd
      - text: Calendar
        href: calendar.qmd
        aria-label: WestDRI training calendar
      - text: Newsletter
        href: newsletter.qmd
        aria-label: WestDRI Newsletter
      - href: contact.qmd
        aria-label: WestDRI Contact
      - text: Wiki
        href: https://docs.alliancecan.ca/wiki/Technical_documentation
    right:
      - icon: github
        href: https://github.com/WestDRI
        aria-label: WestDRI GitHub
      - icon: youtube
        href: https://www.youtube.com/channel/UCfgds4Qf7VFOv4ORRvFFmhw
        aria-label: WestDRI YouTube
  navbar:
    background: light
    logo: /img/sfudrac_logo.png
    logo-alt: "SFU & DRAC logos"
    left:
      - text: Git
        href: git/index.qmd
      - text: R
        href: r/index.qmd
      - text: Julia
        href: julia/index.qmd
      - text: Python
        href: python/index.qmd
      - text: ML
        href: ml/index.qmd
      - text: Bash
        href: bash/index.qmd
      - text: Research tools
        href: tools/index.qmd
  sidebar:
    - id: git
      collapse-level: 2
      contents:
        - section:
          contents:
            - git/index.qmd
        - section: Workshops & courses
          contents:
            - text: Getting started with Git
              href: git/getting_started.qmd
            - text: The three trees of Git
              href: git/three_trees.qmd
            - text: Remotes
              href: git/remotes.qmd
            - text: Excluding from version control
              href: git/ignore.qmd
            - text: Branches
              href: git/branches.qmd
            - text: Stashing
              href: git/stash.qmd
            - text: Tags
              href: git/tags.qmd
            - text: Searching a Git project
              href: git/practice_repo/search.qmd
            - text: Time travel
              href: git/time_travel.qmd
            - text: Undoing
              href: git/undo.qmd
            - text: Tools for a friendlier Git
              href: git/tools.qmd
            - text: "---"
            - text: Collaborating through Git
              href: git/collab.qmd
            - text: "---"
            - text: Contributing to projects
              href: git/contrib.qmd
    - id: r
      collapse-level: 2
      contents:
        - section:
          contents:
            - r/index.qmd
        - section: Workshops & courses
          contents: 
            - text: "R: why and for whom?"
              href: r/why.qmd
            - text: "R: the basics"
              href: r/basics.qmd
            - text: Intro R for the humanities
              href: r/intro_hss.qmd
            - text: Packages
              href: r/packages.qmd
            - text: Glimpse at the tidyverse
              href: r/tidyverse.qmd
            - text: Parallel R
              href: r/parallel.qmd
            - text: Resources
              href: r/resources.qmd
            - text: "---"
            - text: Web scraping
              href: r/webscraping.qmd
            - text: "---"
            - text: Intro GIS in R
              href: r/intro_gis.qmd
        - "---"
        - section: Webinars
          contents:
            - text: GIS mapping in R
              href: r/gis_mapping.qmd
            - text: "---"
            - text: Intro HPC in R
              href: r/hpc_intro.qmd
    - id: julia
      collapse-level: 2
      contents:
        - section:
          contents:
            - julia/index.qmd
        - section: Workshops & courses
          contents: 
            - text: Introduction to Julia
              href: julia/intro.qmd
            - text: Basics of the Julia language
              href: julia/basics.qmd
            - text: Collections
              href: julia/collections.qmd
            - text: Types
              href: julia/types.qmd
            - text: Functions
              href: julia/functions.qmd
            - text: Control flow
              href: julia/control_flow.qmd
            - text: Macros
              href: julia/macros.qmd
            - text: Packages
              href: julia/packages.qmd
            - text: Plotting
              href: julia/plotting.qmd
            - text: Working with tabular data
              href: julia/tabular.qmd
            - text: Non interactive execution
              href: julia/non_interactive.qmd
            - text: Intro to HPC in Julia
              href: julia/intro_hpc.qmd
            - text: Performance
              href: julia/performance.qmd
            - text: Multi-threading
              href: julia/multithreading.qmd
            - text: Distributed computing
              href: julia/distributed.qmd
            - text: Resources
              href: julia/resources.qmd
        - "---"
        - section: Webinars
          contents:
            - text: First dab at Julia
              href: julia/firstdab.qmd
            - text: "---"
            - text: Data visualization with Makie
              href: julia/makie.qmd
            - text: "---"
            - text: Machine learning with Flux
              href: julia/flux.qmd
    - id: python
      collapse-level: 2
      contents:
        - section:
          contents:
            - python/index.qmd
        - section: Workshops & courses
          contents: 
            - text: Modules and libraries
              href: python/packages.qmd
            - text: "Python: the basics"
              href: python/basics.qmd
            - text: Collections
              href: python/collections.qmd
            - text: Control flow
              href: python/control_flow.qmd
            - text: Functions
              href: python/functions.qmd
            # - text: Intro to Pandas
            #   href: python/pandas.qmd
            - "---"
            - text: Web scraping
              href: python/webscraping.qmd
            # - text: Intro HPC in Python
            #   href: python/webscraping.qmd
            # - text: Resources
            #   href: python/resources.qmd
    - id: ml
      collapse-level: 2
      contents:
        - section:
          contents:
            - ml/index.qmd
        - section: Workshops & courses
          contents: 
            - text: Overarching concept of DL
              href: ml/concept.qmd
            - text: "Concepts: AI, ML, DL, NN"
              href: ml/nn.qmd
            - text: Which framework to choose?
              href: ml/choosing_frameworks.qmd
            - text: High-level frameworks
              href: ml/high_level_frameworks.qmd
            - text: Intro for the humanities
              href: ml/intro_hss.qmd
            - text: Automatic differentiation
              href: ml/autograd.qmd
            - text: Classifying the MNIST
              href: ml/mnist.qmd
            - text: Building a model
              href: ml/nn_building.qmd
            - text: Training a model
              href: ml/nn_training.qmd
            - text: Audio DataLoader
              href: ml/audio_dataloader.qmd
            - text: ML on production clusters
              href: ml/hpc.qmd
            - text: Finding pre-trained models
              href: ml/pretrained_models.qmd
            - text: Creating checkpoints
              href: ml/checkpoints.qmd
            - text: Resources
              href: ml/resources.qmd
        - "---"
        - section: Webinars
          contents:
            - text: PyTorch tensors
              href: ml/torchtensors.qmd
            - text: "---"
            - text: Image upscaling
              href: ml/upscaling.qmd
            - text: "---"
            - text: fastai
              href: ml/fastai.qmd
            - text: "---"
            - text: ML in Julia with Flux
              href: ml/flux.qmd
    - id: bash
      collapse-level: 2
      contents:
        - section:
          contents:
            - bash/index.qmd
        - section: Workshops & courses
          contents: 
            - text: Scripting for beginners
              href: bash/intro_scripting.qmd
        - "---"
        - section: Webinars
          contents:
            - text: Fun tools
              href: bash/tools1.qmd
            - text: More tools
              href: bash/tools2.qmd
    - id: tools
      collapse-level: 2
      contents:
        - section:
          contents:
            - tools/index.qmd
        - section: Workshops & courses
          contents: 
            - text: Authoring with Quarto
              href: tools/quarto.qmd
        - "---"
        - section: Webinars
          contents:
            - text: Getting help
              href: tools/help.qmd

format:
  html:
    toc: true
    toc-title: Workshop sections
    toc-depth: 5
    theme:
      light: [cosmo, theme.scss]
    code-overflow: wrap
    css: styles.css
    link-external-newwindow: true
    reference-location: margin
    fig-cap-location: margin

execute:
  freeze: auto
  cache: true
  error: true
  echo: true
