project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!*.py"
    - "!*.R"
    - "!*.jl"
    - "!*.org"
    - "!*_old.qmd"
    - "!*_bk.qmd"
    - "!/git/revisiting_old_commits_alternate.qmd"
    - "!/tools/quarto/"
    - "!/tools/quarto_webinar_slides_first_more_wordy_version.qmd"

website:
  title: Research Computing
  image: /img/sfudrac_logo.png
  favicon: /img/sfu_favicon.png
  site-url: https://mint.westdri.ca/
  repo-url: https://github.com/WestDRI/arc-training
  page-navigation: true
  page-footer:
    left:
      - text: About
        href: about.qmd
    center:
      - text: Calendar
        href: calendar.qmd
        aria-label: Training calendar
      - text: Newsletter
        href: newsletter.qmd
        aria-label: Newsletter
    right:
      - text: Contact
        href: contact.qmd
        aria-label: Contact
  navbar:
    background: light
    logo: /img/sfudrac_logo.png
    logo-alt: "SFU & DRAC logos"
    title: false
    left:
      - text: Git
        href: git/index.qmd
      - text: R
        href: r/index.qmd
      - text: Julia
        href: julia/index.qmd
      - text: Python
        href: python/index.qmd
      - text: AI
        href: ai/index.qmd
      - text: Bash
        href: bash/index.qmd
      - text: Tools
        href: tools/index.qmd
    right:
      - icon: github
        href: https://github.com/WestDRI
        target: _blank
        aria-label: GitHub organization
      - icon: wikipedia
        href: https://docs.alliancecan.ca/wiki/Technical_documentation
        target: _blank
        aria-label: Alliance wikipedia
      - icon: youtube
        href: https://www.youtube.com/channel/UCfgds4Qf7VFOv4ORRvFFmhw
        target: _blank
        aria-label: YouTube channel
      - text: Talks
        href: talks/index.qmd
  sidebar:
    - id: git
      collapse-level: 2
      contents:
        - section:
          contents:
            - git/index.qmd
        - text: "<em>All Git pages:</em>"
          href: git/index.qmd
        - "---"
        - section: <b><em>Getting started with Git</em></b>
          href: git/top_intro.qmd
          contents:
            - text: What is Git?
              href: git/intro.qmd
            - text: Installation and setup
              href: git/install.qmd
            - text: Documentation
              href: git/documentation.qmd
            - text: First steps
              href: git/first_steps.qmd
            - text: Excluding from version control
              href: git/ignore.qmd
            - text: Inspecting changes
              href: git/changes.qmd
            - text: Getting information on commits
              href: git/logs.qmd
            # - text: The three trees of Git
              # href: git/three_trees.qmd
            - text: Stashing
              href: git/stash.qmd
            - text: Revisiting old commits
              href: git/time_travel.qmd
            - text: Tags
              href: git/tags.qmd
            - text: Aliases
              href: git/aliases.qmd
            - text: Branches
              href: git/branches.qmd
            - text: Remotes
              href: git/remotes.qmd
            - text: Undoing
              href: git/undo.qmd
            - text: Resources
              href: git/resources.qmd
            - text: Tools for a friendlier Git
              href: git/tools.qmd
        - "---"
        - section: <b><em>Workshops</em></b>
          href: git/practice_repo/search.qmd
          contents:
            - text: Searching a Git project
              href: git/practice_repo/search.qmd
            - text: Collaborating through Git
              href: git/collab.qmd
            - text: Contributing to projects
              href: git/contrib.qmd
    - id: r
      collapse-level: 2
      contents:
        - section:
          contents:
            - r/index.qmd
        - text: "<em>All R pages:</em>"
          href: r/index.qmd
        - "---"
        - section: <em><b>Getting started with R</b></em>
          href: r/top_intro.qmd
          contents: 
            - text: Running R
              href: r/intro_run.qmd
            - text: "R: why and for whom?"
              href: r/intro_why.qmd
            - text: First steps in R
              href: r/intro_basics.qmd
            - text: Packages
              href: r/intro_packages.qmd
            - text: Data types and structures
              href: r/intro_data_structure.qmd
            - text: Indexing
              href: r/intro_indexing.qmd
            - text: Function definition
              href: r/intro_functions.qmd
            - text: Control flow
              href: r/intro_control_flow.qmd
            - text: Introduction to the tidyverse
              href: r/intro_tidyverse.qmd
            - text: Plotting
              href: r/intro_plotting.qmd
            - text: Publishing
              href: r/intro_publishing.qmd
            - text: Resources
              href: r/intro_resources.qmd
        - "---"
        - section: <b><em>High-performance R</em></b>
          href: r/top_hpc.qmd
          contents: 
            - text: SSH login
              href: r/hpc_run.qmd
            - text: R on HPC clusters
              href: r/hpc_clusters.qmd
            - text: Measuring performance
              href: r/hpc_performance.qmd
            - text: Optimizations
              href: r/hpc_optimizations.qmd
            - text: Memory management
              href: r/hpc_memory.qmd
            - text: "Parallelism: concepts"
              href: r/hpc_parallelism.qmd
            # - text: Running R code in parallel
            #   href: r/hpc_parallel_r.qmd
            - text: The future package
              href: r/hpc_future.qmd
            - text: foreach and doFuture
              href: r/hpc_foreach.qmd
            # - text: Data on HPC clusters
              # href: r/hpc_data.qmd
            - text: Partitioning data
              href: r/hpc_partition.qmd
            - text: Writing C++ in R with Rcpp
              href: r/hpc_rcpp.qmd
            - text: Resources for HPC in R
              href: r/hpc_resources.qmd
        - "---"
        - section: <b><em>Workshops</em></b>
          href: r/ws_webscraping.qmd
          contents: 
           - text: Web scraping with R
             href: r/ws_webscraping.qmd
           - text: GIS with R
             href: r/ws_gis_intro.qmd
           - text: Intro R for the humanities
             href: r/ws_hss_intro.qmd
        - "---"
        - section: <em><b>Webinars</b></em>
          href: r/wb_gis_mapping.qmd
          contents:
            - text: GIS mapping with R
              href: r/wb_gis_mapping.qmd
            - text: HPC in R
              href: r/wb_hpc.qmd
    - id: julia
      collapse-level: 2
      contents:
        - section:
          contents:
            - julia/index.qmd
        - text: "<em>All Julia pages:</em>"
          href: julia/index.qmd
        - "---"
        - section: <b><em>Getting started with Julia</em></b>
          href: julia/top_intro.qmd
          contents: 
            - text: Introduction to Julia
              href: julia/intro_intro.qmd
            - text: Basics of the Julia language
              href: julia/intro_basics.qmd
            - text: Collections
              href: julia/intro_collections.qmd
            - text: Types
              href: julia/intro_types.qmd
            - text: Functions
              href: julia/intro_functions.qmd
            - text: Control flow
              href: julia/intro_control_flow.qmd
            - text: Macros
              href: julia/intro_macros.qmd
            - text: Packages
              href: julia/intro_packages.qmd
            - text: Plotting
              href: julia/intro_plotting.qmd
            - text: Working with tabular data
              href: julia/intro_tabular.qmd
            - text: Non interactive execution
              href: julia/intro_non_interactive.qmd
            - text: Resources
              href: julia/intro_resources.qmd
        - "---"
        - section: <b><em>High-performance Julia</em></b>
          href: julia/top_hpc.qmd
          contents: 
            - text: Intro to HPC in Julia
              href: julia/hpc_intro.qmd
            - text: Performance
              href: julia/hpc_performance.qmd
            - text: Multi-threading
              href: julia/hpc_multithreading.qmd
            - text: Distributed computing
              href: julia/hpc_distributed.qmd
        - "---"
        - section: <b><em>Webinars</em></b>
          href: julia/wb_makie.qmd
          contents:
            - text: Data visualization with Makie
              href: julia/wb_makie.qmd
            - text: First dab at Julia
              href: julia/wb_firstdab.qmd
            - text: Deep learning with Flux
              href: julia/wb_flux.qmd
    - id: python
      collapse-level: 2
      contents:
        - section:
          contents:
            - python/index.qmd
        - text: "<em>All Python pages:</em>"
          href: python/index.qmd
        - "---"
        - section: <b><em>Getting started</em></b>
          href: python/top_intro.qmd
          contents: 
            - text: Running Python
              href: python/run.qmd
            - text: "Python: the basics"
              href: python/basics.qmd
            - text: Collections
              href: python/collections.qmd
            - text: Control flow
              href: python/control_flow.qmd
            - text: Functions
              href: python/functions.qmd
            # - text: Modules and libraries
            #   href: python/packages.qmd
            # - text: Intro HPC in Python
            #   href: python/intro_hpc.qmd
            # - text: Resources
            #   href: python/resources.qmd
        - "---"
        - section: <em><b>Workshops</b></em>
          href: python/webscraping.qmd
          contents: 
            - text: Web scraping with Python
              href: python/webscraping.qmd
            - text: DataFrames with Pandas
              href: python/pandas.qmd
    - id: ai
      collapse-level: 2
      contents:
        - section:
          contents:
            - ai/index.qmd
        - text: "<em>All AI pages:</em>"
          href: ai/index.qmd
        - "---"
        - section: <b><em>PyTorch</em></b>
          href: ai/top_pt.qmd
          contents: 
            - text: Introduction
              href: ai/pt_intro.qmd
            - text: Which framework to choose?
              href: ai/pt_choosing_frameworks.qmd
            - text: High-level frameworks
              href: ai/pt_high_level_frameworks.qmd
            - text: Introduction to NN
              href: ai/pt_nn.qmd
            - text: The PyTorch API
              href: ai/pt_pytorch.qmd
            - text: PyTorch tensors
              href: ai/pt_tensors.qmd
            # - text: Loading data
              # href: ai/pt_data.qmd
            # - text: Building models
              # href: ai/pt_model.qmd
            - text: Automatic differentiation
              href: ai/pt_autograd.qmd
            - text: Workflow
              href: ai/pt_workflow.qmd
            # - text: Training
              # href: ai/pt_training.qmd
            - text: Creating checkpoints
              href: ai/pt_checkpoints.qmd
            - text: "Example: the MNIST"
              href: ai/pt_mnist.qmd
            - text: DL on production clusters
              href: ai/pt_hpc.qmd
            - text: Resources
              href: ai/pt_resources.qmd
        - "---"
        - section: <b><em>JAX</em></b>
          href: ai/top_jx.qmd
          contents: 
            - text: Why JAX?
              href: ai/jx_why.qmd
            - text: How does JAX work?
              href: ai/jx_map.qmd
            - text: Relation to NumPy
              href: ai/jx_numpy.qmd
            - text: JIT subtleties
              href: ai/jx_jit.qmd
            - text: Automatic differentiation
              href: ai/jx_ad.qmd
            - text: Pytrees
              href: ai/jx_pytree.qmd
            - text: Parallel computing
              href: ai/jx_parallel.qmd
        - "---"
        - section: <b><em>Flax</em></b>
          href: ai/top_fl.qmd
          contents:
            - text: Deep learning with JAX
              href: ai/fl_jaxdl.qmd
        - "---"
        - section: <b><em>Scikit-learn</em></b>
          href: ai/sk_intro.qmd
          contents: 
            - text: What is scikit-learn?
              href: ai/sk_intro.qmd
            - text: Sklearn workflow
              href: ai/sk_workflow.qmd
        - "---"
        - section: <b><em>Workshops</em></b>
          href: ai/ws_audio_dataloader.qmd
          contents: 
            - text: Audio DataLoader
              href: ai/ws_audio_dataloader.qmd
            - text: Finding pre-trained models
              href: ai/ws_pretrained_models.qmd
            - text: Intro ML for the humanities
              href: ai/ws_hss_intro.qmd
        # - "---"
        # - section: <b><em>DL readings</em></b>
          # href: ai/concepts.qmd
          # contents: 
            # - text: "Concepts: AI, ML, DL, NN"
              # href: ai/concepts.qmd
            # - text: Supervised learning
              # href: ai/supervised_learning.qmd
        - "---"
        - section: <b><em>Webinars</em></b>
          href: ai/wb_frameworks.qmd
          contents:
            - text: Map of current frameworks
              href: ai/wb_frameworks.qmd
            - text: Data version control
              href: ai/wb_dvc.qmd
            - text: PyTorch tensors
              href: ai/wb_torchtensors.qmd
            - text: Image upscaling
              href: ai/wb_upscaling.qmd
            - text: fastai
              href: ai/wb_fastai.qmd
            - text: DL in Julia with Flux
              href: ai/wb_flux.qmd
    - id: bash
      collapse-level: 2
      contents:
        - section:
          contents:
            - bash/index.qmd
        - text: "<em>All Bash pages:</em>"
          href: bash/index.qmd
        - "---"
        - section: <b><em>Getting started with Bash</em></b>
          href: bash/top_intro.qmd
          contents: 
            - text: Introduction
              href: bash/introduction.qmd
            - text: "Bash: the basics"
              href: bash/basics.qmd
            - text: The Unix filesystem
              href: bash/filesystem.qmd
            - text: Variables
              href: bash/variables.qmd
            - text: Wildcards
              href: bash/molecules/wildcards.qmd
            - text: Redirections & pipes
              href: bash/molecules/redirections.qmd
            - text: Control flow
              href: bash/molecules/control_flow.qmd
            - text: Functions
              href: bash/functions.qmd
            - text: Special parameters
              href: bash/special_parameters.qmd
            - text: Aliases
              href: bash/aliases.qmd
            - text: Writing scripts
              href: bash/molecules/script.qmd
            # - text: Finding files
              # href: bash/molecules/find.qmd
            # - text: Archives
              # href: bash/archives.qmd
            - text: Transferring files
              href: bash/transfer.qmd
            - text: Resources
              href: bash/resources.qmd
        - "---"
        - section: <b><em>Workshops</em></b>
          href: bash/intro_scripting.qmd
          contents: 
            - text: Scripting for beginners
              href: bash/intro_scripting.qmd
            - text: Searching & manipulating text
              href: bash/text.qmd
        - "---"
        - section: <b><em>Webinars</em></b>
          href: bash/tools1.qmd
          contents:
            - text: Fun tools
              href: bash/tools1.qmd
            - text: More fun tools
              href: bash/tools2.qmd
    - id: tools
      collapse-level: 2
      contents:
        - section:
          contents:
            - tools/index.qmd
        - text: "<em>All tools pages:</em>"
          href: tools/index.qmd
        - "---"
        - section: <em><b>Workshops</b></em>
          href: tools/quarto.qmd
          contents: 
            - text: Authoring with Quarto
              href: tools/quarto.qmd
        - "---"
        - section: <b><em>Webinars</em></b>
          href: tools/emacs_prog_ide.qmd
          contents:
            - text: Emacs as a programming IDE
              href: tools/emacs_prog_ide.qmd
            - text: "Quarto: the new R Markdown"
              href: tools/quarto_webinar.qmd
            - text: Getting help
              href: tools/help.qmd
    - id: talks
      collapse-level: 2
      contents:
        - section:
          contents:
            - talks/index.qmd
        - section: "<em><b>Conference talks</b></em>"
          href: talks/2023_driconnect.qmd
          contents:
            - text: DRI Connect Spring 2023
              href: talks/2023_driconnect.qmd
 
format:
  html:
    toc: true
    toc-title: "<em>On this page:</em>"
    toc-depth: 5
    theme:
      light: [cosmo, theme.scss]
    css: styles.css
    link-external-newwindow: true
    reference-location: margin
    fig-cap-location: margin

execute:
  freeze: auto
  cache: true
  error: true
  echo: true
