project:
  type: website

website:
  title: WestDRI
  image: sfudrac.png
  favicon: sfu_favicon.png
  site-url: https://arc-training.westdri.ca/
  repo-url: https://github.com/WestDRI/arc-training
  page-navigation: true
  reader-mode: true
  page-footer:
    left: For our main site, see [https://training.westdri.ca/](https://training.westdri.ca/){target="_blank"}
    center:
      - icon: github
        href: https://github.com/WestDRI
        aria-label: WestDRI GitHub
      - icon: youtube
        href: https://www.youtube.com/channel/UCfgds4Qf7VFOv4ORRvFFmhw
        aria-label: WestDRI YouTube
      - icon: calendar-event
        href: https://github.com/WestDRI/arc-training/calendar
        aria-label: WestDRI training calendar
    right:
      - icon: envelope-paper-fill
        href: https://github.com/WestDRI/arc-training/newsletter
        aria-label: WestDRI Newsletter
      - icon: mailbox2
        href: https://github.com/WestDRI/arc-training/contact
        aria-label: WestDRI Contact
  navbar:
    background: light
    logo: sfudrac.png
    logo-alt: "SFU & DRAC logos"
    title: WestDRI
    collapse-below: lg
    left:
      - text: Git
        href: git/map.qmd
      - text: R
        href: r/map.qmd
      - text: Julia
        href: julia/map.qmd
      - text: Python
        href: python/map.qmd
      - text: ML
        href: ml/map.qmd
      - text: Shell
        href: shell/map.qmd
      - text: Other
        href: other/map.qmd
    right:
      - icon: map-fill
        href: https://github.com/WestDRI/arc-training/sitemap
  sidebar:
    - id: git
      contents:
        - section:
          contents:
            - git/map.qmd
        - section: Workshops
          contents:
            - text: Intro Git & GitHub
              href: git/2022_git_sfu.qmd
            - git/callouts.qmd
        - "---"
        - section: Webinars
          contents:
        - "---"
        - section: Courses
    - id: r
      contents:
        - section:
          contents:
            - r/map.qmd
        - section: Workshops
          contents: 
        - "---"
        - section: Webinars
          contents:
        - "---"
        - section: Courses
    - id: julia
      contents:
        - section:
          contents:
            - julia/map.qmd
        - section: Workshops
          contents: 
        - "---"
        - section: Webinars
          contents:
        - "---"
        - section: Courses
    - id: python
      contents:
        - section:
          contents:
            - python/map.qmd
        - section: Workshops
          contents: 
        - "---"
        - section: Webinars
          contents:
        - "---"
        - section: Courses
    - id: ml
      contents:
        - section:
          contents:
            - ml/map.qmd
        - section: Workshops
          contents: 
        - "---"
        - section: Webinars
          contents:
        - "---"
        - section: Courses
    - id: shell
      contents:
        - section:
          contents:
            - shell/map.qmd
        - section: Workshops
          contents: 
        - "---"
        - section: Webinars
          contents:
        - "---"
        - section: Courses
    - id: other
      contents:
        - section:
          contents:
            - other/map.qmd
        - section: Workshops
          contents: 
        - "---"
        - section: Webinars
          contents:
        - "---"
        - section: Courses
format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss]
    code-overflow: wrap
    css: styles.css
    include-after-body: js.html
    grid:
      sidebar-width: 250px
      body-width: 900px
    comments:
      giscus: 
        repo: WestDRI/arc-training
