project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!/tools/quarto/"

website:
  title: WestDRI
  image: /img/sfudrac_logo.png
  favicon: /img/sfu_favicon.png
  site-url: https://mint.westdri.ca/
  repo-url: https://github.com/WestDRI/arc-training
  reader-mode: true
  page-navigation: true
  page-footer:
    left:
      Please also visit our **[main website](https://training.westdri.ca/){target="_blank"}**
    center:
      - text: About
        href: about.qmd
      - text: Calendar
        href: calendar.qmd
        aria-label: WestDRI training calendar
      - text: Newsletter
        href: newsletter.qmd
        aria-label: WestDRI Newsletter
      - href: contact.qmd
        aria-label: WestDRI Contact
    right:
      - icon: github
        href: https://github.com/WestDRI
        aria-label: WestDRI GitHub
      - icon: youtube
        href: https://www.youtube.com/channel/UCfgds4Qf7VFOv4ORRvFFmhw
        aria-label: WestDRI YouTube
  navbar:
    background: light
    logo: /img/sfudrac_logo.png
    logo-alt: "SFU & DRAC logos"
    left:
      - text: Git
        href: git/index.qmd
      - text: R
        href: r/index.qmd
      - text: Julia
        href: julia/index.qmd
      # - text: Python
        # href: python/index.qmd
      - text: ML
        href: ml/index.qmd
      - text: Bash
        href: bash/index.qmd
      - text: Research tools
        href: tools/index.qmd
  sidebar:
    - id: git
      collapse-level: 2
      contents:
        - section:
          contents:
            - git/index.qmd
        - section: Workshops & courses
          contents:
            - text: Intro Git & GitHub
              href: git/intro.qmd
            - text: Searching history
              href: git/search.qmd
            # - text: Collaborating through Git
              # href: git/collab.qmd
            # - text: Contributing to GitHub projects
              # href: git/contrib.qmd
    - id: r
      collapse-level: 2
      contents:
        - section:
          contents:
            - r/index.qmd
        - section: Workshops & courses
          contents: 
            - text: "R: the basics"
              href: r/basics.qmd
            - text: Intro R for the humanities
              href: r/intro_hss.qmd
            - text: Web scraping with R
              href: r/webscraping.qmd
            # - text: HPC in R
              # href: r/hpc.qmd
            # - text: Parallel R
              # href: r/parallel.qmd
            - text: Intro GIS in R
              href: r/intro_gis.qmd
        - "---"
        - section: Webinars
          contents:
            - text: Intro HPC in R
              href: r/hpc_intro.qmd
            - text: GIS mapping in R
              href: r/gis_mapping.qmd
    - id: julia
      collapse-level: 2
      contents:
        - section:
          contents:
            - julia/index.qmd
        - section: Workshops & courses
          contents: 
            - text: Intro to HPC in Julia
              href: julia/intro_hpc.qmd
            - text: Working with tabular data
              href: julia/tabular.qmd
        - "---"
        - section: Webinars
          contents:
            - text: Data visualization with Makie
              href: julia/makie.qmd
            - text: Machine learning with Flux
              href: julia/flux.qmd
            - text: First dab at Julia
              href: julia/firstdab.qmd
    # - id: python
    #   collapse-level: 2
    #   contents:
    #     - section:
    #       contents:
    #         - python/index.qmd
    #     - section: Workshops & courses
    - id: ml
      collapse-level: 2
      contents:
        - section:
          contents:
            - ml/index.qmd
        - section: Workshops & courses
          contents: 
            - text: Intro for the humanities
              href: ml/intro_hss.qmd
            - text: Classifying the MNIST
              href: ml/mnist.qmd
            - text: Automatic differentiation
              href: ml/autograd.qmd
        - "---"
        - section: Webinars
          contents:
            - text: Finding pre-trained models
              href: ml/pretrained_models.qmd
            - text: PyTorch tensors
              href: ml/torchtensors.qmd
            - text: Image upscaling
              href: ml/upscaling.qmd
            - text: fastai
              href: ml/fastai.qmd
            - text: ML in Julia with Flux
              href: ml/flux.qmd
    - id: bash
      collapse-level: 2
      contents:
        - section:
          contents:
            - bash/index.qmd
        - section: Workshops & courses
          contents: 
            - text: Scripting for beginners
              href: bash/intro_scripting.qmd
        - "---"
        - section: Webinars
          contents:
            - text: Fun tools
              href: bash/tools1.qmd
            - text: More tools
              href: bash/tools2.qmd
    - id: tools
      collapse-level: 2
      contents:
        - section:
          contents:
            - tools/index.qmd
        - section: Workshops & courses
          contents: 
            - text: Authoring with Quarto
              href: tools/quarto.qmd
        - "---"
        - section: Webinars
          contents:
            - text: Getting help
              href: tools/help.qmd

format:
  html:
    toc: true
    toc-title: Table of contents
    theme:
      light: [cosmo, theme.scss]
    code-overflow: wrap
    css: styles.css
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
    link-external-newwindow: true
    reference-location: margin

execute:
  freeze: auto
  cache: true
  error: true
  echo: true
