project:
  type: website
  output-dir: _site

website:
  title: WestDRI
  image: /img/sfudrac_logo.png
  favicon: /img/sfu_favicon.png
  site-url: https://arc-training.westdri.ca
  repo-url: https://github.com/WestDRI/arc-training
  repo-actions: [edit, issue]
  reader-mode: true
  page-footer:
    left:
      Please also visit our [main website](https://training.westdri.ca/){target="_blank"}
    center:
      # © 2022 [SFU](https://www.sfu.ca/){target="_blank"} & [DRAC](https://alliancecan.ca/){target="_blank"}
      - text: About
        href: about.qmd
      - text: Calendar
        href: calendar.qmd
        aria-label: WestDRI training calendar
      - text: Newsletter
        href: newsletter.qmd
        aria-label: WestDRI Newsletter
      - href: contact.qmd
        aria-label: WestDRI Contact
    right:
      - icon: github
        href: https://github.com/WestDRI
        aria-label: WestDRI GitHub
      - icon: youtube
        href: https://www.youtube.com/channel/UCfgds4Qf7VFOv4ORRvFFmhw
        aria-label: WestDRI YouTube
  navbar:
    background: light
    logo: /img/sfudrac_logo.png
    logo-alt: "SFU & DRAC logos"
    left:
      - text: Git
        href: git/index.qmd
      - text: R
        href: r/index.qmd
      - text: Julia
        href: julia/index.qmd
      - text: Python
        href: python/index.qmd
      - text: ML
        href: ml/index.qmd
      - text: Shell
        href: shell/index.qmd
      - text: Other
        href: other/index.qmd
  sidebar:
    - id: git
      collapse-level: 1
      contents:
        - section:
          contents:
            - git/index.qmd
        - section: Workshops
          contents:
            - text: Intro Git & GitHub
              href: git/intro.qmd
        - "---"
        - section: Webinars
          contents:
        - "---"
        - section: Courses
    - id: r
      collapse-level: 1
      contents:
        - section:
          contents:
            - r/index.qmd
        - section: Workshops
          contents: 
        - "---"
        - section: Webinars
          contents:
            - text: HPC in R
              href: r/r_parallel.qmd
        - "---"
        - section: Courses
    - id: julia
      collapse-level: 1
      contents:
        - section:
          contents:
            - julia/index.qmd
        - section: Workshops
          contents: 
        - "---"
        - section: Webinars
          contents:
        - "---"
        - section: Courses
    - id: python
      collapse-level: 1
      contents:
        - section:
          contents:
            - python/index.qmd
        - section: Workshops
          contents: 
        - "---"
        - section: Webinars
          contents:
        - "---"
        - section: Courses
    - id: ml
      collapse-level: 1
      contents:
        - section:
          contents:
            - ml/index.qmd
        - section: Workshops
          contents: 
        - "---"
        - section: Webinars
          contents:
        - "---"
        - section: Courses
    - id: shell
      collapse-level: 1
      contents:
        - section:
          contents:
            - shell/index.qmd
        - section: Workshops
          contents: 
        - "---"
        - section: Webinars
          contents:
        - "---"
        - section: Courses
    - id: other
      collapse-level: 1
      contents:
        - section:
          contents:
            - other/index.qmd
        - section: Workshops
          contents: 
        - "---"
        - section: Webinars
          contents:
        - "---"
        - section: Courses

format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss]
    code-overflow: wrap
    css: styles.css
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
    link-external-newwindow: true

execute:
  freeze: auto
