---
title: About this site
title-block-banner: true
toc: false
anchor-sections: false
---

This site contains [Marie-Hélène Burle](https://www.sfu.ca/~msb2/)'s latest content. \
Her older training material can be found on the archived sites:

- [Shell, Git, R, Python, etc.](https://prog.westdri.ca/)
- [Julia training material](https://julia.westdri.ca/)
- [Machine learning training material](https://ml.westdri.ca/)
<br><br>

## Our main training website
This is the [mint](index.qmd) ("**m**int **i**s **n**ot **t**raining") website. \
To view all our training material, please visit the [training](https://training.westdri.ca/) website.

## Our other websites

In addition, here are a few of our websites for various training events:

- [Coding Fundamentals for Humanists 2026](https://dhsi-2026.netlify.app/) for the [Digital Humanities Summer Institute](https://dhsi.org/)
- [SFU Summer School 2026](https://sfu26.netlify.app/)
- [Coding Fundamentals for Humanists 2025](https://dhsi-2025.netlify.app/) for the [Digital Humanities Summer Institute](https://dhsi.org/)
- [SFU Summer School 2025](https://sfu25.netlify.app/)
- [Coding Fundamentals for Humanists 2024](https://dhsi-2024.netlify.app/) for the [Digital Humanities Summer Institute](https://dhsi.org/)
- [SFU Summer School 2024](https://rcss24.netlify.app/)
- [Coding Fundamentals for Humanists 2023](https://dhsi-2023.netlify.app/) for the [Digital Humanities Summer Institute](https://dhsi.org/)
- [Uvic Summer School 2023](https://2023uvic.netlify.app/)
- [SFU Summer School 2023](https://2023sfu.netlify.app/)
- [HSS Winter Series 2023](https://hss23.netlify.app/)
- [Autumn School 2022](https://autumnschool2022.westdri.ca/)
- [Training Modules 2022](https://rcmodules22.netlify.app/)
- [HSS Winter Series 2022](https://hss-series-2022.netlify.app/)
- [Coding Fundamentals for Humanists 2022](https://dhsi-2022.netlify.app/) for the [Digital Humanities Summer Institute](https://dhsi.org/)
- [Training Modules 2021](https://wgtm21.netlify.app/)
- [Coding Fundamentals for Humanists 2021](https://dhsi-2021.netlify.app/) for the [Digital Humanities Summer Institute](https://dhsi.org/)
- [Summer School 2020](https://wgschool.netlify.app/)
