[[redirects]]
from = "/ml/*"
to = "/ai/:splat"

[[redirects]]
from = "/ai/pt_*"
to = "/ai/pt/pt_:splat"

[[redirects]]
from = "/ai/jx_*"
to = "/ai/jx/jx_:splat"

[[redirects]]
from = "/ai/fl_*"
to = "/ai/jx/fl_:splat"
