[[redirects]]
from = "/ml/*"
to = "/ai/:splat"

[[redirects]]
from = "/ai/pt_*"
to = "/ai/pt/:splat"

[[redirects]]
from = "/ai/jx_*"
to = "/ai/jx/:splat"

[[redirects]]
from = "/ai/fl_*"
to = "/ai/jx/:splat"
