{
  "hash": "00eb2fa929ec20452c95dfb080297942",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: Compiling the metadata\nauthor: Marie-Hélène Burle\n---\n\n:::{.def}\n\nIn this section, we process some of the metadata associated with the NABirds dataset by creating a [Polars](https://github.com/pola-rs/polars) DataFrame collecting all the information we will need while processing the images and training our model. This allows us to get some information about the dataset.\n\n*[Polars](/python/hpc_polars) is a modern and ultra fast package that you should use instead of [pandas](https://github.com/pandas-dev/pandas) whenever you can if you care about performance.*\n\n:::\n\n## Metadata files\n\nIn addition to images, the dataset comes with a number of text files. To understand the dataset, of course, the place to start is by reading ... the README.\n\nYou can find it in full in this accordion box, with a summary below:\n\n:::{.callout-note collapse=\"true\"}\n\n## README\n\n### The nabirds dataset\n\n#### Versions\n\nv0 - June 2015: initial release\n\nFor more information about the dataset, visit the project websites:\n\n  http://www.vision.caltech.edu/visipedia\n  http://vision.cornell.edu/se3/projects/visipedia/\n  http://dl.allaboutbirds.org/nabirds\n\nIf you use the dataset in a publication, please cite the dataset in the style described on the dataset website (see url above).\n\nPlease see the nabirds.py file for example code on using the data. You can visualize images and annotations by running: python nabirds.py\nMake sure you are in the nabirds/ directory.\n\n#### Directory information\n\n- images/\n\n\tThe images organized in subdirectories based on species. See IMAGES AND CLASS LABELS section below for more info.\n\n- parts/\n\n\t11 part locations per image. See PART LOCATIONS section below for more info.\n\n### Images and class labels\n\nImages are contained in the directory images/, with 555 subdirectories (one for each bird category).\n\n#### List of image files (images.txt)\n\nThe list of image file names is contained in the file images.txt, with each line corresponding to one image:\n\n<image_id> <image_name>\n\n#### Train/test split (train_test_split.txt)\n\nThe suggested train/test split is contained in the file train_test_split.txt, with each line corresponding to one image:\n\n<image_id> <is_training_image>\n\nwhere <image_id> corresponds to the ID in images.txt, and a value of 1 or 0 for <is_training_image> denotes that the file is in the training or test set, respectively.\n\n#### Image sizes (sizes.txt)\n\nThe size of each image in pixels:\n\n<image_id> <width> <height>\n\nwhere <image_id> corresponds to the ID in images.txt, and <width> and <height> correspond to the width and height of the image in pixels.\n\n#### Image photographers (photographers.txt)\n\nThe photographer for each image:\n\n<image_id> <photographer_name>\n\nwhere <image_id> corresponds to the ID in images.txt, and <photographer_name> corresponds to the name of the photographer that took the photo. Please\nbe considerate and display the photographer's name when displaying their image.\n\n#### List of class names (classes.txt)\n\nThe list of class names (bird species) is contained in the file classes.txt, with each line corresponding to one class:\n\n<class_id> <class_name>\n\n#### Image class labels (image_class_labels.txt)\n\nThe ground truth class labels (bird species labels) for each image are contained in the file image_class_labels.txt, with each line corresponding to one image:\n\n<image_id> <class_id>\n\nwhere <image_id> and <class_id> correspond to the IDs in images.txt and classes.txt, respectively.\n\n#### Class hierarchy (hierarchy.txt)\n\nThe ground truth class labels (bird species labels) for each image are contained in the file image_class_labels.txt, with each line corresponding to one image:\n\n<child_class_id> <parent_class_id>\n\nwhere <child_class_id> and <parent_class_id> correspond to the IDs in classes.txt.\n\n### Bounding boxes\n\nEach image contains a single bounding box label.  Bounding box labels are contained in the file bounding_boxes.txt, with each line corresponding to one image:\n\n<image_id> <x> <y> <width> <height>\n\nwhere <image_id> corresponds to the ID in images.txt, and <x>, <y>, <width>, and <height> are all measured in pixels.\n\n### Part locations\n\n#### List of part names (parts/parts.txt)\n\nThe list of all part names is contained in the file parts/parts.txt, with each line corresponding to one part:\n\n<part_id> <part_name>\n\n#### Part locations (parts/part_locs.txt)\n\nThe set of all ground truth part locations is contained in the file parts/part_locs.txt, with each line corresponding to the annotation of a particular part in a particular image:\n\n<image_id> <part_id> <x> <y> <visible>\n\nwhere <image_id> and <part_id> correspond to the IDs in images.txt and parts/parts.txt, respectively.  <x> and <y> denote the pixel location of the center of the part.  <visible> is 0 if the part is not visible in the image and 1 otherwise.\n\n:::\n\nEach image is associated with a [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier).\n\nWe won't need all the information provided with this dataset for this course, but what we need is contained in the following files:\n\nName | Content\n---| -------\nbounding_boxes.txt | List of UUIDs and their corresponding bounding boxes (one bounding box per image, just around the bird)\nclasses.txt | List of class ids and corresponding class names\nimage_class_labels.txt | List of UUIDs and their corresponding class ids\nimages.txt | List of UUIDs and their corresponding file names\nphotographers.txt | List of UUIDs and their corresponding photographers\ntrain_test_split.txt | List of UUIDs and 1 or 0 depending on whether the image is for training or validation respectively (the dataset comes with a suggested split)\n\nThe README has one request:\n\n> Please be considerate and display the photographer's name when displaying their image.\n\nWe will make sure to follow it.\n\n## Clean problem files\n\nTwo of the files are problematic because they are jagged: the number of elements per line is inconsistent.\n\nLet's create a cleaning function that writes cleaned up copies of the files:\n\n::: {#13486977 .cell execution_count=1}\n``` {.python .cell-code}\ndef clean_classes_file(input_filepath, output_filepath):\n    \"\"\"\n    Remove commas, remove parenthesis, and replace all spaces except the first space\n    on each line and the space between species name and subcategory info with underscores.\n\n    Args:\n        input_filepath (str): the path of the input file.\n        output_filepath (str): the path of the output file.\n    \"\"\"\n    with open(input_filepath, 'r') as infile, \\\n         open(output_filepath, 'w') as outfile:\n\n        for line in infile:\n            # Remove commas and ending parenthesis\n            cleaned_line = line.replace(',', '').replace(')', '')\n\n            # Strip newline characters\n            cleaned_line = cleaned_line.strip()\n\n            # Split line into two parts based on the first space\n            parts = cleaned_line.split(' ', 1)\n\n            # Replace spaces in the second part with underscores\n            part2_cleaned = parts[1].replace(' ', '_').replace('_(', ' ')\n\n            final_line = f'{parts[0]} {part2_cleaned}\\n'\n\n            outfile.write(final_line)\n```\n:::\n\n\n::: {#ed62677a .cell execution_count=2}\n``` {.python .cell-code}\ndef clean_photographer_file(input_filepath, output_filepath):\n    \"\"\"\n    Remove commas, remove quotes, and replace all spaces except the first space\n    on each line with underscores.\n\n    Args:\n        input_filepath (str): the path of the input file.\n        output_filepath (str): the path of the output file.\n    \"\"\"\n    with open(input_filepath, 'r') as infile, \\\n         open(output_filepath, 'w') as outfile:\n\n        for line in infile:\n            # Remove quotes and commas\n            cleaned_line = line.replace('\"', '').replace(',', '')\n\n            # Strip newline characters\n            cleaned_line = cleaned_line.strip()\n\n            # Split line into two parts based on the first space\n            parts = cleaned_line.split(' ', 1)\n\n            # Replace spaces in the second part with underscores\n            part2_cleaned = parts[1].replace(' ', '_')\n\n            final_line = f'{parts[0]} {part2_cleaned}\\n'\n\n            outfile.write(final_line)\n```\n:::\n\n\nThen we can apply the function on our files:\n\n```{.python}\nbase_dir = '<path-of-the-nabirds-dir>'\n```\n\n:::{.notenoit}\n\nTo be replaced by actual path: in our training cluster, the `base_dir` is at `/project/def-sponsor00/nabirds`:\n\n```{.python}\nbase_dir = '/project/def-sponsor00/nabirds'\n```\n\n:::\n\n\n\n::: {#f23f3edf .cell execution_count=4}\n``` {.python .cell-code}\nimport os\n\nclean_photographer_file(\n    os.path.join(base_dir, 'photographers.txt'),\n    os.path.join(base_dir, 'photographers_cleaned.txt')\n)\n\nclean_classes_file(\n    os.path.join(base_dir, 'classes.txt'),\n    os.path.join(base_dir, 'classes_cleaned.txt')\n)\n```\n:::\n\n\n## Create variables\n\nFor convenience, let's create variables with the path of the various files we need:\n\n::: {#41aa452d .cell execution_count=5}\n``` {.python .cell-code}\nbb_file = os.path.join(base_dir, 'bounding_boxes.txt')\nclass_id_to_name_file = os.path.join(base_dir, 'classes_cleaned.txt')\nclass_id_file = os.path.join(base_dir, 'image_class_labels.txt')\npath_file = os.path.join(base_dir, 'images.txt')\nphotographer_file = os.path.join(base_dir, 'photographers_cleaned.txt')\ntrain_test_split_file = os.path.join(base_dir, 'train_test_split.txt')\n```\n:::\n\n\n## Create a metadata DataFrame\n\nNow it's time to put all the data together in one DataFrame.\n\nFirst, we create a series of DataFrames from each text file:\n\n::: {#92126aee .cell execution_count=6}\n``` {.python .cell-code}\nimport polars as pl\n\nbb = pl.read_csv(\n    bb_file,\n    separator=' ',\n    has_header=False,\n    new_columns=['UUID', 'bb_x', 'bb_y', 'bb_width', 'bb_height']\n)\n\nclass_id = pl.read_csv(\n    class_id_file,\n    separator=' ',\n    has_header=False,\n    new_columns=['UUID', 'class_id']\n)\n```\n:::\n\n\nThe `class_id_to_name_file` is also fairly complicated: some bird species name are followed by additional information (e.g. \"Adult\" or \"Immature\") in parenthesis. If we want to train a model to identify bird species (rather than classes including the subcategories), we need to separate the two.\n\n:::{.notenoit}\n\nAn easy way to quickly check what that additional information looks like is to run **in the terminal, not in Python**:\n\n```{.bash}\nrg \"\\(\" /project/def-sponsor00/nabirds/classes.txt | fzf\n```\n\n:::\n\nIn order to split species name on the one hand and additional information on the other, we need to create 3 columns instead of 2 for this file. The problem is that many rows only have 2 elements (the additional info is not often present).\n\nThe shell command above allows to quickly look for the first occurrence of the additional info: it appears at line 295.\n\nPolars scans the first 100 elements by default to determine the [schema](https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.schema.html) or mapping for the DataFrame. We need to increase this value to at least 295 to make sure that it detects the 3^rd^ column during the reading in of the file:\n\n::: {#35420d88 .cell execution_count=7}\n``` {.python .cell-code}\nclass_id_to_name = pl.read_csv(\n    class_id_to_name_file,\n    separator=' ',\n    has_header=False,\n    infer_schema_length=296,\n    new_columns=['class_id', 'species', 'subcategory']\n)\n```\n:::\n\n\n::: {#ccf943aa .cell execution_count=8}\n``` {.python .cell-code}\npath = pl.read_csv(\n    path_file,\n    separator=' ',\n    has_header=False,\n    new_columns=['UUID', 'path']\n)\n\nphotographer = pl.read_csv(\n    photographer_file,\n    separator=' ',\n    has_header=False,\n    new_columns=['UUID', 'photographer']\n)\n\ntrain_test_split = pl.read_csv(\n    train_test_split_file,\n    separator=' ',\n    has_header=False,\n    new_columns=['UUID', 'is_training_img']\n)\n```\n:::\n\n\n:::{.note}\n\nWe can use `polars.read_csv` even though we have text files because our files are space separated value files. So they function like CSV files with the exception that we have to set the value of the `separator` argument to ` `.\n\n:::\n\nThen we can combine the two DataFrames dealing with classes so that the birds identifications becomes directly associated with the birds UUIDs:\n\n::: {#4f65fe71 .cell execution_count=9}\n``` {.python .cell-code}\nclasses_metadata = (\n    class_id.join(class_id_to_name, on='class_id')\n)\n```\n:::\n\n\nFinally, we combine all the DataFrames:\n\n::: {#27deb1ec .cell execution_count=10}\n``` {.python .cell-code}\nmetadata = (\n    bb.join(classes_metadata, on='UUID')\n    .join(path, on='UUID')\n    .join(photographer, on='UUID')\n    .join(train_test_split, on='UUID')\n)\n```\n:::\n\n\n## Sanity checks\n\nLet's see what our DataFrame looks like:\n\n```{.python}\nprint(metadata)\n```\n\n::: {#cb23ba86 .cell execution_count=11}\n\n::: {.cell-output .cell-output-display execution_count=11}\n```{=html}\n<div><style>\n.dataframe > thead > tr,\n.dataframe > tbody > tr {\n  text-align: right;\n  white-space: pre-wrap;\n}\n</style>\n<small>shape: (48_562, 11)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>UUID</th><th>bb_x</th><th>bb_y</th><th>bb_width</th><th>bb_height</th><th>class_id</th><th>species</th><th>subcategory</th><th>path</th><th>photographer</th><th>is_training_img</th></tr><tr><td>str</td><td>i64</td><td>i64</td><td>i64</td><td>i64</td><td>i64</td><td>str</td><td>str</td><td>str</td><td>str</td><td>i64</td></tr></thead><tbody><tr><td>&quot;0000139e-21dc-4d0c-bfe1-4cae3c…</td><td>83</td><td>59</td><td>128</td><td>228</td><td>817</td><td>&quot;Oak_Titmouse&quot;</td><td>null</td><td>&quot;0817/0000139e21dc4d0cbfe14cae3…</td><td>&quot;Ruth_Cantwell&quot;</td><td>0</td></tr><tr><td>&quot;0000d9fc-4e02-4c06-a0af-a55cfb…</td><td>328</td><td>88</td><td>163</td><td>298</td><td>860</td><td>&quot;Ovenbird&quot;</td><td>null</td><td>&quot;0860/0000d9fc4e024c06a0afa55cf…</td><td>&quot;Christopher_L._Wood_Chris_Wood&quot;</td><td>0</td></tr><tr><td>&quot;00019306-9d83-4334-b255-a44774…</td><td>174</td><td>367</td><td>219</td><td>378</td><td>900</td><td>&quot;Savannah_Sparrow&quot;</td><td>null</td><td>&quot;0900/000193069d834334b255a4477…</td><td>&quot;Ryan_Schain&quot;</td><td>0</td></tr><tr><td>&quot;0001afd4-99a1-4a67-b940-d41941…</td><td>307</td><td>179</td><td>492</td><td>224</td><td>645</td><td>&quot;Eared_Grebe&quot;</td><td>&quot;Nonbreeding/juvenile&quot;</td><td>&quot;0645/0001afd499a14a67b940d4194…</td><td>&quot;Laura_Erickson&quot;</td><td>1</td></tr><tr><td>&quot;000332b8-997c-4540-9647-2f0a84…</td><td>395</td><td>139</td><td>262</td><td>390</td><td>929</td><td>&quot;Eastern_Phoebe&quot;</td><td>null</td><td>&quot;0929/000332b8997c454096472f0a8…</td><td>&quot;Dan_Irizarry&quot;</td><td>0</td></tr><tr><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td></tr><tr><td>&quot;fff86e8b-795f-400a-91e8-565bbb…</td><td>344</td><td>163</td><td>291</td><td>472</td><td>891</td><td>&quot;Canyon_Towhee&quot;</td><td>null</td><td>&quot;0891/fff86e8b795f400a91e8565bb…</td><td>&quot;Nancy_Landry&quot;</td><td>1</td></tr><tr><td>&quot;fff926d7-ccad-4788-839e-97af2d…</td><td>330</td><td>180</td><td>339</td><td>671</td><td>660</td><td>&quot;Rough-legged_Hawk&quot;</td><td>&quot;Light_morph&quot;</td><td>&quot;0660/fff926d7ccad4788839e97af2…</td><td>&quot;Ruth_Sullivan&quot;</td><td>1</td></tr><tr><td>&quot;fffa33ef-a765-408d-8d66-6efc7f…</td><td>184</td><td>94</td><td>258</td><td>612</td><td>492</td><td>&quot;Swallow-tailed_Kite&quot;</td><td>null</td><td>&quot;0492/fffa33efa765408d8d666efc7…</td><td>&quot;Gerry_Dewaghe&quot;</td><td>1</td></tr><tr><td>&quot;ffff0d87-bc84-4ef2-a47e-a4bfa4…</td><td>102</td><td>210</td><td>461</td><td>688</td><td>372</td><td>&quot;Broad-billed_Hummingbird&quot;</td><td>&quot;Adult_Male&quot;</td><td>&quot;0372/ffff0d87bc844ef2a47ea4bfa…</td><td>&quot;Muriel_Neddermeyer&quot;</td><td>0</td></tr><tr><td>&quot;fffff3a5-2a75-47d0-887f-03871e…</td><td>281</td><td>164</td><td>524</td><td>279</td><td>880</td><td>&quot;Black-throated_Gray_Warbler&quot;</td><td>null</td><td>&quot;0880/fffff3a52a7547d0887f03871…</td><td>&quot;Dominic_Sherony&quot;</td><td>0</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\nAnd then let's explore a number of characteristics:\n\n::: {#f90ff94d .cell execution_count=12}\n``` {.python .cell-code}\nprint(metadata.columns)\nprint(metadata.row(0))\nprint(metadata.row(-1))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n['UUID', 'bb_x', 'bb_y', 'bb_width', 'bb_height', 'class_id', 'species', 'subcategory', 'path', 'photographer', 'is_training_img']\n('0000139e-21dc-4d0c-bfe1-4cae3c85c829', 83, 59, 128, 228, 817, 'Oak_Titmouse', None, '0817/0000139e21dc4d0cbfe14cae3c85c829.jpg', 'Ruth_Cantwell', 0)\n('fffff3a5-2a75-47d0-887f-03871e3f9a37', 281, 164, 524, 279, 880, 'Black-throated_Gray_Warbler', None, '0880/fffff3a52a7547d0887f03871e3f9a37.jpg', 'Dominic_Sherony', 0)\n```\n:::\n:::\n\n\n```{.python}\nprint(metadata.head())\n```\n\n::: {#db24be91 .cell execution_count=13}\n\n::: {.cell-output .cell-output-display execution_count=13}\n```{=html}\n<div><style>\n.dataframe > thead > tr,\n.dataframe > tbody > tr {\n  text-align: right;\n  white-space: pre-wrap;\n}\n</style>\n<small>shape: (5, 11)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>UUID</th><th>bb_x</th><th>bb_y</th><th>bb_width</th><th>bb_height</th><th>class_id</th><th>species</th><th>subcategory</th><th>path</th><th>photographer</th><th>is_training_img</th></tr><tr><td>str</td><td>i64</td><td>i64</td><td>i64</td><td>i64</td><td>i64</td><td>str</td><td>str</td><td>str</td><td>str</td><td>i64</td></tr></thead><tbody><tr><td>&quot;0000139e-21dc-4d0c-bfe1-4cae3c…</td><td>83</td><td>59</td><td>128</td><td>228</td><td>817</td><td>&quot;Oak_Titmouse&quot;</td><td>null</td><td>&quot;0817/0000139e21dc4d0cbfe14cae3…</td><td>&quot;Ruth_Cantwell&quot;</td><td>0</td></tr><tr><td>&quot;0000d9fc-4e02-4c06-a0af-a55cfb…</td><td>328</td><td>88</td><td>163</td><td>298</td><td>860</td><td>&quot;Ovenbird&quot;</td><td>null</td><td>&quot;0860/0000d9fc4e024c06a0afa55cf…</td><td>&quot;Christopher_L._Wood_Chris_Wood&quot;</td><td>0</td></tr><tr><td>&quot;00019306-9d83-4334-b255-a44774…</td><td>174</td><td>367</td><td>219</td><td>378</td><td>900</td><td>&quot;Savannah_Sparrow&quot;</td><td>null</td><td>&quot;0900/000193069d834334b255a4477…</td><td>&quot;Ryan_Schain&quot;</td><td>0</td></tr><tr><td>&quot;0001afd4-99a1-4a67-b940-d41941…</td><td>307</td><td>179</td><td>492</td><td>224</td><td>645</td><td>&quot;Eared_Grebe&quot;</td><td>&quot;Nonbreeding/juvenile&quot;</td><td>&quot;0645/0001afd499a14a67b940d4194…</td><td>&quot;Laura_Erickson&quot;</td><td>1</td></tr><tr><td>&quot;000332b8-997c-4540-9647-2f0a84…</td><td>395</td><td>139</td><td>262</td><td>390</td><td>929</td><td>&quot;Eastern_Phoebe&quot;</td><td>null</td><td>&quot;0929/000332b8997c454096472f0a8…</td><td>&quot;Dan_Irizarry&quot;</td><td>0</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n```{.python}\nprint(metadata.tail())\n```\n\n::: {#20d3b399 .cell execution_count=14}\n\n::: {.cell-output .cell-output-display execution_count=14}\n```{=html}\n<div><style>\n.dataframe > thead > tr,\n.dataframe > tbody > tr {\n  text-align: right;\n  white-space: pre-wrap;\n}\n</style>\n<small>shape: (5, 11)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>UUID</th><th>bb_x</th><th>bb_y</th><th>bb_width</th><th>bb_height</th><th>class_id</th><th>species</th><th>subcategory</th><th>path</th><th>photographer</th><th>is_training_img</th></tr><tr><td>str</td><td>i64</td><td>i64</td><td>i64</td><td>i64</td><td>i64</td><td>str</td><td>str</td><td>str</td><td>str</td><td>i64</td></tr></thead><tbody><tr><td>&quot;fff86e8b-795f-400a-91e8-565bbb…</td><td>344</td><td>163</td><td>291</td><td>472</td><td>891</td><td>&quot;Canyon_Towhee&quot;</td><td>null</td><td>&quot;0891/fff86e8b795f400a91e8565bb…</td><td>&quot;Nancy_Landry&quot;</td><td>1</td></tr><tr><td>&quot;fff926d7-ccad-4788-839e-97af2d…</td><td>330</td><td>180</td><td>339</td><td>671</td><td>660</td><td>&quot;Rough-legged_Hawk&quot;</td><td>&quot;Light_morph&quot;</td><td>&quot;0660/fff926d7ccad4788839e97af2…</td><td>&quot;Ruth_Sullivan&quot;</td><td>1</td></tr><tr><td>&quot;fffa33ef-a765-408d-8d66-6efc7f…</td><td>184</td><td>94</td><td>258</td><td>612</td><td>492</td><td>&quot;Swallow-tailed_Kite&quot;</td><td>null</td><td>&quot;0492/fffa33efa765408d8d666efc7…</td><td>&quot;Gerry_Dewaghe&quot;</td><td>1</td></tr><tr><td>&quot;ffff0d87-bc84-4ef2-a47e-a4bfa4…</td><td>102</td><td>210</td><td>461</td><td>688</td><td>372</td><td>&quot;Broad-billed_Hummingbird&quot;</td><td>&quot;Adult_Male&quot;</td><td>&quot;0372/ffff0d87bc844ef2a47ea4bfa…</td><td>&quot;Muriel_Neddermeyer&quot;</td><td>0</td></tr><tr><td>&quot;fffff3a5-2a75-47d0-887f-03871e…</td><td>281</td><td>164</td><td>524</td><td>279</td><td>880</td><td>&quot;Black-throated_Gray_Warbler&quot;</td><td>null</td><td>&quot;0880/fffff3a52a7547d0887f03871…</td><td>&quot;Dominic_Sherony&quot;</td><td>0</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n```{.python}\nimport random\n\nrandom.seed(123)\nprint(metadata.sample())\n```\n\n::: {#1629edca .cell execution_count=15}\n\n::: {.cell-output .cell-output-display execution_count=15}\n```{=html}\n<div><style>\n.dataframe > thead > tr,\n.dataframe > tbody > tr {\n  text-align: right;\n  white-space: pre-wrap;\n}\n</style>\n<small>shape: (1, 11)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>UUID</th><th>bb_x</th><th>bb_y</th><th>bb_width</th><th>bb_height</th><th>class_id</th><th>species</th><th>subcategory</th><th>path</th><th>photographer</th><th>is_training_img</th></tr><tr><td>str</td><td>i64</td><td>i64</td><td>i64</td><td>i64</td><td>i64</td><td>str</td><td>str</td><td>str</td><td>str</td><td>i64</td></tr></thead><tbody><tr><td>&quot;b20cc001-80f0-4280-9cd5-b9b569…</td><td>382</td><td>236</td><td>308</td><td>485</td><td>780</td><td>&quot;Red-winged_Blackbird&quot;</td><td>&quot;Male&quot;</td><td>&quot;0780/b20cc00180f042809cd5b9b56…</td><td>&quot;Alex_Burdo&quot;</td><td>0</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n::: {#652c6f67 .cell execution_count=16}\n``` {.python .cell-code}\nprint(metadata.schema)\nprint(metadata.shape)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSchema({'UUID': String, 'bb_x': Int64, 'bb_y': Int64, 'bb_width': Int64, 'bb_height': Int64, 'class_id': Int64, 'species': String, 'subcategory': String, 'path': String, 'photographer': String, 'is_training_img': Int64})\n(48562, 11)\n```\n:::\n:::\n\n\n::: {#17232fcc .cell execution_count=17}\n``` {.python .cell-code}\nprint(metadata.glimpse())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 48562\nColumns: 11\n$ UUID            <str> '0000139e-21dc-4d0c-bfe1-4cae3c85c829', '0000d9fc-4e02-4c06-a0af-a55cfb16b12b', '00019306-9d83-4334-b255-a447742edce3', '0001afd4-99a1-4a67-b940-d419413e23b3', '000332b8-997c-4540-9647-2f0a8495aecf', '000343bd-5215-49ba-ab9c-7c97a70ac1a5', '0004ff8d-0cc8-47ee-94ba-43352a8b9eb4', '0007181f-a727-4481-ad89-591200c61b9d', '00071e20-8156-4bd8-b5ca-6445c2560ee5', '0007acfc-c0e6-4393-9ab6-02215a82ef63'\n$ bb_x            <i64> 83, 328, 174, 307, 395, 120, 417, 47, 260, 193\n$ bb_y            <i64> 59, 88, 367, 179, 139, 210, 109, 194, 146, 291\n$ bb_width        <i64> 128, 163, 219, 492, 262, 587, 221, 819, 578, 526\n$ bb_height       <i64> 228, 298, 378, 224, 390, 357, 467, 573, 516, 145\n$ class_id        <i64> 817, 860, 900, 645, 929, 652, 951, 900, 988, 400\n$ species         <str> 'Oak_Titmouse', 'Ovenbird', 'Savannah_Sparrow', 'Eared_Grebe', 'Eastern_Phoebe', 'Yellow-crowned_Night-Heron', 'Florida_Scrub-Jay', 'Savannah_Sparrow', 'Yellow-headed_Blackbird', 'Herring_Gull'\n$ subcategory     <str> null, null, null, 'Nonbreeding/juvenile', null, 'Immature', null, null, 'Female/Immature_Male', 'Adult'\n$ path            <str> '0817/0000139e21dc4d0cbfe14cae3c85c829.jpg', '0860/0000d9fc4e024c06a0afa55cfb16b12b.jpg', '0900/000193069d834334b255a447742edce3.jpg', '0645/0001afd499a14a67b940d419413e23b3.jpg', '0929/000332b8997c454096472f0a8495aecf.jpg', '0652/000343bd521549baab9c7c97a70ac1a5.jpg', '0951/0004ff8d0cc847ee94ba43352a8b9eb4.jpg', '0900/0007181fa7274481ad89591200c61b9d.jpg', '0988/00071e2081564bd8b5ca6445c2560ee5.jpg', '0400/0007acfcc0e643939ab602215a82ef63.jpg'\n$ photographer    <str> 'Ruth_Cantwell', 'Christopher_L._Wood_Chris_Wood', 'Ryan_Schain', 'Laura_Erickson', 'Dan_Irizarry', 'Ken_Schneider', 'Velma_Knowles', 'Matt_Tillett', 'Terry_Gray', 'Cory_Gregory'\n$ is_training_img <i64> 0, 0, 0, 1, 0, 0, 0, 1, 1, 0\n\nNone\n```\n:::\n:::\n\n\n```{.python}\nprint(metadata.describe())\n```\n\n::: {#b4ba0593 .cell execution_count=18}\n\n::: {.cell-output .cell-output-display execution_count=18}\n```{=html}\n<div><style>\n.dataframe > thead > tr,\n.dataframe > tbody > tr {\n  text-align: right;\n  white-space: pre-wrap;\n}\n</style>\n<small>shape: (9, 12)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>statistic</th><th>UUID</th><th>bb_x</th><th>bb_y</th><th>bb_width</th><th>bb_height</th><th>class_id</th><th>species</th><th>subcategory</th><th>path</th><th>photographer</th><th>is_training_img</th></tr><tr><td>str</td><td>str</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td><td>str</td><td>str</td><td>str</td><td>str</td><td>f64</td></tr></thead><tbody><tr><td>&quot;count&quot;</td><td>&quot;48562&quot;</td><td>48562.0</td><td>48562.0</td><td>48562.0</td><td>48562.0</td><td>48562.0</td><td>&quot;48562&quot;</td><td>&quot;23589&quot;</td><td>&quot;48562&quot;</td><td>&quot;48562&quot;</td><td>48562.0</td></tr><tr><td>&quot;null_count&quot;</td><td>&quot;0&quot;</td><td>0.0</td><td>0.0</td><td>0.0</td><td>0.0</td><td>0.0</td><td>&quot;0&quot;</td><td>&quot;24973&quot;</td><td>&quot;0&quot;</td><td>&quot;0&quot;</td><td>0.0</td></tr><tr><td>&quot;mean&quot;</td><td>null</td><td>221.68531</td><td>158.534121</td><td>453.897286</td><td>406.37101</td><td>687.918269</td><td>null</td><td>null</td><td>null</td><td>null</td><td>0.492752</td></tr><tr><td>&quot;std&quot;</td><td>null</td><td>133.054864</td><td>80.976264</td><td>187.767897</td><td>168.061559</td><td>214.235138</td><td>null</td><td>null</td><td>null</td><td>null</td><td>0.499953</td></tr><tr><td>&quot;min&quot;</td><td>&quot;0000139e-21dc-4d0c-bfe1-4cae3c…</td><td>0.0</td><td>0.0</td><td>30.0</td><td>35.0</td><td>295.0</td><td>&quot;Abert&#x27;s_Towhee&quot;</td><td>&quot;Adult&quot;</td><td>&quot;0295/01f53d6bf5e449438d2bb79e0…</td><td>&quot;A._Walton&quot;</td><td>0.0</td></tr><tr><td>&quot;25%&quot;</td><td>null</td><td>115.0</td><td>99.0</td><td>309.0</td><td>282.0</td><td>502.0</td><td>null</td><td>null</td><td>null</td><td>null</td><td>0.0</td></tr><tr><td>&quot;50%&quot;</td><td>null</td><td>205.0</td><td>149.0</td><td>434.0</td><td>387.0</td><td>750.0</td><td>null</td><td>null</td><td>null</td><td>null</td><td>0.0</td></tr><tr><td>&quot;75%&quot;</td><td>null</td><td>315.0</td><td>208.0</td><td>581.0</td><td>509.0</td><td>877.0</td><td>null</td><td>null</td><td>null</td><td>null</td><td>1.0</td></tr><tr><td>&quot;max&quot;</td><td>&quot;fffff3a5-2a75-47d0-887f-03871e…</td><td>837.0</td><td>799.0</td><td>1024.0</td><td>1024.0</td><td>1010.0</td><td>&quot;Yellow_Warbler&quot;</td><td>&quot;Yellow-shafted&quot;</td><td>&quot;1010/ff4192ee5a164de684149d926…</td><td>&quot;www.burlybird.com&quot;</td><td>1.0</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n## Learn about the data\n\nNow that we have the metadata organized, let's get to know our data:\n\n::: {#f66e2b3c .cell execution_count=19}\n``` {.python .cell-code}\nprint(f'There are {len(metadata)} images in the dataset.')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nThere are 48562 images in the dataset.\n```\n:::\n:::\n\n\n::: {#6fd3b481 .cell execution_count=20}\n``` {.python .cell-code}\nmetadata_train = metadata.filter(pl.col('is_training_img') == 1)\nprint(f\"\"\"\nThere are:\n- {len(metadata_train)} images in the training set,\n- {len(metadata) - len(metadata_train)} in the validation set.\n\"\"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nThere are:\n- 23929 images in the training set,\n- 24633 in the validation set.\n\n```\n:::\n:::\n\n\n::: {#21526af2 .cell execution_count=21}\n``` {.python .cell-code}\nclass_id = metadata.unique(pl.col('class_id'))\nspecies = metadata.unique(pl.col('species'))\nprint(f'There are {len(class_id)} different classes and {len(species)} different species in the dataset.')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nThere are 555 different classes and 405 different species in the dataset.\n```\n:::\n:::\n\n\n::: {#3f5236ba .cell execution_count=22}\n``` {.python .cell-code}\ntrain_class_id_group_length = metadata_train.group_by(pl.col('class_id')).len()\nprint(f\"\"\"\nThe number of images per class in the training set varies from {train_class_id_group_length.min().select(pl.col('len')).item()} to {train_class_id_group_length.max().select(pl.col('len')).item()},\nwith an average of {round(train_class_id_group_length.mean().select(pl.col('len')).item())} images per class.\n\"\"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nThe number of images per class in the training set varies from 4 to 60,\nwith an average of 43 images per class.\n\n```\n:::\n:::\n\n\n::: {#170c8343 .cell execution_count=23}\n``` {.python .cell-code}\ntrain_species_group_length = metadata_train.group_by(pl.col('species')).len()\nprint(f\"\"\"\nThe number of images per species in the training set varies from {train_species_group_length.min().select(pl.col('len')).item()} to {train_species_group_length.max().select(pl.col('len')).item()},\nwith an average of {round(train_species_group_length.mean().select(pl.col('len')).item())} images per species.\n\"\"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nThe number of images per species in the training set varies from 6 to 221,\nwith an average of 59 images per species.\n\n```\n:::\n:::\n\n\n::: {#1956dcb8 .cell execution_count=24}\n``` {.python .cell-code}\nsubcategory = metadata.unique(pl.col(\"subcategory\"))\nexample_list = subcategory.get_column('subcategory').drop_nulls().head(10).to_list()\nexample_list_cleaned = [x.replace('_', ' ') for x in example_list]\nprint(f\"\"\"\nThere are {len(subcategory)} species subcategories, such as:\n- {'\\n- '.join(example_list_cleaned)}\n- etc.\n\"\"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nThere are 61 species subcategories, such as:\n- Dark morph\n- Male\n- Female/juvenile\n- Adult Subadult\n- Adult subadult\n- Adult male\n- Immature juvenile\n- Female/immature\n- Juvenile\n- Yellow-shafted\n- etc.\n\n```\n:::\n:::\n\n\n## Summary metadata\n\nLet's summarize the info we gathered from the metadata:\n\nCategory | Number\n--- | ---\nImages | 48_562\nTraining images | 23_929\nValidation images | 24_633\nClasses (species with their subcategories) | 555\nSpecies | 405\nAverage number of images per class in the training set | 43\nAverage number of images per species in the training set | 59\n\n## Save DataFrame to Parquet\n\nTo make it easier to retrieve information from the metadata later on, we can save the DataFrame to file.\n\n[Parquet](https://github.com/apache/parquet-format/) is an open-source, columnar, and extremely efficient binary file format for tabular data. Unlike in CSV or JSON files, the data is compressed, making it efficient for storage space. It is also excellent for query performance. Always prefer it over text-based formats.\n\n::: {#6dcba43f .cell execution_count=25}\n``` {.python .cell-code}\nmetadata.write_parquet('metadata.parquet')\n```\n:::\n\n\nOur metadata is ready. We can now start working with the pictures.\n\n",
    "supporting": [
      "jxai_metadata_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}