{
  "hash": "e845e56929a1ef088cd51eb99772e3f1",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: RIP pandas, welcome Polars\nfrontpic: img/polars_vs_pandas.png\nfrontpicwidth: 40%\nfrontpicmargintop: 30px\nfrontpicmarginbottom: 20px\nauthor: Marie-Hélène Burle\ndate: 2026-04-7\ndate-format: long\nexecute:\n  freeze: auto\n  cache: true\n  error: true\n  echo: true\nformat:\n  revealjs:\n    <!-- embed-resources: true -->\n    theme: [default, ../revealjspdpl.scss]\n    logo: /img/favicon_sfudrac.png\n    highlight-style: vim-dark\n    code-line-numbers: false\n    template-partials:\n      - ../title-slide.html\n    pointer:\n      color: \"#b5111b\"\n      pointerSize: 32\n    link-external-newwindow: true\n    footer: <a href=\"wb_polars2.qmd\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"rgb(32,118,193)\" class=\"bi bi-arrow-90deg-up\" viewBox=\"0 0 16 16\"><path fill-rule=\"evenodd\" d=\"M4.854 1.146a.5.5 0 0 0-.708 0l-4 4a.5.5 0 1 0 .708.708L4 2.707V12.5A2.5 2.5 0 0 0 6.5 15h8a.5.5 0 0 0 0-1h-8A1.5 1.5 0 0 1 5 12.5V2.707l3.146 3.147a.5.5 0 1 0 .708-.708l-4-4z\"/></svg>&nbsp;Back to webinar page</a>\n    auto-stretch: false\nrevealjs-plugins:\n  - pointer\n---\n\n## Goal of this webinar {.center}\n\nThere is a new and much better library for Python DataFrames\n\nThere are no downsides to using it, beside the effort to changing habits. For new users who don't have habits yet, there are no downsides\n\nYet, all Python intro courses still teach the old tool\n\n[My goal is to help shift the culture towards a wide adoption of Polars instead of pandas]{.emph}\n\n## A brief history of DataFrames {.center}\n\n```{dot}\n//| echo: false\n//| fig-height: 450px\n\nstrict graph {\n\nbgcolor=\"transparent\"\ngraph [fontname=\"Inconsolata, sans-serif\"]\nnode [fontname=\"Inconsolata, sans-serif\", fontsize=15]\n\ny1 [label=1990, shape=plaintext, group=g1, group=g1]\ny2 [label=2000, shape=plaintext, group=g1, group=g1]\ny3 [label=2008, shape=plaintext, group=g1]\ny4 [label=2020, shape=plaintext, group=g1]\n\nl1 [label=\"S language introduces concept of DataFrames\", href=\"https://en.wikipedia.org/wiki/S_(programming_language)\", shape=plaintext, group=g2]\nl2 [label=\"R supercedes S\", href=\"https://en.wikipedia.org/wiki/R_(programming_language)\", shape=plaintext, group=g2]\nl3 [label=\"DataFrames ported to Python with pandas\", href=\"https://github.com/pandas-dev/pandas\", shape=plaintext, group=g2, fontcolor=\"#e84c44\"]\nl4 [label=\"Better DataFrames library for Python: Polars\", href=\"https://github.com/pola-rs/polars\", shape=plaintext, group=g2, fontcolor=\"#69c9e6\"]\n\n{rank=same; y1 l1}\n\ny1 -- y2 -- y3 -- y4\nl1 -- l2 -- l3 -- l4 [style=invis]\n\n}\n```\n\n## Overview {.center}\n\n| | ![](img/logo_pandas_full.svg){width=\"55%\"} || ![](img/logo_polars_full.svg){width=\"50%\"} |\n|--|--|--|--|\n| Available for | Python || Rust, Python, R, NodeJS |\n| Written in | Cython || Rust |\n| Multithreading | Some operations || Yes (GIL released) |\n| Index | Rows are indexed || Integer positions are used |\n| Evaluation | Eager || Eager and lazy |\n| Query optimizer | No || Yes |\n| Out-of-core | No || Yes |\n| [SIMD](https://en.wikipedia.org/wiki/Single_instruction,_multiple_data) vectorization | Yes || Yes |\n| Data in memory | [NumPy](https://github.com/numpy/numpy) arrays || [Apache Arrow](https://github.com/apache/arrow) arrays |\n| Memory efficiency | Poor || Excellent |\n| Missing data handling | Inconsistent || Consistent; type stability |\n\n## Method {.center}\n\nThe performance of tools can only be evaluated on optimized code: poorly written pandas code is a lot slower than efficient pandas code\n\nI use the best pandas code from [Alex Razoumov pandas course](https://wgpages.netlify.app/python2/python-13-pandas/) in which he benchmarks various syntaxes\n\n# Example 1: a classic\n\n## FizzBuzz {.center}\n\n## {.center}\n\nLoad libraries:\n\n::: {#1824b679 .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\nimport numpy as np\nimport polars as pl\n```\n:::\n\n\nSet series length:\n\n::: {#8d627927 .cell execution_count=2}\n``` {.python .cell-code}\nlength = 10_000\n```\n:::\n\n\n## Code {.center}\n\n![](img/logo_pandas_full.svg){width=\"10%\" fig-align=\"right\"}\n\n::: {#db9cb388 .cell execution_count=3}\n``` {.python .cell-code}\ndf_pd = pd.DataFrame()\n\ndf_pd[\"Count\"] = np.arange(1, length+1)\n\ndf_pd[\"FizzBuzz\"] = df_pd[\"Count\"].astype(str)\n\ndf_pd.loc[df_pd[\"Count\"] % 3 == 0, \"FizzBuzz\"] = \"Fizz\"\ndf_pd.loc[df_pd[\"Count\"] % 5 == 0, \"FizzBuzz\"] = \"Buzz\"\ndf_pd.loc[df_pd[\"Count\"] % 15 == 0, \"FizzBuzz\"] = \"FizzBuzz\"\n```\n:::\n\n\n## {.center}\n\n::: {#a2bb60f4 .cell execution_count=4}\n``` {.python .cell-code}\ndf_pd\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Count</th>\n      <th>FizzBuzz</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>1</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>2</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>3</td>\n      <td>Fizz</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>4</td>\n      <td>4</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>5</td>\n      <td>Buzz</td>\n    </tr>\n    <tr>\n      <th>...</th>\n      <td>...</td>\n      <td>...</td>\n    </tr>\n    <tr>\n      <th>9995</th>\n      <td>9996</td>\n      <td>Fizz</td>\n    </tr>\n    <tr>\n      <th>9996</th>\n      <td>9997</td>\n      <td>9997</td>\n    </tr>\n    <tr>\n      <th>9997</th>\n      <td>9998</td>\n      <td>9998</td>\n    </tr>\n    <tr>\n      <th>9998</th>\n      <td>9999</td>\n      <td>Fizz</td>\n    </tr>\n    <tr>\n      <th>9999</th>\n      <td>10000</td>\n      <td>Buzz</td>\n    </tr>\n  </tbody>\n</table>\n<p>10000 rows × 2 columns</p>\n</div>\n```\n:::\n:::\n\n\n## Code {.center}\n\n![](img/logo_polars_full.svg){width=\"12%\" fig-align=\"right\"}\n\n::: {#e3260acd .cell execution_count=5}\n``` {.python .cell-code}\ndf_pl = pl.DataFrame({\"Count\": np.arange(1, length+1)})\n\ndf_pl.with_columns(pl.col(\"Count\").cast(pl.String).alias(\"FizzBuzz\"))\n\ndf_pl = df_pl.with_columns(\n    pl.when(pl.col(\"Count\") % 3 == 0).then(pl.lit(\"Fizz\"))\n    .when(pl.col(\"Count\") % 5 == 0).then(pl.lit(\"Buzz\"))\n    .when(pl.col(\"Count\") % 15 == 0).then(pl.lit(\"FizzBuzz\"))\n    .otherwise(pl.col(\"Count\")).alias(\"FizzBuzz\")\n)\n```\n:::\n\n\n## {.center}\n\n::: {#acb9cb2d .cell execution_count=6}\n``` {.python .cell-code}\ndf_pl\n```\n\n::: {.cell-output .cell-output-display execution_count=6}\n```{=html}\n<div><style>\n.dataframe > thead > tr,\n.dataframe > tbody > tr {\n  text-align: right;\n  white-space: pre-wrap;\n}\n</style>\n<small>shape: (10_000, 2)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>Count</th><th>FizzBuzz</th></tr><tr><td>i64</td><td>str</td></tr></thead><tbody><tr><td>1</td><td>&quot;1&quot;</td></tr><tr><td>2</td><td>&quot;2&quot;</td></tr><tr><td>3</td><td>&quot;Fizz&quot;</td></tr><tr><td>4</td><td>&quot;4&quot;</td></tr><tr><td>5</td><td>&quot;Buzz&quot;</td></tr><tr><td>&hellip;</td><td>&hellip;</td></tr><tr><td>9996</td><td>&quot;Fizz&quot;</td></tr><tr><td>9997</td><td>&quot;9997&quot;</td></tr><tr><td>9998</td><td>&quot;9998&quot;</td></tr><tr><td>9999</td><td>&quot;Fizz&quot;</td></tr><tr><td>10000</td><td>&quot;Buzz&quot;</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n## Code {.center}\n\n![](img/logo_polars_full.svg){width=\"12%\" fig-align=\"right\"}\n\n::: {#e772b3b2 .cell execution_count=7}\n``` {.python .cell-code}\ndf_pl_lazy = pl.LazyFrame({\"Count\": np.arange(1, length+1)})\n\ndf_pl_lazy.with_columns(pl.col(\"Count\").cast(pl.String).alias(\"FizzBuzz\"))\n\ndf_pl_lazy = df_pl_lazy.with_columns(\n    pl.when(pl.col(\"Count\") % 3 == 0).then(pl.lit(\"Fizz\"))\n    .when(pl.col(\"Count\") % 5 == 0).then(pl.lit(\"Buzz\"))\n    .when(pl.col(\"Count\") % 15 == 0).then(pl.lit(\"FizzBuzz\"))\n    .otherwise(pl.col(\"Count\")).alias(\"FizzBuzz\")\n)\n\ndf_pl_lazy_collected = df_pl_lazy.collect()\n```\n:::\n\n\n## {.center}\n\n::: {#ca5f0d67 .cell execution_count=8}\n``` {.python .cell-code}\ndf_pl_lazy_collected\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```{=html}\n<div><style>\n.dataframe > thead > tr,\n.dataframe > tbody > tr {\n  text-align: right;\n  white-space: pre-wrap;\n}\n</style>\n<small>shape: (10_000, 2)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>Count</th><th>FizzBuzz</th></tr><tr><td>i64</td><td>str</td></tr></thead><tbody><tr><td>1</td><td>&quot;1&quot;</td></tr><tr><td>2</td><td>&quot;2&quot;</td></tr><tr><td>3</td><td>&quot;Fizz&quot;</td></tr><tr><td>4</td><td>&quot;4&quot;</td></tr><tr><td>5</td><td>&quot;Buzz&quot;</td></tr><tr><td>&hellip;</td><td>&hellip;</td></tr><tr><td>9996</td><td>&quot;Fizz&quot;</td></tr><tr><td>9997</td><td>&quot;9997&quot;</td></tr><tr><td>9998</td><td>&quot;9998&quot;</td></tr><tr><td>9999</td><td>&quot;Fizz&quot;</td></tr><tr><td>10000</td><td>&quot;Buzz&quot;</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n## Timing {.center}\n\n![](img/logo_pandas_full.svg){width=\"10%\" fig-align=\"right\"}\n\n::: {#552de24d .cell execution_count=9}\n``` {.python .cell-code}\n%%timeit\n\ndf_pd = pd.DataFrame()\n\ndf_pd[\"Count\"] = np.arange(1, length+1)\n\ndf_pd[\"FizzBuzz\"] = df_pd[\"Count\"].astype(str)\n\ndf_pd.loc[df_pd[\"Count\"] % 3 == 0, \"FizzBuzz\"] = \"Fizz\"\ndf_pd.loc[df_pd[\"Count\"] % 5 == 0, \"FizzBuzz\"] = \"Buzz\"\ndf_pd.loc[df_pd[\"Count\"] % 15 == 0, \"FizzBuzz\"] = \"FizzBuzz\"\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n3.45 ms ± 171 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)\n```\n:::\n:::\n\n\n## Timing {.center}\n\n![](img/logo_polars_full.svg){width=\"12%\" fig-align=\"right\"}\n\n::: {#cea96202 .cell execution_count=10}\n``` {.python .cell-code}\n%%timeit\n\ndf_pl = pl.DataFrame({\"Count\": np.arange(1, length+1)})\n\ndf_pl.with_columns(pl.col(\"Count\").cast(pl.String).alias(\"FizzBuzz\"))\n\ndf_pl.with_columns(\n    pl.when(pl.col(\"Count\") % 3 == 0).then(pl.lit(\"Fizz\"))\n    .when(pl.col(\"Count\") % 5 == 0).then(pl.lit(\"Buzz\"))\n    .when(pl.col(\"Count\") % 15 == 0).then(pl.lit(\"FizzBuzz\"))\n    .otherwise(pl.col(\"Count\")).alias(\"FizzBuzz\")\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n657 μs ± 15.5 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)\n```\n:::\n:::\n\n\n## Timing {.center}\n\n![](img/logo_polars_full.svg){width=\"12%\" fig-align=\"right\"}\n\n::: {#091093cf .cell execution_count=11}\n``` {.python .cell-code}\n%%timeit\n\ndf_pl_lazy = pl.LazyFrame({\"Count\": np.arange(1, length+1)})\n\ndf_pl_lazy.with_columns(pl.col(\"Count\").cast(pl.String).alias(\"FizzBuzz\"))\n\ndf_pl_lazy = df_pl_lazy.with_columns(\n    pl.when(pl.col(\"Count\") % 3 == 0).then(pl.lit(\"Fizz\"))\n    .when(pl.col(\"Count\") % 5 == 0).then(pl.lit(\"Buzz\"))\n    .when(pl.col(\"Count\") % 15 == 0).then(pl.lit(\"FizzBuzz\"))\n    .otherwise(pl.col(\"Count\")).alias(\"FizzBuzz\")\n)\n\ndf_pl = df_pl_lazy.collect()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n464 μs ± 7.35 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)\n```\n:::\n:::\n\n\n## Speedup {.center}\n\nSpeedup with Polars DataFrame around 6 \\\nWith Polars LazyFrame around 8\n\nThese speedups highly depend on the types and sizes of the problems\n\nHow much faster Polars is does vary, what doesn't vary is that it is always much faster\n\n## Memory usage {.center}\n\n::::{.columns}\n\n:::{.column width=\"32%\"}\n\n**pandas**\n\n::: {#e844edf5 .cell execution_count=12}\n``` {.python .cell-code}\ndf_pd.memory_usage()\n```\n\n::: {.cell-output .cell-output-display execution_count=12}\n```\nIndex         132\nCount       80000\nFizzBuzz    80000\ndtype: int64\n```\n:::\n:::\n\n\n132 + 80,000 * 2 = \\\n160,132 bytes \\\n**≈ 160 KB**\n\n:::\n\n:::{.column width=\"2%\"}\n:::\n\n:::{.column width=\"32%\"}\n\n**Polars**\n\n::: {#6aa9c895 .cell execution_count=13}\n``` {.python .cell-code}\ndf_pl.estimated_size()\n```\n\n::: {.cell-output .cell-output-display execution_count=13}\n```\n119409\n```\n:::\n:::\n\n\n119,409 bytes \\\n**≈ 119 KB**\n\n160,132 / 119,409 ≈ 1.3 \\\nFootprint 1.3 times smaller\n\n:::\n\n:::{.column width=\"2%\"}\n:::\n\n:::{.column width=\"32%\"}\n\n**Polars lazy**\n\n<br>\nSame as Polars eager: \\\nif you collect the entire DataFrame as we did here, the lazy API does not reduce the memory footprint\n\n:::\n\n::::\n\n# Example 2: medium dataset\n\n## Data characteristics {.center}\n\nShape: 216,930 rows, 7 columns\n\n## Code {.center}\n\n![](img/logo_pandas_full.svg){width=\"10%\" fig-align=\"right\"}\n\n::: {#894549c8 .cell execution_count=14}\n``` {.python .cell-code}\ndf_pd = pd.read_csv(\n    \"https://raw.githubusercontent.com/razoumov/publish/master/jeopardy.csv\"\n)\n\ndf_pd_subset = df_pd.loc[df_pd[\"Category\"] == \"HISTORY\"]\n\ndf_pd_subset.shape\n```\n\n::: {.cell-output .cell-output-display execution_count=14}\n```\n(349, 7)\n```\n:::\n:::\n\n\n## Code {.center}\n\n![](img/logo_polars_full.svg){width=\"12%\" fig-align=\"right\"}\n\n::: {#19dba8d0 .cell execution_count=15}\n``` {.python .cell-code}\ndf_pl = pl.read_csv(\n    \"https://raw.githubusercontent.com/razoumov/publish/master/jeopardy.csv\"\n)\n\ndf_pl_subset = df_pl.filter(pl.col(\"Category\") == \"HISTORY\")\n\ndf_pl_subset.shape\n```\n\n::: {.cell-output .cell-output-display execution_count=15}\n```\n(349, 7)\n```\n:::\n:::\n\n\n## Code {.center}\n\n![](img/logo_polars_full.svg){width=\"12%\" fig-align=\"right\"}\n\n::: {#522a5317 .cell execution_count=16}\n``` {.python .cell-code}\ndf_pl_lazy = pl.scan_csv(\n    \"https://raw.githubusercontent.com/razoumov/publish/master/jeopardy.csv\"\n)\n\ndf_pl_lazy_subset_collected = df_pl_lazy.filter(\n    pl.col(\"Category\") == \"HISTORY\"\n).collect()\n\ndf_pl_lazy_subset_collected.shape\n```\n\n::: {.cell-output .cell-output-display execution_count=16}\n```\n(349, 7)\n```\n:::\n:::\n\n\n## Timing {.center}\n\n![](img/logo_pandas_full.svg){width=\"10%\" fig-align=\"right\"}\n\n::: {#4e78ca93 .cell execution_count=17}\n``` {.python .cell-code}\n%%timeit\n\ndf_pd = pd.read_csv(\n    \"https://raw.githubusercontent.com/razoumov/publish/master/jeopardy.csv\"\n)\n\ndf_pd.loc[df_pd[\"Category\"] == \"HISTORY\"].shape\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n1.18 s ± 20.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)\n```\n:::\n:::\n\n\n## Timing {.center}\n\n![](img/logo_polars_full.svg){width=\"12%\" fig-align=\"right\"}\n\n::: {#d71bc9b1 .cell execution_count=18}\n``` {.python .cell-code}\n%%timeit\n\ndf_pl = pl.read_csv(\n    \"https://raw.githubusercontent.com/razoumov/publish/master/jeopardy.csv\"\n)\n\ndf_pl.filter(pl.col(\"Category\") == \"HISTORY\").shape\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n802 ms ± 33 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)\n```\n:::\n:::\n\n\n## Timing {.center}\n\n![](img/logo_polars_full.svg){width=\"12%\" fig-align=\"right\"}\n\n::: {#901360db .cell execution_count=19}\n``` {.python .cell-code}\n%%timeit\n\ndf_pl_lazy = pl.scan_csv(\n    \"https://raw.githubusercontent.com/razoumov/publish/master/jeopardy.csv\"\n)\n\ndf_pl_lazy.filter(pl.col(\"Category\") == \"HISTORY\").collect().shape\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n66.3 ms ± 3.56 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)\n```\n:::\n:::\n\n\n## Speedup {.center}\n\nPolars here brings a speedup around 1.5\n\nPolars lazy ramps that up to a speedup of 17\n\n## Memory usage {.center}\n\n::::{.columns}\n\n:::{.column width=\"30%\"}\n\n::: {#ebb33239 .cell execution_count=20}\n``` {.python .cell-code}\ndf_pd.memory_usage()\n```\n\n::: {.cell-output .cell-output-display execution_count=20}\n```\nIndex              132\nShow Number    1735440\nAir Date       1735440\nRound          1735440\nCategory       1735440\nValue          1735440\nQuestion       1735440\nAnswer         1735440\ndtype: int64\n```\n:::\n:::\n\n\n132 + 1,735,440 * 7 = \\\n12,148,212 bytes \\\n**≈ 12 MB**\n\n:::\n\n:::{.column width=\"2%\"}\n:::\n\n:::{.column width=\"33%\"}\n\n::: {#ec62d456 .cell execution_count=21}\n``` {.python .cell-code}\ndf_pl.estimated_size()\n```\n\n::: {.cell-output .cell-output-display execution_count=21}\n```\n31606250\n```\n:::\n:::\n\n\n31,606,250 bytes \\\n**≈ 31 MB**\n\n31,606,250 / 12,148,212 ≈ 2.6 \\\nFootprint 2.6 times *bigger*\n\n:::\n\n:::{.column width=\"2%\"}\n:::\n\n:::{.column width=\"33%\"}\n\n::: {#70d8ce10 .cell execution_count=22}\n``` {.python .cell-code}\ndf_pl_lazy_subset_collected.estimated_size()\n```\n\n::: {.cell-output .cell-output-display execution_count=22}\n```\n48774\n```\n:::\n:::\n\n\n48,774 bytes \\\n**≈ 49 KB**\n\n12,148,212 / 48,774 ≈ 249 \\\nFootprint **249 times smaller**\n\nIf you only collect a subset of the data, the memory footprint drops dramatically\n\n:::\n\n::::\n\n# Example 3:<br>data too big to fit in memory\n\n## Data characteristics {.center}\n\n",
    "supporting": [
      "wb_polars2_slides_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}