---
title: Bayesian inference in JAX
author: Marie-Hélène Burle
---

:::{.def}

[Bayesian statistics](https://en.wikipedia.org/wiki/Bayesian_statistics) is more intuitive to the way we (humans) think about the world and easier to interpret than the traditional [frequentist approach](https://en.wikipedia.org/wiki/Frequentist_probability). Moreover, it allows for the incorporation of prior information and diverse data, it provides a measure of uncertainty, and it is extremely valuable in difficult situations with little data. The downside is that it is computationally complex and intensive. In addition, the best performing algorithms require burdensome calculations of derivatives. This explains its initial limitations.

With the advent of increasingly performant [probabilistic programming languages (PPLs)](https://en.wikipedia.org/wiki/Probabilistic_programming), algorithms, compilers, [automatic differentiation](https://en.wikipedia.org/wiki/Automatic_differentiation) engines, and computer hardware, Bayesian approaches are now fast growing in popularity in many fields.

[JAX](https://docs.jax.dev/en/latest/index.html) is a library for Python that makes use of the extremely performant [XLA compiler](https://en.wikipedia.org/wiki/Accelerated_Linear_Algebra), runs on accelerators (GPUs/TPUs), provides automatic differentiation, [just-in-time compilation](https://en.wikipedia.org/wiki/Just-in-time_compilation), batching, and parallelization. In short, it is a perfect tool for Bayesian statistics. Not surprisingly, many PPLs now use it as a backend and [Stan](https://mc-stan.org/) users (and [developers!](https://statmodeling.stat.columbia.edu/2024/09/25/stan-faster-than-jax-on-cpu/)) are turning to it.

In this webinar, I will give a brief and very high-level introduction to Bayesian inference and JAX, then talk about the various PPLs and samplers which use JAX.

:::

[Slides](wb_bayesian_slides.qmd){.btn .btn-outline-primary} [(Click and wait: this reveal.js presentation may take a little time to load.)]{.inlinenote}
<!-- <br><br> -->

<!-- {{< video https://www.youtube.com/embed/ >}} -->
