---
title: Accelerated array computing & AD with JAX
aliases:
  - /ai/wb_jax.html
author: Marie-Hélène Burle
---

:::{.def}

[JAX](https://jax.readthedocs.io/) is an open source Python library for high-performance array computing and flexible automatic differentiation.

High-performance computing is achieved by [asynchronous dispatch](https://en.wikipedia.org/wiki/Asynchrony_(computer_programming)), [just-in-time compilation](https://en.wikipedia.org/wiki/Just-in-time_compilation), the [XLA compiler for linear algebra](https://www.tensorflow.org/xla), and full compatibility with accelerators ([GPUs](https://en.wikipedia.org/wiki/Graphics_processing_unit) and [TPUs](https://en.wikipedia.org/wiki/Tensor_Processing_Unit)).

Automatic differentiation uses [Autograd](https://github.com/hips/autograd) and works with complex control flows (conditions, recursions), second and third-order derivatives, forward and reverse modes. This makes JAX ideal for machine learning and neural network libraries such as [Flax](https://flax.readthedocs.io/en/latest/) are built on it.

This webinar will give an overview of JAX's principles and functioning.

:::

[Slides](wb_jax_slides.qmd){.btn .btn-outline-primary} [(Click and wait: this reveal.js presentation may take a little time to load.)]{.inlinenote}
<br><br>

{{< video https://www.youtube.com/embed/tk3x9x0eqPU >}}

<br>
*[Slides content](wb_jax_content.qmd) for easier browsing.*

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "LearningResource",
  "name": "Accelerated array computing & AD with JAX",
  "description": "JAX is an open source Python library for high-performance array computing and flexible automatic differentiation.\n\nHigh-performance computing is achieved by asynchronous dispatch, just-in-time compilation, the XLA compiler for linear algebra, and full compatibility with accelerators (GPUs and TPUs).\n\nAutomatic differentiation uses Autograd and works with complex control flows (conditions, recursions), second and third-order derivatives, forward and reverse modes. This makes JAX ideal for machine learning and neural network libraries such as Flax are built on it.\n\nThis webinar will give an overview of JAX’s principles and functioning.",
  "url": "https://mint.westdri.ca/ai/jx/wb_jax",
  "learningResourceType": "slides, video",
  "inLanguage": "en",
  "license": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
  "provider": {
    "@type": "Organization",
    "name": "SFU Research Computing Group"
  },
  "keywords": "AI, deep learning, JAX, Python, automatic differentiation, GPU, TPU, accelerator",
  "author": {
    "@type": "Person",
    "name": "Marie-Hélène Burle"
  },
  "educationalLevel": "beginner"
}
</script>
