---
title: Communication to the research community
subtitle: An open-minded discussion
frontlogo: /img/logo_drac_bilingual_no_bg.svg
author: Marie-Hélène Burle
date: 2025-05-27
date-format: long
execute:
  freeze: auto
  cache: true
  error: true
  echo: true
format:
  revealjs:
    embed-resources: true
    theme: [default, ../revealjsdrac.scss]
    logo: /img/favicon_drac_no_bg.png
    highlight-style: monokai
    code-line-numbers: false
    template-partials:
      - ../title-slide.html
    pointer:
      color: "#b5111b"
      pointerSize: 32
    link-external-newwindow: true
    footer: <a href="2025_driconnect.html"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="rgb(134,110,26)" class="bi bi-arrow-90deg-up" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M4.854 1.146a.5.5 0 0 0-.708 0l-4 4a.5.5 0 1 0 .708.708L4 2.707V12.5A2.5 2.5 0 0 0 6.5 15h8a.5.5 0 0 0 0-1h-8A1.5 1.5 0 0 1 5 12.5V2.707l3.146 3.147a.5.5 0 1 0 .708-.708l-4-4z"/></svg>&nbsp;Back to talk page</a>
revealjs-plugins:
  - pointer
---

## Topics {.center}

### Alliance website

### Alliance newsletter

### Training emails

# Alliance website

## 2 buttons on the front page leading to 2 sub-websites {.center}

::::{.columns}

:::{.column width="50%"}

[Stakeholders, click here]{.btn}

:::

:::{.column width="3%"}
:::

:::{.column width="47%"}

[Researchers, click here]{.btn}

:::

::::

::::{.columns}

:::{.column width="50%"}

↪ Current site

:::

:::{.column width="3%"}
:::

:::{.column width="47%"}

↪ Site with practical info for researchers:

- Status of clusters
- Link to wiki
- How to open tickets
- Link to training platform
- Announcements of upcoming training

:::

::::

## 2 buttons on the front page leading to 2 sub-websites {.center}

<br>
My arguments:

It would make the information researchers need easy to find

2 distinct audiences with different expectations vis-à-vis the Alliance &nbsp;➡ &nbsp;2 sub-websites

## 2 buttons on the front page leading to 2 sub-websites {.center}

- Do you find this idea worthwhile?

- Are there reasons not to implement something along those lines?

- Who would be a good contact to pursue this idea?

- Could we make plans?

# Alliance newsletter

## 2 different newsletters for 2 different audiences {.center}

::::{.columns}

:::{.column width="50%"}

### Stakeholders' newsletter

Current content \
(minus recent additions about training)

:::

:::{.column width="3%"}
:::

:::{.column width="47%"}

### Researchers' newsletter

- Status of clusters
- Link to wiki
- How to open tickets
- Link to training platform
- Announcements of upcoming training

:::

::::

## 2 different newsletters for 2 different audiences {.center}

<br>
My argument: same thing!

Stake holders want to see that the Alliance is great, productive, and involved in transformative computing

Researchers want practical information that can be useful to them

## 2 different newsletters for 2 different audiences {.center}

- Do you find this idea worthwhile?

- Are there reasons not to implement something along those lines?

- Who would be a good contact to pursue this idea?

- Could we make plans?

# Training emails

## The problem {.center}

- Most researchers do not know about the services that we are offering

- We do not have ways to reach out to them to inform them

[Explora](https://explora.alliancecan.ca/) is here and will help a lot! 🥳

But it won't solve everything:

- Users will need to be informed and reminded that Explora exists

- Some users might prefer to get emails about upcoming training events

## Mailing list access {.center}

We teach and help all Canadian academic researchers—not just Alliance clusters users

They are however our main target audience

Being allowed to email CCDB users to inform them of our services (with option to opt-out) would be a great solution

## Ethics {.center}

Responsible management is of course paramount and we would:

- strictly respect opt-out requests
- store data securely
- respect privacy
- abide by anti-spamming laws

## Alternative solution {.center}

An alternative solution would be for an Alliance personnel to send emails on our behalf to advertise our events

This seems impractical and add to the work load of the Alliance but remains an option

## Thoughts and discussion {.center}

Are the concerns around allowing us to use CCDB emails about:

- privacy?
- data safety?
- spamming laws?
- other?

- Is there anything we could do to alleviate these concerns?

- Who would be a good contact to pursue this conversation?

# Thank you for joining me in this discussion 😊
