---
title: Teaching programming with LLMs
subtitle: Reflections on a first experiment
author: Marie-Hélène Burle
---

*Presented at the HSS National Team Meeting in December 2025.*

:::{.def}

Over the past five years, an instructor from [ACENET](https://ace-net.ca/) and I have been teaching a week-long course called *"Coding fundamentals for humanists"* at the [digital humanities summer institute (DHSI)](https://dhsi.org/). The course is an introduction to coding concepts using Python as an example to humanities professors, deans, graduate students, and librarians with no programming experience. The goal is to demystify the topic and remove any apprehension at the idea of coding as well as to provide concrete applications useful in the field of social sciences.

In 2025, I decided to do things very differently and teach my section of the course using [large language models (LLMs)](https://en.wikipedia.org/wiki/Large_language_model).

In this talk, I am presenting my motivation for doing so, how I went about it, what worked and what didn't, and what I learnt in the process.

:::

[Slides](2025_teaching_with_llm_slides.qmd){.btn .btn-outline-primary} [(Click and wait: this reveal.js presentation may take a little time to load.)]{.inlinenote}

*[Slides content](2025_teaching_with_llm_content.qmd) for easier browsing.*
