---
title: The instruments for advanced research computing are here, but are researchers ready?
subtitle: <a href=https://driconnect.alliancecan.ca/>Digital Research Infrastructure Connect, Vancouver 2023</a>
author: Marie-Hélène Burle
---

:::{.def}
The current times are exciting: we are witnessing a growth of computing power while the open source community is vigorously building impressive machine learning and scientific programming tools.

This boom of hardware and software assets cannot however translate into research if graduate students aren't able to take advantage of it. Curricula often lack training pertinent to the use of such resources. Worse yet, in many fields faculties and PIs don't have the necessary background to help their students with high-performance programming. The training team at Simon Fraser University Research Computing Group aims to fill this gap in the West on behalf of the Alliance and all Western Canadian universities.

This talk will present an overview of the training we provide, from introductory skill sets for researchers new to ARC and HPC to advanced topics in parallel programming.
:::

[Slides](2023_driconnect_slides.qmd){.btn .btn-outline-primary}
<br><br>

{{< video https://www.youtube.com/embed/rNRQXN8bS-w >}}
