{
  "hash": "b91af77551bae1425213be2d97e1f83b",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: Comparison with pandas\nauthor: Marie-Hélène Burle\nbibliography: python.bib\ncsl: ../diabetologia.csl\n---\n\n:::{.def}\n\nAs pandas was the only DataFrame library for Python for a long time, many Python users are familiar with it and a comparison with Polars might be useful.\n\n:::\n\n## Overview\n\n| | pandas | Polars |\n|--|--|--|\n| Available for | Python | Rust, Python, R, NodeJS |\n| Written in | Cython | Rust |\n| Multithreading | Some operations | Yes (GIL released) |\n| Index | Rows are indexed | Integer positions are used |\n| Evaluation | Eager | Eager and lazy |\n| Query optimizer | No | Yes |\n| Out-of-core | No | Yes |\n| [SIMD](https://en.wikipedia.org/wiki/Single_instruction,_multiple_data) vectorization | Yes | Yes |\n| Data in memory | With [NumPy](https://github.com/numpy/numpy) arrays | With [Apache Arrow](https://github.com/apache/arrow) arrays |\n| Memory efficiency | Poor | Excellent |\n| Handling of missing data | Inconsistent | Consistent, promotes type stability |\n\n## Missing data\n\n::::{.columns}\n\n:::{.column width=\"52%\"}\n\n![](img/logo_pandas_full.svg){width=\"25%\"}\n\nFor historical reasons, depending on dtype, missing values are one of:\n\n- `NaN` (`numpy.nan`, dtype float),\n- `None`,\n- `NaT` (Not-a-Time, dtype datetime),\n- `pandas.NA` (nullable scalar).\n\nThis leads to inconsistent behaviour and unexpected dtype changes.\n\nThere has been an [ongoing open issue since 2020](https://github.com/pandas-dev/pandas/issues/32265).\n\n:::\n\n:::{.column width=\"2%\"}\n:::\n\n:::{.column width=\"46%\"}\n\n<br>![](img/logo_polars_full.svg){width=\"30%\"}\n\nOne single missing value: `null`.\n\nSimple and consistent behaviour across all data types and better performance.\n\n`NaN` exists and is a float. It is **not** missing data, but the result of mathematical operations that don't return numbers.\n\n[Here](https://www.dontusethiscode.com/blog/2025-01-22_null_vs_nan_applied.html) is a blog that goes into this in details.\n\n:::\n\n::::\n\n## Group by\n\n[Here](https://labs.quansight.org/blog/dataframe-group-by) is a great blog post by Marco Gorelli comparing the ease of use of passing expressions to groups in Polars compared to pandas. I am using his code here and doing some timing on it to look at efficiency.\n\n### Create DataFrames\n\nImport libraries:\n\n::: {#b0f30d4e .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\nimport polars as pl\n```\n:::\n\n\n::::{.columns}\n\n:::{.column width=\"49%\"}\n\nThe pandas DataFrame:\n\n::: {#d6b24d81 .cell execution_count=2}\n``` {.python .cell-code}\ndf_pd = pd.DataFrame(\n    {\n        \"id\": [1, 1, 1, 2, 2, 2],\n        \"sales\": [4, 1, 2, 7, 6, 7],\n        \"views\": [3, 1, 2, 8, 6, 7]\n    }\n)\n```\n:::\n\n\n:::\n\n:::{.column width=\"2%\"}\n:::\n\n:::{.column width=\"49%\"}\n\nThe Polars equivalent:\n\n::: {#e5079670 .cell execution_count=3}\n``` {.python .cell-code}\ndf_pl = pl.DataFrame(\n    {\n        \"id\": [1, 1, 1, 2, 2, 2],\n        \"sales\": [4, 1, 2, 7, 6, 7],\n        \"views\": [3, 1, 2, 8, 6, 7]\n    }\n)\n```\n:::\n\n\n:::\n\n::::\n\n::::{.columns}\n\n:::{.column width=\"49%\"}\n\nThe pandas DataFrame:\n\n::: {#8cb726d4 .cell execution_count=4}\n``` {.python .cell-code}\ndf_pd\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>id</th>\n      <th>sales</th>\n      <th>views</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>1</td>\n      <td>4</td>\n      <td>3</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>1</td>\n      <td>1</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>1</td>\n      <td>2</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>2</td>\n      <td>7</td>\n      <td>8</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>2</td>\n      <td>6</td>\n      <td>6</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>2</td>\n      <td>7</td>\n      <td>7</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n:::\n\n:::{.column width=\"2%\"}\n:::\n\n:::{.column width=\"49%\"}\n\nThe Polars equivalent:\n\n::: {#86cf150f .cell execution_count=5}\n``` {.python .cell-code}\ndf_pl\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```{=html}\n<div><style>\n.dataframe > thead > tr,\n.dataframe > tbody > tr {\n  text-align: right;\n  white-space: pre-wrap;\n}\n</style>\n<small>shape: (6, 3)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>id</th><th>sales</th><th>views</th></tr><tr><td>i64</td><td>i64</td><td>i64</td></tr></thead><tbody><tr><td>1</td><td>4</td><td>3</td></tr><tr><td>1</td><td>1</td><td>1</td></tr><tr><td>1</td><td>2</td><td>2</td></tr><tr><td>2</td><td>7</td><td>8</td></tr><tr><td>2</td><td>6</td><td>6</td></tr><tr><td>2</td><td>7</td><td>7</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n:::\n\n::::\n\n### Marco Gorelli's example\n\n> Find the maximum value of `views`, where `sales` is greater than its mean, per `id`.\n\n### Solutions in pandas\n\nThe straightforward method most people will use:\n\n::: {#fd72f482 .cell execution_count=6}\n``` {.python .cell-code}\ndf_pd.groupby('id').apply(\n    lambda df_pd: df_pd[df_pd['sales'] > df_pd['sales'].mean()]['views'].max(),\n    include_groups=False\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=6}\n```\nid\n1    3\n2    8\ndtype: int64\n```\n:::\n:::\n\n\nAnother option, but it requires 2 `groupby` expressions:\n\n::: {#c558f9bc .cell execution_count=7}\n``` {.python .cell-code}\ndf_pd[\n    df_pd['sales'] > df_pd.groupby('id')['sales'].transform('mean')\n].groupby('id')['views'].max()\n```\n\n::: {.cell-output .cell-output-display execution_count=7}\n```\nid\n1    3\n2    8\nName: views, dtype: int64\n```\n:::\n:::\n\n\nA solution people are unlikely to come up with:\n\n::: {#c1131bc8 .cell execution_count=8}\n``` {.python .cell-code}\ngb = df_pd.groupby(\"id\")\nmask = df_pd[\"sales\"] > gb[\"sales\"].transform(\"mean\")\ndf_pd[\"result\"] = df_pd[\"views\"].where(mask)\ngb[\"result\"].max()\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```\nid\n1    3.0\n2    8.0\nName: result, dtype: float64\n```\n:::\n:::\n\n\n### The solution in Polars\n\n::: {#de0ec490 .cell execution_count=9}\n``` {.python .cell-code}\ndf_pl.group_by('id').agg(\n    pl.col('views').filter(pl.col('sales') > pl.mean('sales')).max()\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=9}\n```{=html}\n<div><style>\n.dataframe > thead > tr,\n.dataframe > tbody > tr {\n  text-align: right;\n  white-space: pre-wrap;\n}\n</style>\n<small>shape: (2, 2)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>id</th><th>views</th></tr><tr><td>i64</td><td>i64</td></tr></thead><tbody><tr><td>1</td><td>3</td></tr><tr><td>2</td><td>8</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\nMuch simpler ...\n\n### Timing of pandas solutions\n\n```{.python}\n%%timeit\n\ndf_pd.groupby('id').apply(\n    lambda df_pd: df_pd[df_pd['sales'] > df_pd['sales'].mean()]['views'].max(),\n    include_groups=False\n)\n```\n\n```\n1.04 ms ± 1.33 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)\n```\n\nThe solution most people are likely to use is by far the slowest.\n\n```{.python}\n%%timeit\n\ndf_pd[\n    df_pd['sales'] > df_pd.groupby('id')['sales'].transform('mean')\n].groupby('id')['views'].max()\n```\n\n```\n678 μs ± 4.04 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)\n```\n\nThe best solution uses 2 `groupby` expressions.\n\n```{.python}\n%%timeit\n\ngb = df_pd.groupby(\"id\")\nmask = df_pd[\"sales\"] > gb[\"sales\"].transform(\"mean\")\ndf_pd[\"result\"] = df_pd[\"views\"].where(mask)\ngb[\"result\"].max()\n```\n\n```\n711 μs ± 952 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)\n```\n\nThis is almost as fast as the best solution.\n\n### Timing of the Polars solution\n\n```{.python}\n%%timeit\n\ndf_pl.group_by('id').agg(\n    pl.col('views').filter(pl.col('sales') > pl.mean('sales')).max()\n)\n```\n\n```\n110 μs ± 3.6 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)\n```\n\nPolars is more straightforward and much faster.\n\n### Conclusion\n\nSpeedup of Polars compared to the best pandas method: **6**. \\\nSpeedup compared to the method most people are likely to use: **9**.\n\nTo pass expressions to groups, Polars has a more straightforward and efficient syntax.\n\n## General performance comparisons\n\n:::{.note}\n\nThe performance of tools can only be evaluated on optimized code: poorly written pandas code is a lot slower than efficient pandas code.\n\nTo ensure fairness towards pandas, I use the best pandas code from [Alex Razoumov pandas course](https://wgpages.netlify.app/python2/python-13-pandas/) in which he benchmarks various syntaxes.\n\n:::\n\n### Example 1: FizzBuzz\n\n[FizzBuzz](https://en.wikipedia.org/wiki/Fizz_buzz#Programming) is a programming exercise based on a children game which consists of counting to `n`, replacing:\n\n- any number divisible by `3` with `Fizz`,\n- any number divisible by `5` with `Buzz`,\n- any number divisible by both `3` and `5` with `FizzBuzz`.\n\nIn his pandas course, Alex compares multiple methods and shows that [the best method uses masks](https://wgpages.netlify.app/python2/python-13-pandas/#three-solutions-to-a-classification-problem). Let's see how Polars fares in comparison to pandas' best method.\n\nFirst, let's load the packages we need and set the length of the series:\n\n::: {#948e2f56 .cell execution_count=10}\n``` {.python .cell-code}\nimport pandas as pd\nimport numpy as np\nimport polars as pl\nn = 10_000\n```\n:::\n\n\nAnd let's make sure that the code works.\n\nWith pandas:\n\n::: {#339ffdae .cell execution_count=11}\n``` {.python .cell-code}\ndf_pd = pd.DataFrame()\ndf_pd[\"Count\"] = np.arange(1, n+1)\ndf_pd[\"FizzBuzz\"] = df_pd[\"Count\"].astype(str)\ndf_pd.loc[df_pd[\"Count\"] % 3 == 0, \"FizzBuzz\"] = \"Fizz\"\ndf_pd.loc[df_pd[\"Count\"] % 5 == 0, \"FizzBuzz\"] = \"Buzz\"\ndf_pd.loc[df_pd[\"Count\"] % 15 == 0, \"FizzBuzz\"] = \"FizzBuzz\"\n\ndf_pd\n```\n\n::: {.cell-output .cell-output-display execution_count=11}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Count</th>\n      <th>FizzBuzz</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>1</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>2</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>3</td>\n      <td>Fizz</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>4</td>\n      <td>4</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>5</td>\n      <td>Buzz</td>\n    </tr>\n    <tr>\n      <th>...</th>\n      <td>...</td>\n      <td>...</td>\n    </tr>\n    <tr>\n      <th>9995</th>\n      <td>9996</td>\n      <td>Fizz</td>\n    </tr>\n    <tr>\n      <th>9996</th>\n      <td>9997</td>\n      <td>9997</td>\n    </tr>\n    <tr>\n      <th>9997</th>\n      <td>9998</td>\n      <td>9998</td>\n    </tr>\n    <tr>\n      <th>9998</th>\n      <td>9999</td>\n      <td>Fizz</td>\n    </tr>\n    <tr>\n      <th>9999</th>\n      <td>10000</td>\n      <td>Buzz</td>\n    </tr>\n  </tbody>\n</table>\n<p>10000 rows × 2 columns</p>\n</div>\n```\n:::\n:::\n\n\nWith Polars:\n\n::: {#bdae02ea .cell execution_count=12}\n``` {.python .cell-code}\ndf_pl = pl.DataFrame({\"Count\": np.arange(1, n+1)})\ndf_pl.with_columns(pl.col(\"Count\").cast(pl.String).alias(\"FizzBuzz\"))\ndf_pl = df_pl.with_columns(\n    pl.when(pl.col(\"Count\") % 3 == 0).then(pl.lit(\"Fizz\"))\n    .when(pl.col(\"Count\") % 5 == 0).then(pl.lit(\"Buzz\"))\n    .when(pl.col(\"Count\") % 15 == 0).then(pl.lit(\"FizzBuzz\"))\n    .otherwise(pl.col(\"Count\")).alias(\"FizzBuzz\")\n)\n\ndf_pl\n```\n\n::: {.cell-output .cell-output-display execution_count=12}\n```{=html}\n<div><style>\n.dataframe > thead > tr,\n.dataframe > tbody > tr {\n  text-align: right;\n  white-space: pre-wrap;\n}\n</style>\n<small>shape: (10_000, 2)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>Count</th><th>FizzBuzz</th></tr><tr><td>i64</td><td>str</td></tr></thead><tbody><tr><td>1</td><td>&quot;1&quot;</td></tr><tr><td>2</td><td>&quot;2&quot;</td></tr><tr><td>3</td><td>&quot;Fizz&quot;</td></tr><tr><td>4</td><td>&quot;4&quot;</td></tr><tr><td>5</td><td>&quot;Buzz&quot;</td></tr><tr><td>&hellip;</td><td>&hellip;</td></tr><tr><td>9996</td><td>&quot;Fizz&quot;</td></tr><tr><td>9997</td><td>&quot;9997&quot;</td></tr><tr><td>9998</td><td>&quot;9998&quot;</td></tr><tr><td>9999</td><td>&quot;Fizz&quot;</td></tr><tr><td>10000</td><td>&quot;Buzz&quot;</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\nBut it gets much better with [lazy evaluation](polars_lazy.qmd). First, we create a LazyFrame instead of a DataFrame. The query is not evaluated but a graph is created. This allows the query optimizer to combine operations and perform [optimizations](https://docs.pola.rs/user-guide/lazy/optimizations/) where possible, very much the way compilers work. To evaluate the query and get a result, we use the `collect` method.\n\nLet's make sure that the lazy Polars code gives us the same result:\n\nWith the Polars lazy API:\n\n::: {#d8926653 .cell execution_count=13}\n``` {.python .cell-code}\ndf_pl_lazy = pl.LazyFrame({\"Count\": np.arange(1, n+1)})\ndf_pl_lazy.with_columns(pl.col(\"Count\").cast(pl.String).alias(\"FizzBuzz\"))\ndf_pl_lazy = df_pl_lazy.with_columns(\n    pl.when(pl.col(\"Count\") % 3 == 0).then(pl.lit(\"Fizz\"))\n    .when(pl.col(\"Count\") % 5 == 0).then(pl.lit(\"Buzz\"))\n    .when(pl.col(\"Count\") % 15 == 0).then(pl.lit(\"FizzBuzz\"))\n    .otherwise(pl.col(\"Count\")).alias(\"FizzBuzz\")\n)\ndf_pl_lazy_collected = df_pl_lazy.collect()\n\ndf_pl_lazy_collected\n```\n\n::: {.cell-output .cell-output-display execution_count=13}\n```{=html}\n<div><style>\n.dataframe > thead > tr,\n.dataframe > tbody > tr {\n  text-align: right;\n  white-space: pre-wrap;\n}\n</style>\n<small>shape: (10_000, 2)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>Count</th><th>FizzBuzz</th></tr><tr><td>i64</td><td>str</td></tr></thead><tbody><tr><td>1</td><td>&quot;1&quot;</td></tr><tr><td>2</td><td>&quot;2&quot;</td></tr><tr><td>3</td><td>&quot;Fizz&quot;</td></tr><tr><td>4</td><td>&quot;4&quot;</td></tr><tr><td>5</td><td>&quot;Buzz&quot;</td></tr><tr><td>&hellip;</td><td>&hellip;</td></tr><tr><td>9996</td><td>&quot;Fizz&quot;</td></tr><tr><td>9997</td><td>&quot;9997&quot;</td></tr><tr><td>9998</td><td>&quot;9998&quot;</td></tr><tr><td>9999</td><td>&quot;Fizz&quot;</td></tr><tr><td>10000</td><td>&quot;Buzz&quot;</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n#### Timing\n\npandas:\n\n```{.python}\n%%timeit\n\ndf_pd = pd.DataFrame()\ndf_pd[\"Count\"] = np.arange(1, n+1)\ndf_pd[\"FizzBuzz\"] = df_pd[\"Count\"].astype(str)\ndf_pd.loc[df_pd[\"Count\"] % 3 == 0, \"FizzBuzz\"] = \"Fizz\"\ndf_pd.loc[df_pd[\"Count\"] % 5 == 0, \"FizzBuzz\"] = \"Buzz\"\ndf_pd.loc[df_pd[\"Count\"] % 15 == 0, \"FizzBuzz\"] = \"FizzBuzz\"\n```\n\n```\n3.4 ms ± 65.4 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)\n```\n\nPolars:\n\n```{.python}\n%%timeit\n\ndf_pl = pl.DataFrame({\"Count\": np.arange(1, n+1)})\ndf_pl.with_columns(pl.col(\"Count\").cast(pl.String).alias(\"FizzBuzz\"))\ndf_pl.with_columns(\n    pl.when(pl.col(\"Count\") % 3 == 0).then(pl.lit(\"Fizz\"))\n    .when(pl.col(\"Count\") % 5 == 0).then(pl.lit(\"Buzz\"))\n    .when(pl.col(\"Count\") % 15 == 0).then(pl.lit(\"FizzBuzz\"))\n    .otherwise(pl.col(\"Count\")).alias(\"FizzBuzz\")\n)\n```\n\n```\n648 μs ± 2.21 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)\n```\n\nPolars lazy API:\n\n```{.python}\n%%timeit\n\ndf_pl_lazy = pl.LazyFrame({\"Count\": np.arange(1, n+1)})\ndf_pl_lazy.with_columns(pl.col(\"Count\").cast(pl.String).alias(\"FizzBuzz\"))\ndf_pl_lazy = df_pl_lazy.with_columns(\n    pl.when(pl.col(\"Count\") % 3 == 0).then(pl.lit(\"Fizz\"))\n    .when(pl.col(\"Count\") % 5 == 0).then(pl.lit(\"Buzz\"))\n    .when(pl.col(\"Count\") % 15 == 0).then(pl.lit(\"FizzBuzz\"))\n    .otherwise(pl.col(\"Count\")).alias(\"FizzBuzz\")\n)\ndf_pl_lazy_collected = df_pl_lazy.collect()\n```\n\n```\n460 μs ± 1.79 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)\n```\n\nThat's a speedup of **5** for the Eager API and a speedup of **7** for the lazy API.\n\nThese speedups highly depend on the types and sizes of the problems. How much faster Polars is does vary, what doesn’t vary is that it is always much faster.\n\n#### Memory usage\n\n::::{.columns}\n\n:::{.column width=\"32%\"}\n\n**pandas**\n\n::: {#c6a107c1 .cell execution_count=14}\n``` {.python .cell-code}\ndf_pd.memory_usage()\n```\n\n::: {.cell-output .cell-output-display execution_count=14}\n```\nIndex         132\nCount       80000\nFizzBuzz    80000\ndtype: int64\n```\n:::\n:::\n\n\n132 + 80,000 * 2 = \\\n160,132 bytes \\\n**≈ 160 KB**\n\n:::\n\n:::{.column width=\"2%\"}\n:::\n\n:::{.column width=\"32%\"}\n\n**Polars**\n\n::: {#d2797989 .cell execution_count=15}\n``` {.python .cell-code}\ndf_pl.estimated_size()\n```\n\n::: {.cell-output .cell-output-display execution_count=15}\n```\n119409\n```\n:::\n:::\n\n\n119,409 bytes \\\n**≈ 119 KB**\n\n160,132 / 119,409 ≈ 1.3 \\\nFootprint 1.3 times smaller.\n\n:::\n\n:::{.column width=\"2%\"}\n:::\n\n:::{.column width=\"32%\"}\n\n**Polars lazy API**\n\nSame as Polars eager: \\\nif you collect the entire DataFrame as we did here, the lazy API does not reduce the memory footprint.\n\n:::\n\n::::\n\n### Example 2: medium dataset\n\nHere I am using [a jeopardy dataset](https://raw.githubusercontent.com/razoumov/publish/master/jeopardy.csv) that Alex uses in his pandas course.\n\nShape: 216,930 rows, 7 columns.\n\nThe goal is to subset this DataFrame for the history category and get the shape of the resulting DataFrame.\n\nFirst, let's make sure that the code works.\n\npandas:\n\n::: {#b68126b0 .cell execution_count=16}\n``` {.python .cell-code}\ndf_pd = pd.read_csv(\"https://raw.githubusercontent.com/razoumov/publish/master/jeopardy.csv\")\ndf_pd.loc[df_pd[\"Category\"] == \"HISTORY\"].shape\n```\n\n::: {.cell-output .cell-output-display execution_count=16}\n```\n(349, 7)\n```\n:::\n:::\n\n\nPolars:\n\n::: {#a9c0770b .cell execution_count=17}\n``` {.python .cell-code}\ndf_pl = pl.read_csv(\"https://raw.githubusercontent.com/razoumov/publish/master/jeopardy.csv\")\ndf_pl.filter(pl.col(\"Category\") == \"HISTORY\").shape\n```\n\n::: {.cell-output .cell-output-display execution_count=17}\n```\n(349, 7)\n```\n:::\n:::\n\n\nPolars lazy API:\n\n::: {#2e947d93 .cell execution_count=18}\n``` {.python .cell-code}\ndf_pl_lazy = pl.scan_csv(\"https://raw.githubusercontent.com/razoumov/publish/master/jeopardy.csv\")\ndf_pl_lazy_subset_collected = df_pl_lazy.filter(pl.col(\"Category\") == \"HISTORY\").collect()\ndf_pl_lazy_subset_collected.shape\n```\n\n::: {.cell-output .cell-output-display execution_count=18}\n```\n(349, 7)\n```\n:::\n:::\n\n\n:::{.note}\n\nTo create a LazyFrame from a file you use one of the `scan_*` methods instead of the `read_*` methods.\n\n:::\n\n#### Timing\n\npandas:\n\n```{.python}\n%%timeit\n\ndf_pd = pd.read_csv(\"https://raw.githubusercontent.com/razoumov/publish/master/jeopardy.csv\")\ndf_pd.loc[df_pd[\"Category\"] == \"HISTORY\"].shape\n```\n\n```\n1.17 s ± 5.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)\n```\n\nPolars:\n\n```{.python}\n%%timeit\n\ndf_pl = pl.read_csv(\"https://raw.githubusercontent.com/razoumov/publish/master/jeopardy.csv\")\ndf_pl.filter(pl.col(\"Category\") == \"HISTORY\").shape\n```\n\n```\n778 ms ± 30.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)\n```\n\nThat's a speedup of **1.5**.\n\nPolars lazy API timing:\n\n```{.python}\n%%timeit\n\ndf_pl_lazy = pl.scan_csv(\"https://raw.githubusercontent.com/razoumov/publish/master/jeopardy.csv\")\ndf_pl_lazy.filter(pl.col(\"Category\") == \"HISTORY\").collect().shape\n```\n\n```\n67.7 ms ± 3.87 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)\n```\n\nWith the lazy API, the speedup ramps up to **17**.\n\n#### Memory usage\n\n::::{.columns}\n\n:::{.column width=\"30%\"}\n\n::: {#f3d5f614 .cell execution_count=19}\n``` {.python .cell-code}\ndf_pd.memory_usage()\n```\n\n::: {.cell-output .cell-output-display execution_count=19}\n```\nIndex              132\nShow Number    1735440\nAir Date       1735440\nRound          1735440\nCategory       1735440\nValue          1735440\nQuestion       1735440\nAnswer         1735440\ndtype: int64\n```\n:::\n:::\n\n\n132 + 1,735,440 * 7 = \\\n12,148,212 bytes \\\n**≈ 12 MB**\n\n:::\n\n:::{.column width=\"2%\"}\n:::\n\n:::{.column width=\"33%\"}\n\n::: {#590fe2e5 .cell execution_count=20}\n``` {.python .cell-code}\ndf_pl.estimated_size()\n```\n\n::: {.cell-output .cell-output-display execution_count=20}\n```\n31606250\n```\n:::\n:::\n\n\n31,606,250 bytes \\\n**≈ 31 MB**\n\n31,606,250 / 12,148,212 ≈ 2.6 \\\nFootprint 2.6 times *bigger*.\n\n:::\n\n:::{.column width=\"2%\"}\n:::\n\n:::{.column width=\"33%\"}\n\n::: {#1e3e1e89 .cell execution_count=21}\n``` {.python .cell-code}\ndf_pl_lazy_subset_collected.estimated_size()\n```\n\n::: {.cell-output .cell-output-display execution_count=21}\n```\n48774\n```\n:::\n:::\n\n\n48,774 bytes \\\n**≈ 49 KB**\n\n12,148,212 / 48,774 ≈ 249 \\\nFootprint **249 times smaller**.\n\nIf you only collect a subset of the data, the memory footprint drops dramatically.\n\n:::\n\n::::\n\n## Data too big to fit in memory\n\n### Example of large dataset\n\nLet's play with data from the [GBIF](https://www.gbif.org/) website for free and open access to biodiversity data.\n\nThe [Southern African Bird Atlas Project 2](https://www.gbif.org/dataset/906e6978-e292-4a8b-9c39-adf6bb0f3323) [@https://doi.org/10.15468/dl.gqwnm2] contains a raw CSV file of 42 GB and an interpreted CSV file of 12.3 GB. Let's look at the latter:\n\nShape: 25,687,526 rows, 50 columns.\n\nFrom that dataset, I want a list of species from the genus *Passer* (Old World sparrows).\n\n### The importance of file format\n\nText-based formats (CSV, JSON) are not suitable for large files.\n\n[Apache Parquet](https://parquet.apache.org/) is a binary, machine-optimized, column-oriented file format with efficient encoding and compression and it is considered the industry-standard file format for large tabular data.<br>\n\n|  ||| File type ||| Size |\n| -- | -- | -- | -- | -- | -- | -- |\n| File downloaded from GBIF ||| Zipped CSV ||| 2.2 GB |\n| Uncompressed file ||| CSV ||| 12.3 GB |\n| Ideal file format ||| [Parquet]{.emph} ||| [0.5 GB]{.emph} |\n\n<br>In addition to being **15 times (!!) smaller**, the Parquet file is **a lot faster to read & write**.\n\n### Format conversion\n\nHere is a way to convert this file if it fits in memory:\n\n```{.python}\n# Read in the CSV file in a Polars DataFrame\ndf = pl.read_csv(\"sa_birds.csv\", separator=\"\\t\")\n\n# Export the DataFrame in a Parquet file\ndf.write_parquet(\"sa_birds.parquet\")\n```\n\n:::{.note}\n\nIf the file doesn't fit in memory, you can use Dask (which also uses Apache Arrow) on a distributed system.\n\n:::\n\n### Native Apache Arrow support\n\nWith its native support for the columnar Apache Arrow format, Polars is ideal to work with Parquet files.\n\npandas can work with Parquet files but this can lead to issues due to the inconsistent way it handles missing data (e.g. see [this SO question](https://stackoverflow.com/q/54866522/9210961), [this issue](https://github.com/pandas-dev/pandas/issues/55721), [this post](https://learn.microsoft.com/en-au/answers/questions/5534487/timestamp-column-from-parquet-file-(created-with-p#:~:text=Venkat%20Reddy%20Navari,you%20have%20any%20further%20queries.))).\n\n```{.python}\n%%timeit\n\n# pandas\nsa_birds_pd = pd.read_parquet(\n    \"sa_birds.parquet\"\n)\n```\n\n```\n1min 10s ± 7.76 s per loop (mean ± std. dev. of 7 runs, 1 loop each)\n```\n\n```{.python}\n%%timeit\n\n# Polars\nsa_birds_pl = pl.read_parquet(\n    \"sa_birds.parquet\"\n)\n```\n\n```\n2.47 s ± 756 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)\n```\n\nSpeedup: 70 / 2.47 ≈ **28**.\n\n[Reading Parquet files in pandas is also A LOT slower!]{.emph}\n\n### RAM required\n\n::::{.columns}\n\n:::{.column width=\"49%\"}\n\n**pandas**\n\n```{.python}\nsa_birds_pd.memory_usage()\n```\n\n```\nIndex                          132\ngbifID                   205500208\ndatasetKey               205500208\noccurrenceID             205500208\nkingdom                  205500208\nphylum                   205500208\nclass                    205500208\norder                    205500208\n...\ndtype: int64\n```\n\n132 + 205,500,208 * 50 = \\\n10,275,010,532 bytes \\\n**≈ 10 GB**\n\n:::\n\n:::{.column width=\"2%\"}\n:::\n\n:::{.column width=\"49%\"}\n\n**Polars**\n\n```{.python}\nsa_birds_pl.estimated_size()\n```\n\n```\n12291023880\n```\n\n12,291,023,880 bytes \\\n**≈ 12 GB**\n\n:::\n\n::::\n\nLet's image that you have only 16 GB of RAM on your machine.\n\nRunning a browser and a few small applications take about 6 GB out of that. This dataset is already too big to process on your laptop.\n\nIf you need to play with the raw data or a larger dataset such as the [eBird dataset](https://www.gbif.org/dataset/4fa7b334-ce0d-4e88-aaae-2e0c138d049e) of 1,775,781,186 rows and 50 columns (**CSV file of 3 TB for the raw data**), you will need A LOT of memory.\n\n### What are your options?\n\nIn pandas or Polars:\n\n- you can select only the columns you are interested,\n- you can read and process the file in chunks and try to combine the results.\n\n[If you only need to run queries on the data however, the Polars lazy API is the answer.]{.emph}\n\n### Create a LazyFrame\n\nYou can create a LazyFrame (no impact on memory, LazyFrame returned instantly):\n\n::: {#6ce3ee15 .cell execution_count=22}\n``` {.python .cell-code}\ndf_pl_lazy = pl.scan_parquet(\"sa_birds.parquet\")\n```\n:::\n\n\nRun a query on it (no impact on memory, LazyFrame returned instantly):\n\n::: {#b6ec1e13 .cell execution_count=23}\n``` {.python .cell-code}\npasser_df_lazy = df_pl_lazy.filter(\n    pl.col(\"genus\") == \"Passer\"\n).select(pl.col(\"species\")).unique()\n```\n:::\n\n\n### Collect result\n\nNow, you collect the result (this uses memory and takes time to compute) and turn the DataFrame into a Python list:\n\n::: {#1f6d7056 .cell execution_count=24}\n``` {.python .cell-code}\npasser_ls = passer_df_lazy.collect().get_column(\"species\").to_list()\n```\n:::\n\n\nDepending on the subset returned by your query, the memory usage will vary. Here, it is minuscule (79 bytes):\n\n::: {#be54b590 .cell execution_count=25}\n``` {.python .cell-code}\npasser_df_lazy.collect().estimated_size()\n```\n\n::: {.cell-output .cell-output-display execution_count=25}\n```\n79\n```\n:::\n:::\n\n\n### Et voilà\n\n::: {#7641ad93 .cell execution_count=26}\n``` {.python .cell-code}\npasser_ls\n```\n\n::: {.cell-output .cell-output-display execution_count=26}\n```\n['Passer diffusus',\n 'Passer motitensis',\n 'Passer domesticus',\n 'Passer melanurus',\n 'Passer griseus']\n```\n:::\n:::\n\n\nWith this method, as long as the data itself fits on a drive and the queries don't return huge subsets of data, you can run queries on giant datasets such as the 3 TB [eBird dataset](https://www.gbif.org/dataset/4fa7b334-ce0d-4e88-aaae-2e0c138d049e) with a small amount of RAM.\n\nNote that the queries can contain complex expressions. What matters is the size of the subset you need to collect at the end.\n\n## Pandas v2\n\nPandas is trying to fight back: v 2.0 came with optional Arrow support instead of NumPy, then [it became the default engine](https://dataalgo.medium.com/pandas-2-0-ditches-numpy-for-pyarrow-what-you-need-to-know-cbba4cb60249), but performance remains way below that of Polars (e.g. in [DataCamp benchmarks](https://www.datacamp.com/tutorial/high-performance-data-manipulation-in-python-pandas2-vs-polars), [official benchmarks](https://pola.rs/posts/benchmarks/), many blog posts for [whole scripts](https://medium.com/@asimandia/benchmarking-performance-polars-vs-vaex-vs-pandas-f1c889dccc12) or [individual tasks](https://medium.com/cuenex/pandas-2-0-vs-polars-the-ultimate-battle-a378eb75d6d1)).\n\nAnd the problems with missing data and syntax remains. Not to mention the lack of lazy API.\n\n## Comparison with other frameworks\n\n:::{.info}\n\nComparisons between Polars and distributed (Dask, Ray, Spark) or GPU (RAPIDS) libraries aren't the most pertinent since they can be used in *combination with* Polars and the benefits can thus be combined.\n\nIt only makes sense to compare Polars with other libraries occupying the same \"niche\" such as pandas or Vaex.\n\nFor [Vaex](https://github.com/vaexio/vaex), [some benchmark found it twice slower](https://medium.com/@asimandia/benchmarking-performance-polars-vs-vaex-vs-pandas-f1c889dccc12), but this could have changed with recent developments.\n\nOne framework performing better than Polars in some benchmarks is [datatable](https://github.com/h2oai/datatable) (derived from the R package [data.table](https://cran.r-project.org/web/packages/data.table/index.html)), but it hasn't been developed for a year—a sharp contrast with the fast development of Polars.\n\n:::\n\n## Migrating from Pandas\n\nRead [the migration guide](https://docs.pola.rs/user-guide/migration/pandas/#selecting-data): it will help you write Polars code rather than \"literally translated\" Pandas code that runs, but doesn't make use of Polars' strengths. The differences in style mostly come from the fact that Polars runs in parallel.\n\n## Conclusion\n\nPolars:\n\n- handles missing data in a consistent and sensible way,\n- has a clear syntax,\n- allows passing expressions to group by in a convenient way,\n- is very fast,\n- uses multithreading automatically,\n- is extremely memory efficient with the lazy API,\n- uses the industry standard Apache Arrow columnar format,\n- works perfectly with Parquet files,\n- works out-of-core with the lazy API.\n\n**Start using Polars now!**\n\n**And use the lazy API.**\n\n![](img/lazy_polar_bear.jpg){fig-align=\"center\"}\n\n",
    "supporting": [
      "polars_pandas_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}