---
title: AI-powered programming with
author: Marie-Hélène Burle
---

:::{.def}

*Content from [the webinar slides](wb_copilot_slides.qmd) for easier browsing.*

:::

## Coding in the age of generative AI

### Codex

OpenAI [Codex](https://openai.com/blog/openai-codex)—based on GPT-3—is the model behind GitHub Copilot

All the big corporate companies are rushing to launch a growing number of similar (and not free, not open source) productivity products (e.g. [tabnine](https://www.tabnine.com/), Microsoft [Visual Studio IntelliCode](https://visualstudio.microsoft.com/services/intellicode/), Amazon [CodeWhisperer](https://aws.amazon.com/codewhisperer/))

These products generate code in a narrow context (auto-completion or transformation of natural language to code or vise-versa)

### AlphaCode 2

Google DeepMind [AlphaCode 2](https://storage.googleapis.com/deepmind-media/AlphaCode2/AlphaCode2_Tech_Report.pdf)—based on Gemini—stands out as a totally different (and for now totally unavailable) product generating code at the level of competitive programming (reaching the 85^th^ percentile)

Think of it as code evolution by "natural" selection:

- a very large number of code samples are generated (think "mutations")
- a filtering and scoring system selects for the best candidates (that's the selection part)

AlphaCode 2 is able to solve much more open-ended problems

### What about FOSS?

#### Free

These models are large and most convenient to run on servers

&emsp;→ Price of cloud service

Some self-hosted options exist. A very promising one is [Tabby](https://github.com/TabbyML/tabby). Not practical for everyone

#### Open source

While these models feed from open source code, they are themselves not open source 🙁

The open source community is trying to provide open source alternatives (e.g. [Tabby](https://github.com/TabbyML/tabby)). Despite the much more limited resources, the performance of some of these alternatives is very good

## GitHub Copilot

(not free, not open source...)

### What is [GitHub Copilot](https://github.com/features/copilot/)?

:::{.fragment}

**&nbsp;→ Cloud-hosted AI programming assistant**

:::

:::{.fragment}

Developed by [GitHub](https://github.com) (Microsoft)

Running [Codex](https://openai.com/blog/openai-codex), a model by [OpenAI](https://openai.com/) derived from the [LLM](https://en.wikipedia.org/wiki/Large_language_model) GPT-3 and trained on open source code

:::

### Access

Individual or organization GitHub accounts

Requires subscription

Students, teachers, and maintainers of popular open source projects can apply for free access

### Safety

Filters are in place for offensive words, but...

Generated code comes with no guaranty of safety or quality

[A lawsuit is open against GitHub Copilot](https://githubcopilotlitigation.com/) for licenses violation

### Supported languages

Any language used in public repos

Quality of suggestions is higher for languages with lots of data

### How to use it?

:::{.fragment}

Start typing code and get autocomplete suggestions

:::

:::{.fragment}

Write comments describing what the code should do and get code generation based on context

:::

:::{.fragment}

It is easy to:

&emsp;&emsp;→ accept suggestions word by word \
&emsp;&emsp;→ line by line \
&emsp;&emsp;→ for entire functions \
&emsp;&emsp;→ cycle through different suggestions

:::

### Interface

Extensions to text editors:

&emsp;&ensp;→ Visual Studio Code/Visual Studio \
&emsp;&ensp;→ Vim/Neovim/Emacs \
&emsp;&ensp;→ JetBrains IDEs \
&emsp;&ensp;→ Azure Data Studio

## Setup

### Get a subscription

Go to your GitHub account page \
&emsp;&ensp;→ Settings \
&emsp;&ensp;→ Copilot \
&emsp;&ensp;→ Enable

Provide free access or payment method

Set settings

### VS Code

:::{.fragment}

[Install the GitHub Copilot extension](https://marketplace.visualstudio.com/items?itemName=GitHub.copilot)

:::

:::{.fragment}

Next suggestion: &emsp;&emsp;&emsp;&emsp;&emsp;&nbsp;`Alt+]` \
Previous suggestion: &emsp;&emsp;&emsp;&nbsp;&nbsp;`Alt+[`

Reject suggestion: &emsp;&emsp;&emsp;&emsp;&ensp;&nbsp;`Esc` \
Accept suggestion: &emsp;&emsp;&emsp;&emsp;&ensp;`Tab` \
Accept next suggested word: `Ctrl+→` &nbsp;(`Command+→` &nbsp;for macOS) \
Set your own key binding for `editor.action.inlineSuggest.acceptNextLine` to accept next suggested line

Open new tab with options: &ensp;`Ctrl+Enter`

You can also hover over suggestions

:::

### Vim/Neovim

Install [Node.js](https://nodejs.org/en/download/)

Clone <https://github.com/github/copilot.vim>

Configure:

```{.bash}
:Copilot setup
```

Enable:

```{.bash}
:Copilot enable
```

Get help:

```{.bash}
:help copilot
```

### Emacs

Install [Node.js](https://nodejs.org/en/download/)

Assuming [straight](https://github.com/radian-software/straight.el) is installed:

```{.lisp}
(straight-use-package 'editorconfig)                   ; Copilot dependency

(use-package copilot
	:straight (:host github
					 :repo "copilot-emacs/copilot.el"
					 :files ("dist" "*.el"))
	:hook (prog-mode . copilot-mode)	               ; Settings up to you
	:bind (("C-8" . copilot-complete)
		   :map copilot-completion-map
		   ("C-j" . copilot-accept-completion)
		   ("C-f" . copilot-accept-completion-by-word)
		   ("C-t" . copilot-accept-completion-by-line)
		   ("C-n" . copilot-next-completion)
		   ("C-p" . copilot-previous-completion)))
```

Login to your GitHub account (only needs to be done once): `M-x copilot-login`

## Copilot in the CLI

### What is Copilot in the CLI?

*In beta*

An extension to [GitHub CLI](https://cli.github.com/) (GitHub operations from the CLI)

&emsp;→ Generate commands from natural language \
&emsp;→ Generate natural language explanations from commands

Trained on data up to 2021

Lower performance for natural languages ≠ English

[Be very careful: the command line is powerful and you can delete your data or mess up your system if you don't know what you are doing. Check commands carefully!]{.emph}

### Setup

:::{.fragment}

[Install GitHub CLI](https://github.com/cli/cli#installation)

Connect to your GitHub account:

```{.bash}
gh auth login
```

:::

:::{.fragment}

<br>
Install Copilot in the CLI:

```{.bash}
gh extension install github/gh-copilot
```

:::{.note}

Update with: `gh extension upgrade gh-copilot`

:::

:::

### Usage

Get code explanations:

```{.bash}
gh copilot explain
```

<br>
Get code from natural language:

```{.bash}
gh copilot suggest
```

### Resources

[GitHub support portal](https://support.github.com/)

[GitHub Copilot documentation](https://docs.github.com/en/copilot)

Stack Overflow [[github-copilot]](https://stackoverflow.com/questions/tagged/github-copilot) tag

[copilot.el](https://github.com/copilot-emacs/copilot.el) (unofficial Emacs plug-in)
