---
title: A map of current machine learning frameworks
aliases:
  - frameworks_slides.html
frontlogo: /img/logo_sfudrac.png
author: Marie-Hélène Burle
date: 2023-10-03
date-format: long
execute:
  freeze: auto
  cache: true
  error: true
  echo: true
format:
  revealjs:
    embed-resources: true
    theme: [default, ../revealjs.scss]
    logo: /img/favicon_sfudrac.png
    highlight-style: monokai
    code-line-numbers: false
    template-partials:
      - ../title-slide.html
    pointer:
      color: "#b5111b"
      pointerSize: 32
    link-external-newwindow: true
    footer: <a href="wb_frameworks.html"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="rgb(153, 153, 153)" class="bi bi-arrow-90deg-up" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M4.854 1.146a.5.5 0 0 0-.708 0l-4 4a.5.5 0 1 0 .708.708L4 2.707V12.5A2.5 2.5 0 0 0 6.5 15h8a.5.5 0 0 0 0-1h-8A1.5 1.5 0 0 1 5 12.5V2.707l3.146 3.147a.5.5 0 1 0 .708-.708l-4-4z"/></svg>&nbsp;Back to webinar page</a>
    auto-stretch: false
revealjs-plugins:
  - pointer
---

## Disclaimers {.center}

Keeping up with the ever evolving field of machine learning is daunting. This webinar aims to bring a little help in this navigation and maybe inspire you to explore new tools. It is however flawed in several ways:

- it is not exhaustive and focuses on the most used frameworks accessible through 3 popular languages,
- a lot of the content could be accused of being biased and subjective,
- it will be outdated quickly.

Ultimately, the best frameworks are the ones that work best for you and your needs. The only piece of advice I would give is to always use open source tools.

---

```{dot}
//| echo: false

strict graph {

bgcolor="transparent"
node [fontname="Inconsolata, sans-serif", shape=plaintext]

"Traditional machine learning\n(ML)\n→ computational statistics\n→ predictive analytics" [URL="https://en.wikipedia.org/wiki/Computational_statistics", fontsize=8, fontcolor=darkolivegreen]
"Deep learning\n(DL)\n→ artificial neural networks" [URL="https://en.wikipedia.org/wiki/Deep_learning", fontsize=8, fontcolor=darkcyan]

Fields -- {"Traditional machine learning\n(ML)\n→ computational statistics\n→ predictive analytics" "Deep learning\n(DL)\n→ artificial neural networks"}

}
```

---

```{dot}
//| echo: false

strict digraph {
  
bgcolor="transparent"
node [fontname="Inconsolata, sans-serif", shape=plaintext]

ml [label="Traditional machine learning\n(ML)\n→ computational statistics\n→ predictive analytics", URL="https://en.wikipedia.org/wiki/Computational_statistics", fontcolor=darkolivegreen]
dl [label="Deep learning\n(DL)\n    → artificial neural networks", URL="https://en.wikipedia.org/wiki/Deep_learning", fontcolor=darkcyan]

Fields -> {ml dl} [dir=none]

1 [label="- Clustering\l- Naives Bayes\l- Ensemble methods\l- Model selection\l- Decision trees\l", shape=plaintext, fontcolor=gray55]
2 [label="- Architecture building\l- NN operations\l- Automatic differentiation (AD)\l- Optimization functions\l", shape=plaintext, fontcolor=gray55]

ml -> 1 [dir=back, color=gray55]
dl -> 2 [dir=back, color=gray55]

}
```

---

```{dot}
//| echo: false

strict graph {

bgcolor="transparent"
node [fontname="Inconsolata, sans-serif", shape=plaintext]

Python [fontcolor=darkgoldenrod, URL="https://www.python.org/"]
Julia [fontcolor=darkorchid2, URL="https://julialang.org/"]
R [fontcolor=cornflowerblue, URL="https://www.r-project.org/"]

Languages -- {Python Julia R}

}
```

---

```{dot}
//| echo: false

strict graph {

bgcolor="transparent"
graph [fontname="Inconsolata, sans-serif"]
node [fontname="Inconsolata, sans-serif"]
label="Most popular frameworks\n\n"
labelloc=t
fontsize=27

subgraph cluster_ml {
  peripheries=0
  label="Traditional machine learning\n\n"
  fontcolor=darkolivegreen
  fontsize=20
  "scikit-learn" "Several Julia ML packages" "Many R ML packages"
}

subgraph cluster_dl {
  peripheries=0
  label="\nDeep learning"
  fontcolor=darkcyan
  fontsize=20
  labelloc=b
  Torch TensorFlow JAX Keras "Several Julia DL packages" "Several R DL packages"
}

Python [color=darkgoldenrod, fontcolor=darkgoldenrod, URL="https://www.python.org/"]
Julia [color=darkorchid2, fontcolor=darkorchid2, URL="https://julialang.org/"]
R [color=cornflowerblue, fontcolor=cornflowerblue, URL="https://www.r-project.org/"]

"scikit-learn" -- Python [color=darkgoldenrod]
Python -- {Torch TensorFlow JAX Keras} [color=darkgoldenrod]

{"Several Julia ML packages" "scikit-learn"} -- Julia [color=darkorchid2]
Julia -- {"Several Julia DL packages" Torch TensorFlow Keras} [color=darkorchid2]

{"scikit-learn" "Many R ML packages"} -- R [color=cornflowerblue]
R -- {"Several R DL packages" Torch TensorFlow Keras} [color=cornflowerblue]

"Several Julia ML packages" [color=gray55, fontcolor=gray55]
"Several Julia DL packages" [color=gray55, fontcolor=gray55]
"Many R ML packages" [color=gray55, fontcolor=gray55]
"Several R DL packages" [color=gray55, fontcolor=gray55]

"scikit-learn" [URL="https://scikit-learn.org/stable/"]
Keras [URL="https://keras.io/"]
TensorFlow [URL="https://www.tensorflow.org/"]
Torch [URL="https://pytorch.org/"]
JAX [URL="https://jax.readthedocs.io/en/latest/index.html"]

}
```

[scikit-learn](https://scikit-learn.org/stable/) is a toolbox of ML algorithms

[TensorFlow](https://www.tensorflow.org/) was a leading DL framework for years, but is now fading

[PyTorch](https://pytorch.org/) slowly took over TensorFlow, but is now starting to face competition

---

```{dot}
//| echo: false

strict graph {

bgcolor="transparent"
graph [fontname="Inconsolata, sans-serif"]
node [fontname="Inconsolata, sans-serif"]
label="Most popular frameworks\n\n"
labelloc=t
fontsize=27

subgraph cluster_ml {
  peripheries=0
  label="Traditional machine learning\n\n"
  fontcolor=darkolivegreen
  fontsize=20
  "scikit-learn" "Several Julia ML packages" "Many R ML packages"
}

subgraph cluster_dl {
  peripheries=0
  label="\nDeep learning"
  fontcolor=darkcyan
  fontsize=20
  labelloc=b
  Torch TensorFlow JAX Keras "Several Julia DL packages" "Several R DL packages"
}

Python [color=darkgoldenrod, fontcolor=darkgoldenrod, URL="https://www.python.org/"]
Julia [color=darkorchid2, fontcolor=darkorchid2, URL="https://julialang.org/"]
R [color=cornflowerblue, fontcolor=cornflowerblue, URL="https://www.r-project.org/"]

"scikit-learn" -- Python [color=darkgoldenrod]
Python -- {Torch TensorFlow JAX Keras} [color=darkgoldenrod]

{"Several Julia ML packages" "scikit-learn"} -- Julia [color=darkorchid2]
Julia -- {"Several Julia DL packages" Torch TensorFlow Keras} [color=darkorchid2]

{"scikit-learn" "Many R ML packages"} -- R [color=cornflowerblue]
R -- {"Several R DL packages" Torch TensorFlow Keras} [color=cornflowerblue]

"Several Julia ML packages" [color=gray55, fontcolor=gray55]
"Several Julia DL packages" [color=gray55, fontcolor=gray55]
"Many R ML packages" [color=gray55, fontcolor=gray55]
"Several R DL packages" [color=gray55, fontcolor=gray55]

"scikit-learn" [URL="https://scikit-learn.org/stable/"]
Keras [URL="https://keras.io/"]
TensorFlow [URL="https://www.tensorflow.org/"]
Torch [URL="https://pytorch.org/"]
JAX [URL="https://jax.readthedocs.io/en/latest/index.html"]

}
```

[JAX](https://jax.readthedocs.io/en/latest/index.html) is its own [domain specific language (DSL)](https://en.wikipedia.org/wiki/Domain-specific_language) of restrictive NumPy-like "pure" functions with automatic differentiation (AD) and accelerated linear algebra (XLA)—a domain-specific compiler

[keras](https://keras.io/) is a high-level API for DL

---

```{dot}
//| echo: false

strict graph {

bgcolor="transparent"
graph [fontname="Inconsolata, sans-serif"]
node [fontname="Inconsolata, sans-serif"]
label="Most popular frameworks\n\n"
labelloc=t
fontsize=27

subgraph cluster_ml {
  peripheries=0
  label="Traditional machine learning\n\n"
  fontcolor=darkolivegreen
  fontsize=20
  "scikit-learn" "Several Julia ML packages" "Many R ML packages"
}

subgraph cluster_dl {
  peripheries=0
  label="\nDeep learning"
  fontcolor=darkcyan
  fontsize=20
  labelloc=b
  Torch TensorFlow JAX Keras "Several Julia DL packages" "Several R DL packages"
}

Python [color=darkgoldenrod, fontcolor=darkgoldenrod, URL="https://www.python.org/"]
Julia [color=darkorchid2, fontcolor=darkorchid2, URL="https://julialang.org/"]
R [color=cornflowerblue, fontcolor=cornflowerblue, URL="https://www.r-project.org/"]

"scikit-learn" -- Python [color=darkgoldenrod]
Python -- {Torch TensorFlow JAX Keras} [color=darkgoldenrod]

{"Several Julia ML packages" "scikit-learn"} -- Julia [color=darkorchid2]
Julia -- {"Several Julia DL packages" Torch TensorFlow Keras} [color=darkorchid2]

{"scikit-learn" "Many R ML packages"} -- R [color=cornflowerblue]
R -- {"Several R DL packages" Torch TensorFlow Keras} [color=cornflowerblue]

"Several Julia ML packages" [color=gray55, fontcolor=gray55]
"Several Julia DL packages" [color=gray55, fontcolor=gray55]
"Many R ML packages" [color=gray55, fontcolor=gray55]
"Several R DL packages" [color=gray55, fontcolor=gray55]

"scikit-learn" [URL="https://scikit-learn.org/stable/"]
Keras [URL="https://keras.io/"]
TensorFlow [URL="https://www.tensorflow.org/"]
Torch [URL="https://pytorch.org/"]
JAX [URL="https://jax.readthedocs.io/en/latest/index.html"]

}
```

A fast evolving field: 
&emsp;- [MXNET](https://github.com/apache/mxnet) was just retired a few days ago \
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;- [caffe2](https://github.com/facebookarchive/caffe2) is now part of [PyTorch](https://github.com/pytorch/pytorch/) \
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;- [JAX](https://jax.readthedocs.io/en/latest/index.html) is looking like a replacement for [TensorFlow](https://www.tensorflow.org/) \
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;- [keras](https://github.com/keras-team/keras-core) has been the high-level frontend for a shifting list of \ &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&nbsp;backends (currently [TensorFlow](https://github.com/tensorflow/tensorflow), [PyTorch](https://github.com/pytorch/pytorch?fbclid=IwAR3mdJ6akutefkkOuCbzhsSRqrJPumMkpGIZvCxz-xRWcdYU2uw63yn2_ig), [JAX](https://github.com/jax-ml/jax))

---

```{dot}
//| echo: false

strict graph {

  label="Python\n\n"
  fontcolor=darkgoldenrod
  labelloc=t
  fontsize=30
  
  bgcolor="transparent"
  graph [fontname="Inconsolata, sans-serif"]
  node [fontname="Inconsolata, sans-serif"]

  subgraph cluster_ml {
	peripheries=0
	label="Traditional machine learning\n\n"
	fontcolor=darkolivegreen
	fontsize=20
	"scikit-learn" "Several Julia ML packages" "Many R ML packages"
  }

  subgraph cluster_dl {
	peripheries=0
	label="\nDeep learning"
	fontcolor=darkcyan
	fontsize=20
	labelloc=b
	Torch TensorFlow JAX Keras "Several Julia DL packages" "Several R DL packages"
  }

  Python [color=darkgoldenrod, fontcolor=darkgoldenrod, URL="https://www.python.org/"]
  Julia [color=gray55, fontcolor=gray55, URL="https://julialang.org/"]
  R [color=gray55, fontcolor=gray55, URL="https://www.r-project.org/"]

  "scikit-learn" [color=darkgoldenrod, URL="https://scikit-learn.org/stable/"]
  Keras [color=darkgoldenrod, URL="https://keras.io/"]
  TensorFlow [color=darkgoldenrod, URL="https://www.tensorflow.org/"]
  Torch [color=darkgoldenrod, URL="https://pytorch.org/"]
  JAX [color=darkgoldenrod, URL="https://jax.readthedocs.io/en/latest/index.html"]
  
  "scikit-learn" -- Python [color=darkgoldenrod]
  Python -- {Torch TensorFlow JAX Keras} [color=darkgoldenrod]

  {"Several Julia ML packages" "scikit-learn"} -- Julia [color=gray55]
  Julia -- {"Several Julia DL packages" Torch TensorFlow Keras} [color=gray55]

  {"scikit-learn" "Many R ML packages"} -- R [color=gray55]
  R -- {"Several R DL packages" Torch TensorFlow Keras} [color=gray55]

  "Several Julia ML packages" [color=gray55, fontcolor=gray55]
  "Several Julia DL packages" [color=gray55, fontcolor=gray55]
  "Many R ML packages" [color=gray55, fontcolor=gray55]
  "Several R DL packages" [color=gray55, fontcolor=gray55]
  
}
```

Several popular packages written *for* Python, but [not]{.underline} *in* Python (too slow) \
→ written in Fortran, C, C++, or DSL

---

```{dot}
//| echo: false

strict graph {

  label="Julia\n\n"
  fontcolor=darkorchid2
  labelloc=t
  fontsize=30
  
  bgcolor="transparent"
  graph [fontname="Inconsolata, sans-serif"]
  node [fontname="Inconsolata, sans-serif"]

  subgraph cluster_ml {
	peripheries=0
	label="Traditional machine learning\n\n"
	fontcolor=darkolivegreen
	fontsize=20
	"scikit-learn" "Several Julia ML packages" "Many R ML packages"
  }

  subgraph cluster_dl {
	peripheries=0
	label="\nDeep learning"
	fontcolor=darkcyan
	fontsize=20
	labelloc=b
	Torch TensorFlow JAX Keras "Several Julia DL packages" "Several R DL packages"
  }

  Python [color=gray55, fontcolor=gray55, URL="https://www.python.org/"]
  Julia [color=darkorchid2, fontcolor=darkorchid2, URL="https://julialang.org/"]
  R [color=gray55, fontcolor=gray55, URL="https://www.r-project.org/"]

  "Several Julia ML packages" [color=darkorchid2, fontcolor=darkorchid2]
  "Several Julia DL packages" [color=darkorchid2, fontcolor=darkorchid2]
  Keras [color=darkorchid2, fontcolor=darkorchid2, URL="https://github.com/ayush1999/Keras.jl"]
  "scikit-learn" [color=darkorchid2, URL="https://github.com/cstjean/ScikitLearn.jl"]
  TensorFlow [color=darkorchid2, URL="https://malmaud.github.io/tfdocs/"]
  Torch [color=darkorchid2, URL="https://github.com/FluxML/Torch.jl"]

  "scikit-learn" -- Python [color=gray55]
  Python -- {Torch TensorFlow JAX Keras} [color=gray55]

  {"Several Julia ML packages" "scikit-learn"} -- Julia [color=darkorchid2]
  Julia -- {"Several Julia DL packages" Torch TensorFlow Keras} [color=darkorchid2]

  {"scikit-learn" "Many R ML packages"} -- R [color=gray55]
  R -- {"Several R DL packages" Torch TensorFlow Keras} [color=gray55]

  "Many R ML packages" [color=gray55, fontcolor=gray55]
  "Several R DL packages" [color=gray55, fontcolor=gray55]
  JAX [color=gray55, fontcolor=gray55]

}
```

Classic Python packages available in Julia thanks to wrappers \
In addition <font color="#b23aee">many packages written in Julia</font> (as the language is fast enough)

---

```{dot}
//| echo: false

strict graph {

label="Julia\n\n"
fontcolor=darkorchid2
labelloc=t
fontsize=30

bgcolor="transparent"
graph [fontname="Inconsolata, sans-serif"]
node [fontname="Inconsolata, sans-serif"]

subgraph cluster_ml {
  peripheries=0
  label="Traditional machine learning\n\n"
  fontcolor=darkolivegreen
  fontsize=20
  "scikit-learn" "Several Julia ML packages" "Many R ML packages"
}

subgraph cluster_dl {
  peripheries=0
  label="\nDeep learning"
  fontcolor=darkcyan
  fontsize=20
  labelloc=b
  Torch TensorFlow JAX Keras "Several Julia DL packages" "Several R DL packages"
}

Python [color=gray55, fontcolor=gray55, URL="https://www.python.org/"]
Julia [color=darkorchid2, fontcolor=darkorchid2, URL="https://julialang.org/"]
R [color=gray55, fontcolor=gray55, URL="https://www.r-project.org/"]

"Several Julia ML packages" [color=darkorchid2, fontcolor=darkorchid2]
"Several Julia DL packages" [color=darkorchid2, fontcolor=darkorchid2]
Keras [color=gray55, fontcolor=gray55, URL="https://github.com/ayush1999/Keras.jl"]
"scikit-learn" [color=gray55, fontcolor=gray55, URL="https://github.com/cstjean/ScikitLearn.jl"]
TensorFlow [color=gray55, fontcolor=gray55, URL="https://malmaud.github.io/tfdocs/"]
Torch [color=gray55, fontcolor=gray55, URL="https://github.com/FluxML/Torch.jl"]

"scikit-learn" -- Python [color=gray55]
Python -- {Torch TensorFlow JAX Keras} [color=gray55]

{"Several Julia ML packages" "scikit-learn"} -- Julia [color=darkorchid2]
Julia -- {"Several Julia DL packages" Torch TensorFlow Keras} [color=darkorchid2]

{"scikit-learn" "Many R ML packages"} -- R [color=gray55]
R -- {"Several R DL packages" Torch TensorFlow Keras} [color=gray55]

"Many R ML packages" [color=gray55, fontcolor=gray55]
"Several R DL packages" [color=gray55, fontcolor=gray55]
JAX [color=gray55, fontcolor=gray55]

}
```

Let's have a look at the Julia specific packages.

---

```{dot}
//| echo: false

strict graph {

  label="A rich ecocystem of packages\n\n"
  labelloc=t
  fontsize=30

  bgcolor="transparent"
  graph [fontname="Inconsolata, sans-serif"]
  node [fontname="Inconsolata, sans-serif", color=darkorchid2]
  compound=true

  subgraph cluster_ml {
	label="Traditional machine learning\n\n"
	color=darkorchid2
	fontcolor=darkolivegreen
	fontsize=20
	edge [style=invis]
	node [fontsize=20]
	{rank=same; AugmentedGaussianProcesses MachineLearning TSML DecisionTree}
	{rank=same; EvoTrees ZigZagBoomerang LightGBM Turing BayesianOptimization}
	{rank=same; MLJ GLMNet LIBSVM MLBase MLKernels Clustering ForneyLab}
	AugmentedGaussianProcesses -- EvoTrees -- MLJ
  }

  subgraph cluster_dl {	
	label="\nDeep learning"
	color=darkorchid2
	fontcolor=darkcyan
	fontsize=20
	labelloc=b
	node [fontsize=20]
	Flux Lux Knet Merlin MLJFlux FluxTraining GraphNeuralNetworks
  }

  Flux [URL="https://github.com/FluxML/Flux.jl"]
  Lux [URL="https://github.com/LuxDL/"]
  Knet [URL="https://github.com/denizyuret/Knet.jl"]
  Merlin [URL=""]
  MLJFlux [URL=""]
  FluxTraining [URL=""]
  GraphNeuralNetworks [URL=""]
  MLJ [URL="https://github.com/alan-turing-institute/MLJ.jl"]
  Turing [URL="https://github.com/TuringLang/Turing.jl"]

  Julia [fontsize=18]
  Julia [fontcolor=darkorchid2, URL="https://julialang.org/"]

  MLBase -- Julia [ltail=cluster_ml, color=darkorchid2]
  Julia -- MLJFlux [lhead=cluster_dl, color=darkorchid2]

}
```

---

```{dot}
//| echo: false

strict graph {

  label="Not counting utility packages...\n\n"
  labelloc=t
  fontsize=40

  bgcolor="transparent"
  graph [fontname="Inconsolata, sans-serif"]
  node [fontname="Inconsolata, sans-serif", color=darkorchid2]
  compound=true

  subgraph cluster_ml {
	label="Traditional machine learning\n\n"
	color=darkorchid2
	fontcolor=darkolivegreen
	fontsize=25
	edge [style=invis]
	node [fontsize=28]
	{rank=same; AugmentedGaussianProcesses MachineLearning TSML DecisionTree}
	{rank=same; EvoTrees ZigZagBoomerang LightGBM Turing BayesianOptimization}
	{rank=same; MLJ GLMNet LIBSVM MLBase MLKernels Clustering ForneyLab}
	AugmentedGaussianProcesses -- EvoTrees -- MLJ
  }

  subgraph cluster_dl {	
	label="\nDeep learning"
	color=darkorchid2
	fontcolor=darkcyan
	fontsize=30
	labelloc=b
	edge [style=invis]
	node [fontsize=28]
	Flux Lux Knet Merlin MLJFlux FluxTraining GraphNeuralNetworks
	subgraph cluster_utilities {
	  peripheries=0
	  fontsize=25
	  label="Utilities:"
	  fontcolor=darkorchid2
	  labelloc=t
 	  node [fontsize=19]
	  DataLoaders MLUtils MLDataUtils MLDatasets TensorBoardLogger ObjectDetector Metalhead
	}
	GraphNeuralNetworks -- Metalhead
  }

  Flux [URL="https://github.com/FluxML/Flux.jl"]
  Lux [URL="https://github.com/LuxDL/"]
  Knet [URL="https://github.com/denizyuret/Knet.jl"]
  Merlin [URL=""]
  MLJFlux [URL=""]
  FluxTraining [URL=""]
  GraphNeuralNetworks [URL=""]
  MLJ [URL="https://github.com/alan-turing-institute/MLJ.jl"]
  Turing [URL="https://github.com/TuringLang/Turing.jl"]

  Julia [fontsize=24, fontcolor=darkorchid2, URL="https://julialang.org/"]

  MLBase -- Julia [ltail=cluster_ml, color=darkorchid2]
  Julia -- MLJFlux [lhead=cluster_dl, color=darkorchid2]

}
```

---

```{dot}
//| echo: false

strict graph {

  label="And many AD implementations!\n\n"
  labelloc=t
  fontsize=45

  bgcolor="transparent"
  graph [fontname="Inconsolata, sans-serif"]
  node [fontname="Inconsolata, sans-serif", color=darkorchid2]
  compound=true
  
  subgraph cluster_ml {
	label="Traditional machine learning\n\n"
	color=darkorchid2
	fontcolor=darkolivegreen
	fontsize=30
	edge [style=invis]
	node [fontsize=36]
	{rank=same; AugmentedGaussianProcesses MachineLearning TSML DecisionTree}
	{rank=same; EvoTrees ZigZagBoomerang LightGBM Turing BayesianOptimization}
	{rank=same; MLJ GLMNet LIBSVM MLBase MLKernels Clustering ForneyLab}
	AugmentedGaussianProcesses -- EvoTrees -- MLJ
  }

  subgraph cluster_dl {	
	label="\nDeep learning"
	color=darkorchid2
	fontcolor=darkcyan
	fontsize=30
	labelloc=b
	edge [style=invis]
	node [fontsize=36]
	Flux Lux Knet Merlin MLJFlux FluxTraining GraphNeuralNetworks
	subgraph cluster_utilities {
	  peripheries=0
	  fontsize=25
	  label="Utilities:"
	  labelloc=t
	  fontcolor=darkorchid2
	  node [fontsize=25]
	  DataLoaders MLUtils MLDataUtils MLDatasets TensorBoardLogger ObjectDetector Metalhead
	}
	subgraph cluster_autodiff {
	  peripheries=0
	  fontsize=25
	  label="Autodiff:"
	  labelloc=t
	  fontcolor=darkorchid2
	  node [fontsize=30]
	  ForwardDiff ReverseDiff Zygote Enzyme ChainRules TaylorDiff StochasticAD
	}
	GraphNeuralNetworks -- Metalhead
	Metalhead -- StochasticAD
  }

  Flux [URL="https://github.com/FluxML/Flux.jl"]
  Lux [URL="https://github.com/LuxDL/"]
  Knet [URL="https://github.com/denizyuret/Knet.jl"]
  Merlin [URL=""]
  MLJFlux [URL=""]
  FluxTraining [URL=""]
  GraphNeuralNetworks [URL=""]
  MLJ [URL="https://github.com/alan-turing-institute/MLJ.jl"]
  Turing [URL="https://github.com/TuringLang/Turing.jl"]
  ForwardDiff [URL="https://github.com/JuliaDiff/ForwardDiff.jl"]
  ReverseDiff [URL="https://github.com/JuliaDiff/ReverseDiff.jl"]
  Zygote [URL="https://github.com/FluxML/Zygote.jl"]
  Enzyme [URL="https://github.com/EnzymeAD/Enzyme.jl"]
  ChainRules [URL="https://github.com/JuliaDiff/ChainRules.jl"]
  TaylorDiff [URL="https://github.com/JuliaDiff/TaylorDiff.jl"]
  StochasticAD [URL="https://github.com/gaurav-arya/StochasticAD.jl"]

  Julia [fontsize=26, fontcolor=darkorchid2, URL="https://julialang.org/"]

  MLBase -- Julia [ltail=cluster_ml, color=darkorchid2]
  Julia -- MLJFlux [lhead=cluster_dl, color=darkorchid2]
  
}
```

---

```{dot}
//| echo: false

strict graph {

  label="Notable options\n\n"
  labelloc=t
  fontsize=45

  bgcolor="transparent"
  graph [fontname="Inconsolata, sans-serif"]
  node [fontname="Inconsolata, sans-serif", color=gray55, fontcolor=gray55]
  compound=true
  
  subgraph cluster_ml {
	label="Traditional machine learning\n\n"
	color=darkorchid2
	fontcolor=darkolivegreen
	fontsize=30
	edge [style=invis]
	node [fontsize=36]
	{rank=same; AugmentedGaussianProcesses MachineLearning TSML DecisionTree}
	{rank=same; EvoTrees ZigZagBoomerang LightGBM Turing BayesianOptimization}
	{rank=same; MLJ GLMNet LIBSVM MLBase MLKernels Clustering ForneyLab}
	AugmentedGaussianProcesses -- EvoTrees -- MLJ
  }

  subgraph cluster_dl {	
	label="\nDeep learning"
	color=darkorchid2
	fontcolor=darkcyan
	fontsize=30
	labelloc=b
	edge [style=invis]
	node [fontsize=36]
	Flux Lux Knet Merlin MLJFlux FluxTraining GraphNeuralNetworks
	subgraph cluster_utilities {
	  peripheries=0
	  fontsize=25
	  label="Utilities:"
	  labelloc=t
	  fontcolor=gray55
	  node [fontsize=25]
	  DataLoaders MLUtils MLDataUtils MLDatasets TensorBoardLogger ObjectDetector Metalhead
	}
	subgraph cluster_autodiff {
	  peripheries=0
	  fontsize=25
	  label="Autodiff:"
	  labelloc=t
	  fontcolor=gray55
	  node [fontsize=30]
	  ForwardDiff ReverseDiff Zygote Enzyme ChainRules TaylorDiff StochasticAD
	}
	GraphNeuralNetworks -- Metalhead
	Metalhead -- StochasticAD
  }

  Flux [color=darkorchid2, fontcolor=black, URL="https://github.com/FluxML/Flux.jl"]
  Lux [color=darkorchid2, fontcolor=black, URL="https://github.com/LuxDL/"]
  Knet [URL="https://github.com/denizyuret/Knet.jl"]
  Merlin [URL=""]
  MLJFlux [URL=""]
  FluxTraining [URL=""]
  GraphNeuralNetworks [URL=""]
  MLJ [color=darkorchid2, fontcolor=black, URL="https://github.com/alan-turing-institute/MLJ.jl"]
  Turing [URL="https://github.com/TuringLang/Turing.jl"]
  ForwardDiff [URL="https://github.com/JuliaDiff/ForwardDiff.jl"]
  ReverseDiff [URL="https://github.com/JuliaDiff/ReverseDiff.jl"]
  Zygote [color=darkorchid2, fontcolor=black, URL="https://github.com/FluxML/Zygote.jl"]
  Enzyme [color=darkorchid2, fontcolor=black, URL="https://github.com/EnzymeAD/Enzyme.jl"]
  ChainRules [URL="https://github.com/JuliaDiff/ChainRules.jl"]
  TaylorDiff [URL="https://github.com/JuliaDiff/TaylorDiff.jl"]
  StochasticAD [URL="https://github.com/gaurav-arya/StochasticAD.jl"]

  Julia [fontsize=26, color=darkorchid2, fontcolor=darkorchid2, URL="https://julialang.org/"]

  MLBase -- Julia [ltail=cluster_ml, color=darkorchid2]
  Julia -- MLJFlux [lhead=cluster_dl, color=darkorchid2]
  
}
```

*Machine learning:*

[MLJ](https://github.com/alan-turing-institute/MLJ.jl) is a ML toolbox with Julia functions and wrappers to scikit-learn models

---

```{dot}
//| echo: false

strict graph {

  label="Notable options\n\n"
  labelloc=t
  fontsize=45

  bgcolor="transparent"
  graph [fontname="Inconsolata, sans-serif"]
  node [fontname="Inconsolata, sans-serif", color=gray55, fontcolor=gray55]
  compound=true
  
  subgraph cluster_ml {
	label="Traditional machine learning\n\n"
	color=darkorchid2
	fontcolor=darkolivegreen
	fontsize=30
	edge [style=invis]
	node [fontsize=36]
	{rank=same; AugmentedGaussianProcesses MachineLearning TSML DecisionTree}
	{rank=same; EvoTrees ZigZagBoomerang LightGBM Turing BayesianOptimization}
	{rank=same; MLJ GLMNet LIBSVM MLBase MLKernels Clustering ForneyLab}
	AugmentedGaussianProcesses -- EvoTrees -- MLJ
  }

  subgraph cluster_dl {	
	label="\nDeep learning"
	color=darkorchid2
	fontcolor=darkcyan
	fontsize=30
	labelloc=b
	edge [style=invis]
	node [fontsize=36]
	Flux Lux Knet Merlin MLJFlux FluxTraining GraphNeuralNetworks
	subgraph cluster_utilities {
	  peripheries=0
	  fontsize=25
	  label="Utilities:"
	  labelloc=t
	  fontcolor=gray55
	  node [fontsize=25]
	  DataLoaders MLUtils MLDataUtils MLDatasets TensorBoardLogger ObjectDetector Metalhead
	}
	subgraph cluster_autodiff {
	  peripheries=0
	  fontsize=25
	  label="Autodiff:"
	  labelloc=t
	  fontcolor=gray55
	  node [fontsize=30]
	  ForwardDiff ReverseDiff Zygote Enzyme ChainRules TaylorDiff StochasticAD
	}
	GraphNeuralNetworks -- Metalhead
	Metalhead -- StochasticAD
  }

  Flux [color=darkorchid2, fontcolor=black, URL="https://github.com/FluxML/Flux.jl"]
  Lux [color=darkorchid2, fontcolor=black, URL="https://github.com/LuxDL/"]
  Knet [URL="https://github.com/denizyuret/Knet.jl"]
  Merlin [URL=""]
  MLJFlux [URL=""]
  FluxTraining [URL=""]
  GraphNeuralNetworks [URL=""]
  MLJ [color=darkorchid2, fontcolor=black, URL="https://github.com/alan-turing-institute/MLJ.jl"]
  Turing [URL="https://github.com/TuringLang/Turing.jl"]
  ForwardDiff [URL="https://github.com/JuliaDiff/ForwardDiff.jl"]
  ReverseDiff [URL="https://github.com/JuliaDiff/ReverseDiff.jl"]
  Zygote [color=darkorchid2, fontcolor=black, URL="https://github.com/FluxML/Zygote.jl"]
  Enzyme [color=darkorchid2, fontcolor=black, URL="https://github.com/EnzymeAD/Enzyme.jl"]
  ChainRules [URL="https://github.com/JuliaDiff/ChainRules.jl"]
  TaylorDiff [URL="https://github.com/JuliaDiff/TaylorDiff.jl"]
  StochasticAD [URL="https://github.com/gaurav-arya/StochasticAD.jl"]

  Julia [fontsize=26, color=darkorchid2, fontcolor=darkorchid2, URL="https://julialang.org/"]

  MLBase -- Julia [ltail=cluster_ml, color=darkorchid2]
  Julia -- MLJFlux [lhead=cluster_dl, color=darkorchid2]
  
}
```

*Neural networks:*

[Flux](https://fluxml.ai/) is a DL framework similar to PyTorch in pure Julia

[Lux](https://github.com/LuxDL/) is a rewrite of Flux keeping the trainable and non-trainable parameters decoupled

---

```{dot}
//| echo: false

strict graph {

  label="Notable options\n\n"
  labelloc=t
  fontsize=45

  bgcolor="transparent"
  graph [fontname="Inconsolata, sans-serif"]
  node [fontname="Inconsolata, sans-serif", color=gray55, fontcolor=gray55]
  compound=true
  
  subgraph cluster_ml {
	label="Traditional machine learning\n\n"
	color=darkorchid2
	fontcolor=darkolivegreen
	fontsize=30
	edge [style=invis]
	node [fontsize=36]
	{rank=same; AugmentedGaussianProcesses MachineLearning TSML DecisionTree}
	{rank=same; EvoTrees ZigZagBoomerang LightGBM Turing BayesianOptimization}
	{rank=same; MLJ GLMNet LIBSVM MLBase MLKernels Clustering ForneyLab}
	AugmentedGaussianProcesses -- EvoTrees -- MLJ
  }

  subgraph cluster_dl {	
	label="\nDeep learning"
	color=darkorchid2
	fontcolor=darkcyan
	fontsize=30
	labelloc=b
	edge [style=invis]
	node [fontsize=36]
	Flux Lux Knet Merlin MLJFlux FluxTraining GraphNeuralNetworks
	subgraph cluster_utilities {
	  peripheries=0
	  fontsize=25
	  label="Utilities:"
	  labelloc=t
	  fontcolor=gray55
	  node [fontsize=25]
	  DataLoaders MLUtils MLDataUtils MLDatasets TensorBoardLogger ObjectDetector Metalhead
	}
	subgraph cluster_autodiff {
	  peripheries=0
	  fontsize=25
	  label="Autodiff:"
	  labelloc=t
	  fontcolor=gray55
	  node [fontsize=30]
	  ForwardDiff ReverseDiff Zygote Enzyme ChainRules TaylorDiff StochasticAD
	}
	GraphNeuralNetworks -- Metalhead
	Metalhead -- StochasticAD
  }

  Flux [color=darkorchid2, fontcolor=black, URL="https://github.com/FluxML/Flux.jl"]
  Lux [color=darkorchid2, fontcolor=black, URL="https://github.com/LuxDL/"]
  Knet [URL="https://github.com/denizyuret/Knet.jl"]
  Merlin [URL=""]
  MLJFlux [URL=""]
  FluxTraining [URL=""]
  GraphNeuralNetworks [URL=""]
  MLJ [color=darkorchid2, fontcolor=black, URL="https://github.com/alan-turing-institute/MLJ.jl"]
  Turing [URL="https://github.com/TuringLang/Turing.jl"]
  ForwardDiff [URL="https://github.com/JuliaDiff/ForwardDiff.jl"]
  ReverseDiff [URL="https://github.com/JuliaDiff/ReverseDiff.jl"]
  Zygote [color=darkorchid2, fontcolor=black, URL="https://github.com/FluxML/Zygote.jl"]
  Enzyme [color=darkorchid2, fontcolor=black, URL="https://github.com/EnzymeAD/Enzyme.jl"]
  ChainRules [URL="https://github.com/JuliaDiff/ChainRules.jl"]
  TaylorDiff [URL="https://github.com/JuliaDiff/TaylorDiff.jl"]
  StochasticAD [URL="https://github.com/gaurav-arya/StochasticAD.jl"]

  Julia [fontsize=26, color=darkorchid2, fontcolor=darkorchid2, URL="https://julialang.org/"]

  MLBase -- Julia [ltail=cluster_ml, color=darkorchid2]
  Julia -- MLJFlux [lhead=cluster_dl, color=darkorchid2]
  
}
```

*Autodiff:*

[Zygote](https://github.com/FluxML/Zygote.jl) is the AD engine for Flux

[Enzyme](https://enzyme.mit.edu/) is a novel, more powerful AD tool for languages using the LLVM compiler. Now being incorporated in Lux

---

```{dot}
//| echo: false

strict graph {

  label="R\n\n"
  fontcolor=cornflowerblue
  labelloc=t
  fontsize=30
  
  bgcolor="transparent"
  graph [fontname="Inconsolata, sans-serif"]
  node [fontname="Inconsolata, sans-serif"]

  subgraph cluster_ml {
	peripheries=0
	label="Traditional machine learning\n\n"
	fontcolor=darkolivegreen
	fontsize=20
	"scikit-learn" "Several Julia ML packages" "Many R ML packages"
  }

  subgraph cluster_dl {
	peripheries=0
	label="\nDeep learning"
	fontcolor=darkcyan
	fontsize=20
	labelloc=b
	Torch TensorFlow JAX Keras "Several Julia DL packages" "Several R DL packages"
  }

  Python [color=gray55, fontcolor=gray55, URL="https://www.python.org/"]
  Julia [color=gray55, fontcolor=gray55, URL="https://julialang.org/"]
  R [color=cornflowerblue, fontcolor=cornflowerblue, URL="https://www.r-project.org/"]

  "Many R ML packages" [color=cornflowerblue]
  "Several R DL packages" [color=cornflowerblue]
  "scikit-learn" [color=cornflowerblue, URL="https://saraswatmks.github.io/superml/"]
  Keras [color=cornflowerblue, URL="https://github.com/rstudio/keras"]
  TensorFlow [color=cornflowerblue, URL="https://tensorflow.rstudio.com/"]
  Torch [color=cornflowerblue, URL="https://torch.mlverse.org/"]

  "scikit-learn" -- Python [color=gray55]
  Python -- {Torch TensorFlow JAX Keras} [color=gray55]

  {"Several Julia ML packages" "scikit-learn"} -- Julia [color=gray55]
  Julia -- {"Several Julia DL packages" Torch TensorFlow Keras} [color=gray55]

  {"scikit-learn" "Many R ML packages"} -- R [color=cornflowerblue]
	R -- {"Several R DL packages" Torch TensorFlow Keras} [color=cornflowerblue]

	"Several Julia ML packages" [color=gray55, fontcolor=gray55]
	"Several Julia DL packages" [color=gray55, fontcolor=gray55]
	JAX [color=gray55, fontcolor=gray55]
	
}
```

Classic Python packages available in R thanks to wrappers \
In addition many packages written *for* R, but [not]{.underline} *in* R (too slow) \
→ written in Fortran, C, or C++

---

```{dot}
//| echo: false

strict graph {

  label="R\n\n"
  fontcolor=cornflowerblue
  labelloc=t
  fontsize=30
  
  bgcolor="transparent"
  graph [fontname="Inconsolata, sans-serif"]
  node [fontname="Inconsolata, sans-serif"]

  subgraph cluster_ml {
	peripheries=0
	label="Traditional machine learning\n\n"
	fontcolor=darkolivegreen
	fontsize=20
	"scikit-learn" "Several Julia ML packages" "Many R ML packages"
  }

  subgraph cluster_dl {
	peripheries=0
	label="\nDeep learning"
	fontcolor=darkcyan
	fontsize=20
	labelloc=b
	Torch TensorFlow JAX Keras "Several Julia DL packages" "Several R DL packages"
  }

  Python [color=gray55, fontcolor=gray55, URL="https://www.python.org/"]
  Julia [color=gray55, fontcolor=gray55, URL="https://julialang.org/"]
  R [color=cornflowerblue, fontcolor=cornflowerblue, URL="https://www.r-project.org/"]

  "Many R ML packages" [color=cornflowerblue]
  "Several R DL packages" [color=cornflowerblue]
  "scikit-learn" [color=gray55, fontcolor=gray55, URL="https://saraswatmks.github.io/superml/"]
  Keras [color=gray55, fontcolor=gray55, URL="https://github.com/rstudio/keras"]
  TensorFlow [color=gray55, fontcolor=gray55, URL="https://tensorflow.rstudio.com/"]
  Torch [color=gray55, fontcolor=gray55, URL="https://torch.mlverse.org/"]

  "scikit-learn" -- Python [color=gray55]
  Python -- {Torch TensorFlow JAX Keras} [color=gray55]

  {"Several Julia ML packages" "scikit-learn"} -- Julia [color=gray55]
  Julia -- {"Several Julia DL packages" Torch TensorFlow Keras} [color=gray55]

  {"scikit-learn" "Many R ML packages"} -- R [color=cornflowerblue]
  R -- {"Several R DL packages" Torch TensorFlow Keras} [color=cornflowerblue]

  "Several Julia ML packages" [color=gray55, fontcolor=gray55]
  "Several Julia DL packages" [color=gray55, fontcolor=gray55]
  JAX [color=gray55, fontcolor=gray55]

}
```

Let's have a look at the R specific packages.

---

```{dot}
//| echo: false

strict graph {

  bgcolor="transparent"
  graph [fontname="Inconsolata, sans-serif"]
  node [fontname="Inconsolata, sans-serif", color=cornflowerblue]
  compound=true

  subgraph cluster_ml {
	label="Traditional machine learning\n\n"
	color=cornflowerblue
	fontcolor=darkolivegreen
	fontsize=20
	edge [style=invis]
	node [fontsize=18]
	{rank=same; e1071 kernlab rpart party caret gmodels randomForest ranger}
	{rank=same; ipred gbm xgboost C50 cluster class mclust naivebayes glmnet}
	e1071 -- ipred
  }

  subgraph cluster_dl {	
	label="\nDeep learning"
	color=cornflowerblue
	fontcolor=darkcyan
	fontsize=20
	labelloc=b
	node [fontsize=18]
	RSNNS h2o darch deepr RCNN4R rcppDL rnn neuralnet deepnet
  }

  ranger [URL=""]
  randomForest [URL=""]
  gmodels [URL="https://cran.r-project.org/web/packages/gmodels/index.html"]
  caret [URL=""]
  party [URL="https://cran.r-project.org/web/packages/party/index.html"]
  rpart [URL=""]
  kernlab [URL=""]
  e1071 [URL=""]
  glmnet [URL=""]
  naivebayes [URL=""]
  mclust [URL=""]
  class [URL=""]
  cluster [URL=""]
  C50 [URL=""]
  xgboost [URL=""]
  gbm [URL=""]
  ipred [URL=""]
  deepnet [URL=""]
  neuralnet [URL=""]
  rnn [URL=""]
  rcppDL [URL=""]
  RCNN4R [URL=""]
  deepr [URL=""]
  darch [URL=""]
  h2o [URL=""]
  RSNNS [URL=""]

  R [fontcolor=cornflowerblue, URL="https://www.r-project.org/"]

  cluster -- R [ltail=cluster_ml, color=cornflowerblue]
  R -- RCNN4R [lhead=cluster_dl, color=cornflowerblue]

}
```

A very large field, particularly when it comes to statistical machine learning

Quite a lot of DL packages, despite R's slow speed

The [Machine Learning CRAN Task View](https://cran.r-project.org/web/views/MachineLearning.html) is a good reference for many packages

---

#### Languages summary

```{dot}
//| echo: false

strict graph {

bgcolor="transparent"
graph [fontname="Inconsolata, sans-serif"]
node [fontname="Inconsolata, sans-serif"]
edge [style=invis]

1 [label="- Huge userbase\l- Mature frameworks\l- Smooth APIs\l- Easy to scale\l", shape=plaintext, fontsize=13]
2 [label="Needs other\llanguages\lfor speed\l", shape=plaintext, fontsize=13]
3 [label="- All in Julia\l- Tools at the\ledge of research\l- Great for developpers\l", shape=plaintext, fontsize=13, URL="https://sciml.ai/"]
4 [label="- Small userbase\l- Not the smoothest\lfor end users\l", shape=plaintext, fontsize=13]
5 [label="- Countless packages\n- Very user-friendly\n- Well documented", shape=plaintext, fontsize=13]
6 [label="- Needs C for\lspeed\l- Slow\l- Too slow for DL\l- Hard to scale\l", shape=plaintext, fontsize=13]

Strengths [shape=underline]
Weaknesses [shape=underline]

Python [color=darkgoldenrod, fontcolor=darkgoldenrod, URL="https://www.python.org/"]
Julia [color=darkorchid2, fontcolor=darkorchid2, URL="https://julialang.org/"]
R [color=cornflowerblue, fontcolor=cornflowerblue, URL="https://www.r-project.org/"]

{rank=same; Strengths 1 3 5}
{rank=same; Weaknesses 2 4 6}

Python -- 1 -- 2
Julia -- 3 -- 4
R -- 5 -- 6

Strengths -- 1 -- 3 -- 5
Weaknesses -- 2 -- 4 -- 6

}
```

---

#### Languages summary

```{dot}
//| echo: false

strict graph {

bgcolor="transparent"
graph [fontname="Inconsolata, sans-serif"]
node [fontname="Inconsolata, sans-serif"]
edge [style=invis]

1 [label="Good", shape=plaintext]
2 [label="Good", shape=plaintext]
3 [label="Good", shape=plaintext]
4 [label="Good", shape=plaintext]
5 [label="Good", shape=plaintext]
6 [label="Very limited", shape=plaintext]

"Machine learning" [shape=plaintext, fontcolor=darkolivegreen]
"Deep learning" [shape=plaintext, fontcolor=darkcyan]

Python [color=darkgoldenrod, fontcolor=darkgoldenrod, URL="https://www.python.org/"]
Julia [color=darkorchid2, fontcolor=darkorchid2, URL="https://julialang.org/"]
R [color=cornflowerblue, fontcolor=cornflowerblue, URL="https://www.r-project.org/"]

{rank=same; "Machine learning" 1 3 5}
{rank=same; "Deep learning" 2 4 6}

Python -- 1 -- 2
Julia -- 3 -- 4
R -- 5 -- 6

"Machine learning" -- 1 -- 3 -- 5
"Deep learning" -- 2 -- 4 -- 6

}
```

---

#### Frameworks picks

```{dot}
//| echo: false

strict digraph {
  
bgcolor="transparent"
graph [fontname="Inconsolata, sans-serif"]
node [fontname="Inconsolata, sans-serif"]
label="Machine learning\n\n"
fontcolor=darkolivegreen
labelloc=t

1 [label="scikit-learn\lor MLJ\l", shape=plaintext]
2 [label="Julia or R\lstats packages\l", shape=plaintext]

3 [label="Toolboxes of\nclassic algorithms", shape=plaintext, fontcolor=gray55]
4 [label="Advanced and\lspecialized techniques\lWhich ones to use\ldepends on specific problems\l", shape=plaintext, fontcolor=gray55]

{rank=same; 1 2}
{rank=same; 3 4}

1 -> 2 [style=invis]
1 -> 3 [dir=back, color=gray55]
2 -> 4 [dir=back, color=gray55]

}
```

:::aside

Many other options are also excellent. This selection is based on great documentation, ease of use, and popularity. It is very subjective.

:::

---

#### Frameworks picks

```{dot}
//| echo: false

strict digraph {
  
bgcolor="transparent"
graph [fontname="Inconsolata, sans-serif"]
node [fontname="Inconsolata, sans-serif"]
label="Deep learning\n\n"
fontsize=16
fontcolor=darkcyan
labelloc=t

1 [label=PyTorch, shape=plaintext]
2 [label=JAX, shape=plaintext]
3 [label="Lux with Enzyme", shape=plaintext]

4 [label="Optional Keras\lat high-level\lOptional JIT\l", shape=plaintext, fontcolor=gray55]
5 [label="Sophisticated AD\lOptional packages\lfor ease of use\l(e.g. Equinox)\lDomain-specific language\l", shape=plaintext, fontcolor=gray55]
6 [label="Explicit parameters\lHigh performance AD\lJIT (Julia)\l", shape=plaintext, fontcolor=gray55]

{rank=same; 1 2 3}

1 -> 2 -> 3 [style=invis]

1 -> 4 [dir=back, color=gray55]
2 -> 4 [dir=back, color=gray55]
2 -> 5 [dir=back, color=gray55]
3 -> 6 [dir=back, color=gray55]

}
```

:::aside

Here, the selection is based on speed, which is crucial for DL.

:::

---

#### Frameworks picks

```{dot}
//| echo: false

strict digraph {
  
bgcolor="transparent"
graph [fontname="Inconsolata, sans-serif"]
node [fontname="Inconsolata, sans-serif"]
label="Deep learning\n\n"
fontsize=16
fontcolor=darkcyan
labelloc=t

1 [label=PyTorch, shape=plaintext]
2 [label=JAX, shape=plaintext]
3 [label="Lux with Enzyme", shape=plaintext]

4 [label="Optional Keras\lat high-level\lOptional JIT\l", shape=plaintext, fontcolor=gray55]
5 [label="Sophisticated AD\lOptional packages\lfor ease of use\l(e.g. Equinox, Flax)\l", shape=plaintext, fontcolor=gray55]
6 [label="Explicit parameters\lHigh performance AD\lJIT (Julia)\l", shape=plaintext, fontcolor=gray55]

7 [label="Easy\lAll in Python\lUnified framework\l", shape=plaintext, fontcolor=gray55]
8 [label="Fastest options at the moment\lMany optional moving parts\lRequires learning a DSL (JAX)\lor Julia (Lux)\l", shape=plaintext, fontcolor=gray55]

{rank=same; 1 2 3}

1 -> 2 -> 3 [style=invis]

1 -> 4 [dir=back, color=gray55]
2 -> 4 [dir=back, color=gray55]
2 -> 5 [dir=back, color=gray55]
3 -> 6 [dir=back, color=gray55]

4 -> 7 [dir=back, color=gray55]
5 -> 8 [dir=back, color=gray55]
6 -> 8 [dir=back, color=gray55]

}
```

---

```{dot}
//| echo: false

strict digraph {
  
bgcolor="transparent"
graph [fontname="Inconsolata, sans-serif"]
node [fontname="Inconsolata, sans-serif", fontsize=15]
label="Automatic differentiation (AD)\n\n"
fontsize=18
labelloc=t

1 [label="Static graph\nand XLA", shape=plaintext, group=g1]
2 [label="Dynamic tape-based", shape=plaintext, group=g1]
3 [label="Dynamic tape-based\nand JIT", shape=plaintext, group=g1]
4 [label="Eager graph\nand XLA", shape=plaintext, group=g1]
5 [label="Non-standard interpretation\nand XLA", shape=plaintext, group=g1]
6 [label="Works at lower level", shape=plaintext, group=g1]
7 [label="Works on LLVM itself", shape=plaintext, group=g1]

a [label="TensorFlow", shape=plaintext, fontcolor=darkgoldenrod, color=darkgoldenrod, group=g2, shape=oval]
b [label="PyTorch", shape=plaintext, fontcolor=darkgoldenrod, color=darkgoldenrod, group=g2, shape=oval]
c [label="PyTorch", shape=plaintext, fontcolor=darkgoldenrod, color=darkgoldenrod, group=g2, shape=oval]
d [label="TensorFlow2", shape=plaintext, fontcolor=darkgoldenrod, color=darkgoldenrod, group=g2, shape=oval]
e [label="JAX", shape=plaintext, fontcolor=darkgoldenrod, color=darkgoldenrod, group=g2, shape=oval]
f [label="Zygote", shape=plaintext, fontcolor=darkorchid2, color=darkorchid2, group=g2, shape=oval]
g [label="Enzyme", shape=plaintext, fontcolor=darkorchid2, color=darkorchid2, group=g2, shape=oval]

A [label="Inconvenient", shape=plaintext, fontcolor=gray55, group=g3]
B [label="Hard to optimize", shape=plaintext, fontcolor=gray55, group=g3]
C [label="Not currently developped", shape=plaintext, fontcolor=gray55, group=g3]
D [label="Dynamism doesn't\nplay well with XLA", shape=plaintext, fontcolor=gray55, group=g3]
E [label="Only sublanguage", shape=plaintext, fontcolor=gray55, group=g3]
F [label="Harder implementation", shape=plaintext, fontcolor=gray55, group=g3]
G [label="Very hard to implement", shape=plaintext, fontcolor=gray55, group=g3]

{rank=same; 1 a A}
{rank=same; 2 b B}
{rank=same; 3 c C}
{rank=same; 4 d D}
{rank=same; 5 e E}
{rank=same; 6 f F}
{rank=same; 7 g G}

1 -> a -> A [style=invis]
2 -> b -> B [style=invis]
3 -> c -> C [style=invis]
4 -> d -> D [style=invis]
5 -> e -> E [style=invis]
6 -> f -> F [style=invis]
7 -> g -> G [style=invis]

1 -> 2 -> 3 -> 4 -> 5 -> 6 -> 7
a -> b -> c -> d -> e -> f -> g [style=invis]
A -> B -> C -> D -> E -> F -> G [style=invis]

}
```

:::aside

From [a blog post by Christopher Rackauckas](https://www.stochasticlifestyle.com/engineering-trade-offs-in-automatic-differentiation-from-tensorflow-and-pytorch-to-jax-and-julia/)

:::

<!-- Could turn this last slide into a series of slides with everything grayed out except for the line I am talking about. -->





<!-- alternative autodiff in Python -->
<!-- https://github.com/HIPS -->

<!-- https://kidger.site/thoughts/jax-vs-julia/ -->
<!-- https://forem.julialang.org/jacobusmmsmit/thoughts-on-using-jax-and-julia-2f0b -->
<!-- https://www.stochasticlifestyle.com/engineering-trade-offs-in-automatic-differentiation-from-tensorflow-and-pytorch-to-jax-and-julia/ -->

<!-- https://juliahub.com/ui/Search?t=machine-learning -->
<!-- https://juliapackages.com/c/machine-learning -->

<!-- https://stackoverflow.com/questions/54527439/differences-in-scikit-learn-keras-or-pytorch -->

<!-- https://pytorch-geometric.readthedocs.io/en/latest/ -->

<!-- look into scaling of frameworks -->
