---
title: A map of current ML frameworks
aliases:
  - frameworks.html
author: Marie-Hélène Burle
---

:::{.def}

We are in a period of active development of new deep learning techniques, adding to the already mature area of traditional machine learning. This is leading to a vast and ever evolving field of implementations which can be disorienting.

In this webinar, I will guide you through a map of the current frameworks, organizing them based on their domain (machine learning vs deep learning) and the languages required to use them. I will also talk about the various automatic differentiation options available.

To narrow such a large topic, I am limiting the map to frameworks that can be used from Python, Julia, and R.

:::

[Slides](wb_frameworks_slides.qmd){.btn .btn-outline-primary} [(Click and wait: this reveal.js presentation is heavy and takes some time to load.)]{.inlinenote}
<br><br>

{{< video https://www.youtube.com/embed/XGtiCBz2gIg >}}

<br>
*[Slides content](wb_frameworks_content.qmd) for easier browsing.*

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "LearningResource",
  "name": "A map of current deep learning frameworks",
  "description": "We are in a period of active development of new deep learning techniques, adding to the already mature area of traditional machine learning. This is leading to a vast and ever evolving field of implementations which can be disorienting.\n\nIn this webinar, I will guide you through a map of the current frameworks, organizing them based on their domain (machine learning vs deep learning) and the languages required to use them. I will also talk about the various automatic differentiation options available.\n\nTo narrow such a large topic, I am limiting the map to frameworks that can be used from Python, Julia, and R.",
  "url": "https://mint.westdri.ca/ai/wb_frameworks",
  "learningResourceType": "slides, video",
  "inLanguage": "en",
  "license": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
  "provider": {
    "@type": "Organization",
    "name": "SFU Research Computing Group"
  },
  "keywords": "AI, deep learning, machine learning",
  "author": {
    "@type": "Person",
    "name": "Marie-Hélène Burle"
  },
  "educationalLevel": "beginner"
}
</script>
