---
title: Harnessing big data<br>for agricultural excellence
subtitle: "Part 1: Understanding big data in agriculture"
frontpic: /img/logo_sfu_agro.png
frontpicwidth: 40%
noshadow: noshadow
author: Marie-Hélène Burle
institute: Simon Fraser University's Big Data Hub
date: 2024-11-20
date-format: long
execute:
  error: true
  echo: true
format:
  revealjs:
    <!-- embed-resources: true -->
    theme: [default, ../revealjs_sfu.scss]
    logo: /img/logo_sfu_bigdata.png
    highlight-style: monokai
    code-line-numbers: false
    template-partials:
      - ../title-slide.html
    pointer:
      color: "#b5111b"
      pointerSize: 32
    link-external-newwindow: true
    <!-- footer: <a href="ws_bccai.html"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="rgb(153, 153, 153)" class="bi bi-arrow-90deg-up" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M4.854 1.146a.5.5 0 0 0-.708 0l-4 4a.5.5 0 1 0 .708.708L4 2.707V12.5A2.5 2.5 0 0 0 6.5 15h8a.5.5 0 0 0 0-1h-8A1.5 1.5 0 0 1 5 12.5V2.707l3.146 3.147a.5.5 0 1 0 .708-.708l-4-4z"/></svg>&nbsp;Back to workshop page</a> -->
revealjs-plugins:
  - pointer
---

# Welcome to the Big Data Hub

## SFU Big Data Hub {.center}

Since 2016, the SFU Big Data Hub has offered workshops, events, and consulting services for researchers and industry

SFU is home to the Cedar computer cluster, soon to be replaced by an even bigger supercomputer

## Goal of this workshop {.center}

- Clarify important concepts around big data
- Demonstrate how important big data has become in agriculture and farming

:::{.note}

This workshop will be followed by a 2<sup>nd</sup> session on challenges and solutions while working with big data

:::

## Concepts {.center}

### Big data

Datasets so large that they cannot be processed by conventional analytics methods, but which open up possibilities for predictive analytics and machine learning

### Machine learning (ML)

A subfield of AI that can be defined as computer programs whose performance at a task improves with experience

### Modelling

A subfield of ML, modelling is the use of mathematical models to calculate predictions

### Deep learning (DL)

A subfield of ML using artificial neural networks to calculate predictions or generate novel data

## Why has big data become so popular? {.center}

In typical computing, a programmer writes code that gives a computer detailed instructions of what to do

Coding all the possible ways—pixel by pixel—that an image can represent, say, a dog is an impossibly large task: there are many breeds of dogs, the image can be a picture, a blurred picture, a drawing, a cartoon, the dog can be in all sorts of positions, wearing clothes, etc.

There just aren't enough resources to make the traditional programming approach able to create a computer program that can identify a dog in images

By feeding a very large number of dog images to a neural network however, we can train that network to recognize dogs in images that it has never seen (without explicitly programming how it does this!)

# So how does it all work?

. . .

<br>
It depends on the type of learning

## Supervised learning {.center}

- *Regression* is a form of supervised learning with continuous outputs
- *Classification* is supervised learning with discrete outputs

Supervised learning uses training data in the form of example input/output pairs

### Goal

Find the relationship between inputs and outputs

## Unsupervised learning {.center}

Clustering, social network analysis, market segmentation, PCA ... are all forms of unsupervised learning

Unsupervised learning uses unlabelled data

### Goal

Find structure within the data

## Reinforcement learning {.center}

The algorithm explores by performing random actions and these actions are rewarded or punished (bonus points or penalties)

This is how algorithms learn to play games

# Big data in agriculture

## Types of data {.center}

- Soil pH
- Soil NPK ratios
- Seeds types/breeds
- Satellite data
- Rainfall
- Temperatures
- UVs
- Insects/parasites/pathogens abundance

## Models {.center}

Models can help forecast:

- Weather
- Yield
- Machines wear
- Energy needs

Which helps with the planning of:

- Fertilizer/pesticides amounts and schedules
- Crop rotations
- Supply chains

## Internet of Things (IoT) {.center}

## The cloud {.center}

# Case studies

## 

## 

## 

# Resources

## Tools {.center}

Here are just a few:

- [scikit-learn](https://scikit-learn.org/stable/): a Python ML library built on top of [SciPy](https://scipy.org/)
- [Natural Language Toolkit (NLTK)](https://www.nltk.org/): a suite of Python libraries geared towards teaching and research
- [spaCy](https://spacy.io/): Python library geared towards production
- [torchtext](https://pytorch.org/text/stable/index.html), part of the [PyTorch](https://pytorch.org/) project (and many options of added layers on top such as [PyTorch-NLP](https://pytorchnlp.readthedocs.io/en/latest/)): Python library
- [GenSim](https://radimrehurek.com/gensim/): Python library
- [Stanford CoreNLP](https://stanfordnlp.github.io/CoreNLP/): Java library
- [Many libraries in the Julia programming language](https://juliapackages.com/c/machine-learning)

## Which one to choose? {.center}

[Choose an open source tool](https://mint.westdri.ca/ai/choosing_frameworks.html){target="_blank"} (i.e. stay away from proprietary software such as MATLAB)

- Researchers who do not have access to the tool cannot reproduce your methods (open tools = open equitable research)
- Once you graduate, you may not have access to the tool anymore
- Your university may stop paying for a license
- You may get locked-in
- Proprietary tools are often black boxes
- Long-term access is not guaranty (problem to replicate studies)
- The licenses you have access to may be limiting and a cause of headache
- Proprietary tools fall behind popular open-source tools
- Proprietary tools often fail to address specialized edge cases needed in research

## Neural nets {.center}

[3Blue1Brown by Grant Sanderson](https://www.3blue1brown.com/) has a series of 4 videos on neural networks which is easy to watch, fun, and does an excellent job at introducing the functioning of a simple neural network

- [What are NN? (19 min)](https://www.youtube.com/embed/aircAruvnKk)
- [How do NN learn? (21 min)](https://www.youtube.com/embed/IHZwWFHWa-w)
- [What is backpropagation? (14 min)](https://www.youtube.com/embed/Ilg3gGewQ5U)
- [How does backpropagation work? (10 min)](https://www.youtube.com/embed/tIeHLnjs5U8)

:::{.note}

As you develop your own ML models, if you find that your mathematical background is shaky, 3blue1brown also has [an excellent series of videos on linear algebra](https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab) and [an equally great one on calculus](https://www.youtube.com/playlist?list=PLZHQObOWTQDMsr9K-rj53DwVRMYO3t5Yr)

:::

## Open-access preprints {.center}

- [Arxiv Sanity Preserver by Andrej Karpathy](http://arxiv-sanity.com/)
- [ML papers in the computer science category on arXiv](https://arxiv.org/list/cs.LG/recent)
- [ML papers in the stats category on arXiv](https://arxiv.org/list/stat.ML/recent)
- [Distill ML research online journal](https://distill.pub/)

## Advice and sources {.center}

- [Advice and sources from ML research student](https://web.mit.edu/tslvr/www/lessons_two_years.html)

## Getting help {.center}

Stack Overflow:

- [[machine-learning] tag](https://stackoverflow.com/questions/tagged/machine-learning)
- [[deep-learning] tag](https://stackoverflow.com/questions/tagged/deep-learning)
- [[supervised-learning] tag](https://stackoverflow.com/questions/tagged/supervised-learning)
- [[unsupervised-learning] tag](https://stackoverflow.com/questions/tagged/unsupervised-learning)
- [[semisupervised-learning] tag](https://stackoverflow.com/questions/tagged/semisupervised-learning)
- [[reinforcement-learning] tag](https://stackoverflow.com/questions/tagged/reinforcement-learning)
- [[transfer-learning] tag](https://stackoverflow.com/questions/tagged/transfer-learning)
- [[machine-learning-model] tag](https://stackoverflow.com/questions/tagged/machine-learning-model)
- [[learning-rate] tag](https://stackoverflow.com/questions/tagged/learning-rate)

## Open datasets {.center}

- [benchmarks.ai](https://benchmarks.ai)
- [AIBench](https://www.benchcouncil.org/AIBench/index.html#AIBench)
- [kaggle](https://www.kaggle.com/datasets)
- [Wikipedia](https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research)

## PyTorch {.center}

- [Documentation](https://pytorch.org/docs/stable/index.html)
- [Tutorials](https://pytorch.org/tutorials/)
- [Examples](https://github.com/pytorch/examples)

### Getting help

- [PyTorch Discourse forum](https://discuss.pytorch.org/)
- [Stack Overflow [pytorch] tag](https://stackoverflow.com/questions/tagged/pytorch)

### Pre-trained models

- [PyTorch Hub](https://pytorch.org/hub/)

## Python {.center}

### IDE

- [Project Jupyter](https://jupyter.org/)
- [List of IDEs with description](https://wiki.python.org/moin/IntegratedDevelopmentEnvironments)
- [Comparison of IDEs](https://en.wikipedia.org/wiki/Comparison_of_integrated_development_environments#Python)
- [Emacs Python IDE](https://github.com/jorgenschaefer/elpy)

### Getting help

- [Stack Overflow [python] tag](https://stackoverflow.com/questions/tagged/python)
