---
title: Intro to deep learning, NLP, and LLMs
author: Marie-Hélène Burle
---

:::{.def}

◦ How does deep learning really work? \
◦ What exactly are those large language models everybody talks about? \
◦ How can I build a neural network? \
◦ What is NLP?

This presentation will answer these questions in a non-technical manner to give you a high-level understanding of a discipline that has become crucial in all fields of research.

:::

[Slides](ws_dl_nlp_llm_slides.html){.btn .btn-outline-primary} [(Click and wait: the presentation might take a few instants to load)]{.inlinenote}
<br><br>

{{< video https://www.youtube.com/embed/YqUFNv7L63A >}}

<br>
*[Slides content](ws_dl_nlp_llm_content.qmd) for easier browsing.*

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "LearningResource",
  "name": "An introduction to deep learning, NLP, and LLMs",
  "description": "- How does deep learning really work?\n\n- What exactly are those large language models everybody talks about?\n\n- How can I build a neural network?\n\n- What is NLP?\n\nThis presentation will answer these questions in a non-technical manner to give you a high-level understanding of a discipline that has become crucial in all fields of research.",
  "url": "https://mint.westdri.ca/ai/ws_dl_nlp_llm",
  "learningResourceType": [
    "slides",
	"video"
  ],
  "inLanguage": "en",
  "license": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
  "provider": {
    "@type": "Organization",
    "name": "SFU Research Computing Group"
  },
  "keywords": "AI, deep learning, machine learning, NLP, LLM",
  "author": {
    "@type": "Person",
    "name": "Marie-Hélène Burle"
  },
  "educationalLevel": "beginner"
}
</script>
