---
title: Intro to ML for the humanities
aliases:
  - intro_hss.html
author: Marie-Hélène Burle
---

:::{.def}

We hear about it all the time, but what really is machine learning? And what about deep learning? Neural networks?? How can any of this help me with my work? And how? Which tools do I need to make use of the transformative advances happening in that field??

This workshop will answer these questions in a non-technical manner to give you a high level overview of a discipline that has become crucial in all fields of research.

:::

[Slides](ws_hss_intro_slides.html){.btn .btn-outline-primary} [(Click and wait: the presentation might take a few instants to load)]{.inlinenote}
<br><br>

{{< video https://www.youtube.com/embed/UrCwLM4Zu-Q >}}

<br>
*[Slides content](ws_hss_intro_content.qmd) for easier browsing.*

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "LearningResource",
  "name": "An introduction to machine learning for the humanities",
  "description": "We hear about it all the time, but what really is machine learning? And what about deep learning? Neural networks?? How can any of this help me with my work? And how? Which tools do I need to make use of the transformative advances happening in that field?\n\nThis workshop will answer these questions in a non-technical manner to give you a high level overview of a discipline that has become crucial in all fields of research.",
  "url": "https://mint.westdri.ca/ai/ws_hss_intro",
  "learningResourceType": "slides, video",
  "inLanguage": "en",
  "license": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
  "provider": {
    "@type": "Organization",
    "name": "SFU Research Computing Group"
  },
  "keywords": "AI, machine learning, deep learning, humanities, HSS",
  "author": {
    "@type": "Person",
    "name": "Marie-Hélène Burle"
  },
  "educationalLevel": "beginner"
}
</script>
