---
title: fastai
aliases:
  - fastai.html
  - /ai/wb_fastai.html
subtitle: A deep learning library for fast implementation and research
author: Marie-Hélène Burle
---

:::{.def}

[fastai](https://docs.fast.ai/) is a deep learning library which provides practitioners with high-level components that can quickly and easily provide state-of-the-art results in standard deep learning domains. This webinar will take a closer look at its features and functionality.

:::

{{< video https://www.youtube.com/embed/Q3__FzA6XLc >}}

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "LearningResource",
  "name": "fastai: a deep learning library for fast implementation and research",
  "description": "[fastai](https://docs.fast.ai/) is a deep learning library which provides practitioners with high-level components that can quickly and easily provide state-of-the-art results in standard deep learning domains. This webinar will take a closer look at its features and functionality.",
  "url": "https://mint.westdri.ca/ai/pt/wb_fastai",
  "learningResourceType": "video",
  "inLanguage": "en",
  "license": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
  "provider": {
    "@type": "Organization",
    "name": "SFU Research Computing Group"
  },
  "keywords": "AI, deep learning, fastai, PyTorch",
  "author": {
    "@type": "Person",
    "name": "Marie-Hélène Burle"
  },
  "educationalLevel": "beginner"
}
</script>
