---
title: Everything you wanted to know (and more) about PyTorch tensors
aliases:
  - torchtensors.html
  - /ai/wb_torchtensors.html
author: Marie-Hélène Burle
---

:::{.def}

Before information can be fed to artificial neural networks (ANNs), it needs to be converted to a form ANNs can process: floating point numbers. Indeed, you don't pass a sentence or an image through an ANN; you input numbers representing a sequence of words or pixel values.

All these floating point numbers need to be stored in a data structure. The most suited structure is multidimensional (to hold several layers of information) and since all data is of the same type, it is an array.

Python already has several multidimensional array structures—the most popular of which being [NumPy](https://numpy.org/)'s ndarray—but the particularities of deep learning call for special characteristics: ability to run operations on GPUs and/or in a distributed fashion, as well as the ability to keep track of computation graphs for [automatic differentiation](https://en.wikipedia.org/wiki/Automatic_differentiation).

The PyTorch tensor is a Python data structure with these characteristics that can also easily be converted to/from NumPy's ndarray and integrates well with other Python libraries such as [Pandas](https://pandas.pydata.org/).

In this webinar, suitable for users of all levels, we will have a deep look at this data structure and go much beyond a basic introduction.

In particular, we will:

- see how tensors are stored in memory,
- look at the metadata which allows this efficient memory storage,
- cover the basics of working with tensors (indexing, vectorized operations...),
- move tensors to/from GPUs,
- convert tensors to/from NumPy ndarrays,
- see how tensors work in distributed frameworks,
- see how linear algebra can be done with PyTorch tensors.

:::

[Slides](wb_torchtensors_slides.qmd){.btn .btn-outline-primary} [(Click and wait: this reveal.js presentation may take a little time to load.)]{.inlinenote}
<br><br>

{{< video https://www.youtube.com/embed/n-3h9ucTN4w >}}

<br>
*[Slides content](wb_torchtensors_content.qmd) for easier browsing.*

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "LearningResource",
  "name": "Everything you wanted to know (and more) about PyTorch tensors",
  "description": "Before information can be fed to artificial neural networks (ANNs), it needs to be converted to a form ANNs can process: floating point numbers. Indeed, you don’t pass a sentence or an image through an ANN; you input numbers representing a sequence of words or pixel values.\n\nAll these floating point numbers need to be stored in a data structure. The most suited structure is multidimensional (to hold several layers of information) and since all data is of the same type, it is an array.\n\nPython already has several multidimensional array structures—the most popular of which being NumPy’s ndarray—but the particularities of deep learning call for special characteristics: ability to run operations on GPUs and/or in a distributed fashion, as well as the ability to keep track of computation graphs for automatic differentiation.\n\nThe PyTorch tensor is a Python data structure with these characteristics that can also easily be converted to/from NumPy’s ndarray and integrates well with other Python libraries such as Pandas.\n\nIn this webinar, suitable for users of all levels, we will have a deep look at this data structure and go much beyond a basic introduction.\n\nIn particular, we will:\n\n- see how tensors are stored in memory,\n\n- look at the metadata which allows this efficient memory storage,\n\n- cover the basics of working with tensors (indexing, vectorized operations…),\n\n- move tensors to/from GPUs,\n\n- convert tensors to/from NumPy ndarrays,\n\n- see how tensors work in distributed frameworks,\n\n- see how linear algebra can be done with PyTorch tensors.",
  "url": "https://mint.westdri.ca/ai/pt/wb_torchtensors",
  "learningResourceType": "slides, video",
  "inLanguage": "en",
  "license": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
  "provider": {
    "@type": "Organization",
    "name": "SFU Research Computing Group"
  },
  "keywords": "AI, deep learning, PyTorch, tensor",
  "author": {
    "@type": "Person",
    "name": "Marie-Hélène Burle"
  },
  "educationalLevel": "beginner"
}
</script>
