---
title: Setup
author: Marie-Hélène Burle
---

:::{.def}

Let's start by setting things up for the course.

:::

## On your computer

[This is for your future information only. During the course, we will use a temporary training cluster.]{.emph}

### Requirements

To run CuPy on your computer, you need [a supported OS and at least one supported GPU](gpu_cuda.html#support.qmd). If you don't, you can use a cloud service or the Alliance supercomputers.

### Installation

I suggest installing CuPy on your computer with [uv](https://github.com/astral-sh/uv):

- If you already have CUDA 13, you can install CuPy with:

```{.bash}
uv init --bare	                      # Initiate project
uv add cupy-cuda13x					  # Install CuPy
```

:::{.note}

Replace `cupy-cuda13x` by `cupy-cuda12x` if you have CUDA 12.

:::

- If you don't have CUDA, install CuPy with a CUDA toolkit as a dependency with:

```{.bash}
uv add "cupy-cuda13x[ctk]"
```

## On Alliance clusters

We are providing a virtual training cluster for this course.

### Logging in

#### Step 1: get the info

During the course, we will give you 3 pieces of information:

- a link to a list of usernames,
- the hostname for our temporary training cluster,
- the password to access that cluster.

#### Step 2: claim a username

Add your first name or a pseudo next to a free username on the list to claim it.

[Your username is the name that was already on the list, NOT what you wrote next to it]{.emph} (which doesn't matter at all and only serves at signalling that this username is now taken).

Your username will look like `userxx`—`xx` being 2 digits—with **no space** and **no capital letter**.

#### Step 3: run the ssh command

::: {.panel-tabset}

##### Linux and macOS users

Linux users: &ensp;&ensp;open the terminal emulator of your choice. \
macOS users: &nbsp;&nbsp;open "Terminal".

Then type:

```{.bash}
ssh userxx@hostname
```

and press `Enter`.

:::{.note}

- Replace `userxx` by your username (e.g. `user09`).
- Replace `hostname` by the hostname we will give you the day of the workshop.

:::

When asked:

> Are you sure you want to continue connecting (yes/no/[fingerprint])?

Answer: "yes".

##### Windows users

We suggest using [the free version of MobaXterm](https://mobaxterm.mobatek.net/download-home-edition.html), a software that comes with a terminal emulator and a GUI interface for SSH sessions.

Here is how to install MobaXterm:

- download the "Installer edition" to your computer (green button to the right),
- unzip the file,
- double-click on the `.msi` file to launch the installation.

Here is how to log in with MobaXterm:

- open MobaXterm,
- click on [Session]{.codelike} (top left corner),
- click on [SSH]{.codelike} (top left corner),
- fill in the [Remote host *]{.codelike} box with the cluster hostname we gave you,
- tick the box [Specify username]{.codelike},
- fill in the box with the username you selected (e.g. `user09`),
- press [OK]{.codelike},
- when asked `Are you sure you want to continue connecting (yes/no/[fingerprint])?`, answer: "yes".

:::{.note}

[Here](https://mobaxterm.mobatek.net/demo.html) is a live demo.

:::

:::

#### Step 4: enter the password

When prompted, enter the password we gave you.

[You will not see anything happen as you type the password. This is normal and it is working, so keep on typing the password.]{.emph}

:::{.note}

This is called blind typing and is a Linux safety feature. It can be unsettling at first not to get any feed-back while typing as it really looks like it is not working. Type slowly and make sure not to make typos.

:::

Then press `Enter`.

#### Am I logged in?

To know whether or not you are logged in, look at your prompt: it should look like the following (with your actual username):

```
[userxx@login1 ~]$
```

#### Troubleshooting

Problems logging in are almost always due to typos. If you cannot log in, retry slowly, entering your password carefully.

#### How do I log out?

You can log out by pressing [Ctl+d]{.codelike}.

### Load module

Check available Python versions:

```{.bash}
module spider python
```

Check requirements to load Python 3.14:

```{.bash}
module spider python/3.14.2
```

Double-check that you already have `StdEnv/2023`:

```{.bash}
module list
```

Load Python 3.14:

```{.bash}
module load python/3.14.2
```

### Virtual environment

For this course, we have already installed `cupy` in a virtual environment everybody has access to. After the course, if you have an Alliance account, you can install CuPy following the instructions in the "On production clusters" tab.

:::{.panel-tabset}

### For this course

For today, all you need to do is activate the virtual environment we already created:

```{.bash}
source /project/def-sponsor00/cupy_env/bin/activate
```

### On production clusters

Create a virtual env:

```{.bash}
python -m venv ~/cupy_env
```

Activate it:

```{.bash}
source ~/cupy_env/bin/activate
```

Update `pip` from our wheel:

```{.bash}
python -m pip install --upgrade --no-index pip
```

Install `cupy` from our wheel:

```{.bash}
python -m pip install --no-index cupy
```

:::
