---
title: Notes about GPUs
description: GPUs on supercomputers, CUDA & kernels
title-block-banner: true
---

:::{.topdef}

Before launching into courses involving GPUs, these notes get you started on using GPUs on the Alliance clusters.

They also briefly introduce [CUDA](https://en.wikipedia.org/wiki/CUDA) and the various libraries that make it accessible in Python.

Finally, they go over the basic concepts of GPU programming so that you get a sense of what is happening under the hood and are in a better position to customize high-level code where possible.

:::

<br>
[[Start notes ➤](gpu_clusters.qmd)]{.topinline}

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "LearningResource",
  "name": "Notes about GPUs",
  "description": "Before launching into courses involving GPUs, these notes get you started on using GPUs on the Alliance clusters.\n\nThey also briefly introduce CUDA and how to access it in Python.\n\nFinally, they go over the basic concepts of GPU programming so that you get a sense of what is happening under the hood and are in a better position to customize high-level code where possible.",
  "url": "https://mint.westdri.ca/python/gpu_intro",
  "learningResourceType": "course",
  "inLanguage": "en",
  "license": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
  "provider": {
    "@type": "Organization",
    "name": "SFU Research Computing Group"
  },
  "keywords": "Python, GPU programming, CUDA",
  "author": {
    "@type": "Person",
    "name": "Marie-Hélène Burle"
  }
}
</script>
