---
title: Some words about Python
author: Marie-Hélène Burle
---

:::{.def}



:::

## A very popular language

### From a slowish start ...

Python was released in 1991 by Dutch programmer [Guido van Rossum](https://en.wikipedia.org/wiki/Guido_van_Rossum) to the "alt.sources" [Usenet](https://en.wikipedia.org/wiki/Usenet) group.

Its initial adoption was very gradual in niche communities.

In the 2000s, the release of Python 2.0, the birth of Python-based web frameworks, and the development of the first scientific libraries turned Python into a mainstream language.

The introduction of version 3.0 in 2008 fixed core design flaws in the language, but because many changes were backwards-incompatible, it also created rifts in the community and a slow and fragmented transition from the old mature version to the new one.

### ... to the most popular language

Since the mid-2010s, the language has seen an explosive growth thanks to the uptake by the data science community and the deep learning revolution (when Google released TensorFlow in 2015 and Facebook released PyTorch in 2016, they chose Python as their primary interface, making it, for better or for worse the *lingua franca* of AI and Machine Learning).

You can track its ever increasing advantage over other programming languages in indexes such as the [PYPL PopularitY of Programming Language index](https://pypl.github.io/PYPL.html) (based on the number of tutorial searches in Google) or the [TIOBE](https://www.tiobe.com/tiobe-index/) (calculated from the number of search engine results for queries containing the name of the language).

## Python pros and cons

 interpreted language with a simple, easily readable syntax, and a large collection of external packages.
