---
title: Control flow
aliases:
  - control_flow.html
author: Marie-Hélène Burle
---

:::{.def}

Control flow statements alter the linear execution of code, allowing for one or another section of code to be executed, or for one section of code to be executed multiple times.

:::

## Conditionals

Conditionals dictate the flow of information based on predicates (statements that return `True` or `False`).

:::{.example}

Example predicates:

:::

```{.python}
4 < 3
2 == 4
2 != 4
2 in range(5)
2 not in range(5)
3 <= 4 and 4 > 5
3 <= 4 and 4 > 5 and 3 != 2
3 <= 4 or 4 > 5
```

### If statements

In the simplest case, we have:

```{.python}
if <predicate>:
    <some action>
```

This translates to:

- If `<predicate>` evaluates to `True`, the body of the if statement gets evaluated (`<some action>` is run),
- If `<predicate>` evaluates to `False`, nothing happens.

:::{.example}

Examples:

:::

```{python}
x = 3
if x >= 0:
    print(x, 'is positive')
```

```{python}
x = -3
if x >= 0:
    print(x, 'is positive')
```

:::{.note}

Nothing gets returned since the predicate returned `False`.

:::

### If/else statements

Let's add an `else` statement so that our code also returns something when the predicate evaluates to `False`:

```{.python}
if <predicate>:
    <some action>
else:
    <some other action>
```

:::{.example}

Example:

:::

```{python}
x = -3
if x >= 0:
    print(x, 'is positive')
else:
    print(x, 'is negative')
```

### If/elif/else

We can make this even more complex with:

```{.python}
if <predicate1>:
    <some action>
elif <predicate2>:
    <some other action>    
else:
    <yet some other action>
```

:::{.example}

Example:

:::

```{python}
x = -3
if x > 0:
    print(x, 'is positive')
elif x < 0:
    print(x, 'is negative')
else:
    print(x, 'is zero')
```

:::{.exo}

:::{.yourturn}

Your turn:

:::

Test this if/elif/else loop with other values of `x` to make sure that it works as expected.

:::

## Loops

### For loops

For loops run a set of instructions for each element of an iterable.

An iterable is any Python object cable of returning the items it contains one at a time.

:::{.example}

Examples of iterables:

:::

```{.python}
range(5)
'a string is an iterable'
[2, 'word', 4.0]
```

For loops follow the syntax:

```{.python}
for <iterable>:
    <some action>
```

:::{.example}

Example:

:::

```{python}
for i in range(5):
    print(i)
```

:::{.exo}

:::{.yourturn}

Your turn:

:::

Remember that the indentation matters in Python.

What do you think that this will print? (try to come up with a hypothesis before running it).

```{.python}
for i in range(5):
    print(i)
print(i)
```

Now, what about?

```{.python}
for i in range(5):
    print(i)
    print(i)
```

:::

Strings are iterables too, so this works:

```{python}
for i in 'a string is an iterable':
    print(i)
```

To iterate over multiple iterables at the same time, a convenient option is to use the function `zip` which creates an iterator of tuples:

```{python}
for i, j in zip([1, 2, 3, 4], [3, 4, 5, 6]):
    print(i + j)
```

:::{.exo}

:::{.yourturn}

Your turn:

:::

Strings can be concatenated with the `+` sign in Python.

Example:

```{python}
print("This is" + " a test.")
```

Now, consider the 2 variables:

```{python}
names = ["Paul", "Eric", "Lucie"]
desserts = ["ice cream", "cakes", "pies"]
```

Create a loop that will print:

```{python}
#| echo: false

for name, dessert in zip(names, desserts):
    print(name + " likes " + dessert)
```

:::

### While loops

While loops run as long as a predicate remains true. They follow the syntax:

```{.python}
while <predicate>:
    <some action>
```

:::{.example}

Example:

:::

```{python}
i = 0
while i <= 10:
    print(i)
    i += 1
```

:::{.exo}

:::{.yourturn}

Your turn:

:::

What is the problem with the following loop:

```{.python}
i = 10
while i >= 0:
    print(i)
    i += 1
```

:::
