---
title: Resources
aliases:
  - resources.html
author: Marie-Hélène Burle
---

## Alliance wiki

- [Python page](https://docs.alliancecan.ca/wiki/Python)

There are many books on Python, several of which can be accessed online for free, either directly, or through your university.

## Books by O'Reilly

1. *Think Python*, 2nd Edition, by Allen B. Downey
2. *Python Pocket Reference*, 5th Edition, by Mark Lutz
3. *Introducing Python*, by Bill Lubanovic
4. *Python in a Nutshell*, 3rd Edition, by Alex Martelli, Anna Ravenscroft, and Steve Holden
5. *Learning Python*, 5th Edition, by Mark Lutz
6. *Python Cookbook*, 3rd Edition, by David Beazley and Brian K. Jones
7. *The Hitchhiker's Guide to Python*, by Kenneth Reitz and Tanya Schlusser
8. *Fluent Python*, by Luciano Ramalho
9. *High Performance Python*, by Micha Gorelick and Ian Ozsvald
10. *Web Scraping with Python*, by Ryan Mitchell
11. *Python Data Science Handbook*, by Jake VanderPlas
12. *Python for Data Analysis*, by Wes McKinney
13. *Foundations for Analytics with Python*, by Clinton W. Brownley
14. *Data Wrangling with Python*, by Jacquiline Kazil and Katharine Jarmul
15. *Data Visualization with Python and Javascript*, by Kyran Dale
16. *Natural Language Processing with Python*, by Steven Bird and Ewan Klein
17. *Thoughtful Machine Learning with Python*, by Matthew Kirk
18. *Python for Finance*, by Yves Hilpisch

## Books by No Starch Press

1. *Automate the Boring Stuff with Python*, by Al Sweigart
2. *Python Crash Course*, by Eric Matthews
3. *Python Playground*, by Mahesh Venkitachalam
4. *Doing Math with Python*, by Amit Saha
5. *Invent Your Own Computer Games with Python*, by Al Sweigart

## Other books

1. *Python Machine Learning*, by Sebastian Raschka
2. *Practical Programming: An Introduction to Computer Science Using Python 3*, by Paul Gries, Jennifer Campbell, and Jason Montojo
3. *Python for Dummies*, by Stef Maruch and Aahz Maruch
4. *Python Essential Reference*, 4th Edition, by David Beazley
5. *Head First Python*, by Paul Barry
6. *Python for Data Science for Dummies*, by John Paul Mueller and Luca Massaron
7. *Beginning Programming with Python for Dummies*, by John Paul Mueller
8. *Python for Everybody*, by Charles Severance
