---
title: Syntax
aliases:
  - basics.html
  - intro_intro.html
author: Marie-Hélène Burle
---

:::{.def}

First, let's cover some basics of the Python syntax.

:::

## Commands

Short commands are usually written one per line:

```{python}
a = 2.0
print(a)
```

but you can write multiple commands on the same line with the semi-colon separator:

```{python}
a = 2.0; print(a)
```

:::{.notenoit}

In a Python shell or when using Jupyter, you can omit the `print` function if you want to return a result directly (this is not true in [functions definitions](intro_functions)).

So the above could be run as:

```{python}
a = 2.0
a
```

and

```{python}
a = 2.0; a
```

Be careful though that if you are running a script (i.e. you write this code in a text file with a `.py` extension and execute it by running `python <your-script>.py` in the command line), nothing will get printed with this method and you have to explicitly use the `print` function.

:::

Some commands (e.g. function definitions, for loops, if else statements) span over multiple lines. The first line starts normally, but subsequent lines are indented to mark that they are part of the same command.

**This indentation—one tab or a series of spaces (often 4 spaces, but the number can be customized in many IDEs)—has a syntactic meaning in Python and is not just for human readability:**

```{python}
# Incorrect code
for i in [1, 2]:
print(i)
```

```{python}
# Correct code
for i in [1, 2]:
    print(i)
```

:::{.note}

IDEs and good text editors indent code automatically.

:::

## Comments

Comments (snippets of text for human consumption and ignored by the Python interpreter) are marked by the hashtag:

```{python}
# This is a full-line comment

print(a)         # This is an inline comment
```

:::{.note}

[PEP 8](https://peps.python.org/pep-0008/#maximum-line-length)—the style guide for Python code—suggests a maximum of 72 characters per line for comments. Try to keep comments to the point and spread them over multiple lines if they are too long.

:::

## Basic operations

```{python}
print(3 + 2)
```

```{python}
print(3.0 - 2.0)
```

```{python}
print(10 / 2)
```

:::{.note}

Notice how the result can be of a different type.

:::

Variables can be used in operations:

```{python}
a = 3
print(a + 2)
```

`a = a + 10` can be replaced by the more elegant:

```{python}
a += 10
print(a)
```

:::{.exo}

:::{.yourturn}

Your turn:

:::

Transform the following code:

```{.python}
a = a * 2
print(a)
```

by following these rules:

- turn the code as a one-liner,
- add a comment to it,
- replace the operation with a more elegant form.

:::

## Quotes

Pairs of single and double quotes are used to create strings.

:::{.note}

[PEP 8](https://peps.python.org/pep-0008/#maximum-line-length) does not recommend one style over the other. It does suggest however that once you have chosen a style, you stick to it to make scripts consistent.

:::

```{python}
"This is a string."
```

```{python}
type("This is a string.")
```

```{python}
'This is also a string.'
```

```{python}
type('This is also a string.')
```

Apostrophes and textual quotes interfere with Python quotes. In these cases, use the opposite style to avoid any problem:

```{python}
# This doesn't work
'This string isn't easy'
```

```{python}
# This is good
"This string isn't easy"
```

```{python}
# This doesn't work
"He said: "this is a problem.""
```

```{python}
# This is good
'He said: "this is a problem."'
```

Sometimes, neither option works and you have to escape some of the quotes with `\`:

```{python}
# This doesn't work
"He said: "this string isn't easy""
```

```{python}
# This doesn't work either
'He said: "this string isn't easy"'
```

```{python}
# You can use double quotes and escape double quotes in the string
"He said: \"this string isn't easy\""
```

```{python}
# Or you can use single quotes and escape single quotes in the string
'He said: "this string isn\'t easy"'
```
