---
title: Sentiment analysis
author: Marie-Hélène Burle
---

:::{.def}



:::

:::{.callout-note collapse="true"}

## Necessary code from previous sessions

Here is the necessary code from previous sessions, stripped to the minimum:

```{python}
# Load packages
import requests
import pymupdf
from textblob import TextBlob

# Download the data
url = "https://funnyengwish.wordpress.com/wp-content/uploads/2017/05/pratchett_terry_wyrd_sisters_-_royallib_ru.pdf"
response = requests.get(url)

# Extract data from pdf
data = response.content
doc = pymupdf.Document(stream=data)

# Create text from first pdf page
page1 = doc[0].get_text()

# Turn text into TextBlob
text = TextBlob(page1)
```

:::

```{python}
from textblob.sentiments import NaiveBayesAnalyzer
```

```{python}
review1 = "How have I never read Terry Pratchett before? He's like ... Shakespeare and Wodehouse and Monty Python all wrapped into one! A student gave me this book while we were studying Macbeth in class. Wyrd Sisters is a sort of parallel story, which manages to poke fun at the play, revere the play, make inside jokes about the play, and ... well, generally turn the play on its head. All the while, you, the reader, get to feel very smart and superior for getting all the jokes and allusions. And yet it manages to avoid being gimmicky. It really is a good story with good characters, too. This is no Life of Brian where the story itself matters less than the hilarity of the parody. Wyrd Sisters may draw a good deal of life from Macbeth, but its real liveliness comes from Pratchett's skilled characterizations of a regicidal Duke, his murderess Dutchess, their depressed Fool, and three very colorful witches. Oh, it's just genius. My only problem is figuring out what Pratchett novel to read next ... he's dauntingly prolific!"

r1 = TextBlob(review1)
r = TextBlob(review1, analyzer=NaiveBayesAnalyzer())

r1.sentiment
r.sentiment
```

```{python}
review2 = "A veritable smorgasbord of Shakespeare references sees the 6th Discworld novel come to life, dragging the two most prominent witches (Granny and Nanny) and their occult-leaning protege, Magrat, though thickets and thick-cities alike as they attempt to make sure fate happens. Maybe with a few encouraging prods along the way… A mixture of Macbeth and Hamlet with a little dollop of King Lear thrown in, along with many other Shakespeare nonsense that doesn’t stand out right way, Wyrd Sisters is one of PTerry’s very early masterpieces. His hands and head seem to meld together as one, where his imagination is not shackled by the human-only speed of his writing (or typing) or the darned debilitation of the English language.The plot simmers nicely, following and then not following the true path of how this kind of story goes. It’s so nice to see the Discworld countryside getting a deep look-in, and how well it contrasts with city-life, but also manages to co-exist very peacefully (as long as the city stays far away from the countryside, thank you). Whilst previously we visited vast open vistas on the Disc, these close-quarter scenes are even more brimful of life and curiosity and share yet another facet to not only PTerry’s imagination, but the world he has created. One of the best things about PTerry (and of any comedy at all) is that, whilst he does take the mickey out of Shakespeare and fantasy and all those things, he does it with such love and reverence that it shines through and makes the humour that much more poignant and, well, funny. (My previous review of this had me not enjoying it and I’m actually pretty baffled by that. I loved every single minute of this re-read and it’s curious how your tastes and feelings can change even after only a few years. I’ll leave the old review below just for the sake of it: Wyrd Sisters is the second of the Witch mini-series, in the ever popular Discworld series. Equal Rites was the first and we were introduced to one of the greatest characters of all-time: Granny Weatherwax. Wyrd Sisters brings two more witches-and mentions of many others-in to fray: Nanny Ogg, Granny's best friend, and Magrat Garlick, a new-wave witch who thinks jangling jewellery and occult symbols makes you a better witch. Adding two new witches alongside Granny just emphasises how cantankerous, stubborn and bloody brilliant she is. Even they can't deny that she's the best. She is tolerated most of the time, but there's always an underlying current of total respect, in the same way you respect your grandparents because they lived through the war, even if they do still say \"does anyone want to get a Chinky?\" The plot is Shakespearean-Macbeth in particular-and takes many plot points from that, as well as a lot of the quotes. It's a wonderful juxtaposition of Discworld nonsense and Shakespearean tragedy that is twisted with unique Pratchett humour. It is written much the same way all the early Discworld books were. Very well, hardly any technical faults and smatterings of Pratchett humour. Despite the wonderful Granny, the amusing Nanny and the Straightforward but naive Magrat, and my love for all the Discworld witches, I couldn't enjoy this as much as I wanted. It was funny in a tittering kind of way, and the plot was interesting, but it never quite held my attention. I never felt like I wanted to read it all the time, or try and finish reading it. It took me quite a while to get through it (for other reasons I won't go in to) but it never really held me enough to want it. Still a better love story than Twilight.)"

r2 = TextBlob(review2)
r = TextBlob(review2, analyzer=NaiveBayesAnalyzer())

r2.sentiment
r.sentiment
```

```{python}
review3 = "I struggled finishing the book as I lost interest."

r3 = TextBlob(review3)
r = TextBlob(review3, analyzer=NaiveBayesAnalyzer())

r3.sentiment
r.sentiment
```

```{python}
review4 = "I did not enjoy this book at all. Slow and tedious. It had some funny bits in the beginning, but I struggled to finish it."

r4 = TextBlob(review4)
r = TextBlob(review4, analyzer=NaiveBayesAnalyzer())

r4.sentiment
r.sentiment
```

```{python}
review5 = "It doesn't get much more boring than that. Zero improvement from Equal Rights, a complete snore-fest, poorly paced and with a clear lack of stakes and humour. I quit Discworld."

r5 = TextBlob(review5)
r = TextBlob(review5, analyzer=NaiveBayesAnalyzer())

r5.sentiment
r.sentiment
```

```{python}
review6 = "Hated this book. To be fair, not my style. Only read parts of it because it was assigned for a book club."

r6 = TextBlob(review6)
r = TextBlob(review6, analyzer=NaiveBayesAnalyzer())

r6.sentiment
r.sentiment
```

```{python}
review7 = "Dnf - boring"

r7 = TextBlob(review7)
r = TextBlob(review7, analyzer=NaiveBayesAnalyzer())

r7.sentiment
r.sentiment
```

## Rule-based vs data-based NLP

TextBlob (and [NLTK](https://www.nltk.org/) on which it is built) uses a rule-based or lexicon-based approach to NLP. This is an old technique that requires linguistic knowledge and is computationally basic. As we saw, it has many limitations.

The recent successes of [large language models (LLMs)](https://en.wikipedia.org/wiki/Large_language_model) have shown unequivocally that AI algorithms fed vast amounts of data do a much better job. They do not need to be programmed explicitly since learn by experience. They do however require a lot of computing power and data for training.

Such models are built from multiple complex [artificial neural networks](https://en.wikipedia.org/wiki/Neural_network_(machine_learning)) trained using libraries such as [PyTorch](https://pytorch.org/) or [JAX](https://jax.readthedocs.io/en/latest/index.html).

As [Frederick Jelinek](https://en.wikipedia.org/wiki/Frederick_Jelinek) is famously often quoted (although what he said was probably slightly different):

> Every time I fire a linguist, the performance of the speech recognizer goes up.

:::{.emph}

I will quickly demo how much better any of the LLMs out there does at this task.

:::
