---
title: Lazy evaluation
author: Marie-Hélène Burle
bibliography: python.bib
csl: ../diabetologia.csl
---

:::{.def}

When it comes to high-performance computing, one of the strengths of Polars is that it supports [lazy evaluation](https://en.wikipedia.org/wiki/Lazy_evaluation). Lazy evaluation instantly returns a future that can be used without waiting for the result of the computation. Moreover, when you run queries on a LazyFrame, Polars creates a graph and runs [optimizations](https://docs.pola.rs/user-guide/lazy/optimizations/) on it, very much the way compiled languages work.

If you want to speedup your code, **use lazy execution whenever possible.**

:::

## Reading in data to a LazyFrame

Ideally, you want to use the lazy API from the start, when you read in the data.

In the previous examples, we used [`polars.read_csv`](https://docs.pola.rs/api/python/stable/reference/api/polars.read_csv.html#polars.read_csv) to read our data. This returns a Polars DataFrame:

```{python}
import polars as pl

url = "https://cdn.jsdelivr.net/npm/vega-datasets/data/disasters.csv"

df = pl.read_csv(url)
type(df)
```

Instead, you can use [`polars.scan_csv`](https://docs.pola.rs/api/python/stable/reference/api/polars.scan_csv.html#polars.scan_csv) to create a LazyFrame:

```{python}
df_lazy = pl.scan_csv(url)
type(df_lazy)
```

:::{.note}

There are scan functions [for all the IO methods Polars offers](https://docs.pola.rs/user-guide/io/).

:::

## Converting to a LazyFrame

If you already have a DataFrame, you can create a LazyFrame from it with the [`polars.DataFrame.lazy`](https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.lazy.html#polars.DataFrame.lazy) method:

```{python}
df_lazy = df.lazy()
```

## Getting the results

To get results from a LazyFrame, you use [`polars.LazyFrame.collect`](https://docs.pola.rs/api/python/stable/reference/lazyframe/api/polars.LazyFrame.collect.html).

This won't work because a LazyFrame has no attribute `shape`:

```{python}
df_lazy.filter(pl.col("Year") == 2001).shape
```

You need to `collect` the result first:

```{python}
df_lazy.filter(pl.col("Year") == 2001).collect().shape
```

`collect` turns your LazyFrame into a DataFrame, but it only does so on the subset needed for your query:

```{python}
type(df_lazy.filter(pl.col("Year") == 2001).collect())
```

This allows you to work with data too big to fit in memory!

## Data too big to fit in memory

### Example of large dataset

Let's play with data from the [GBIF](https://www.gbif.org/) website (free and open access biodiversity database). The [Southern African Bird Atlas Project 2](https://www.gbif.org/dataset/906e6978-e292-4a8b-9c39-adf6bb0f3323) [@https://doi.org/10.15468/dl.gqwnm2] contains a CSV file of 12.3 GB.

The data contains 25,687,526 rows and 50 columns.

From that dataset, I want a list of species from the genus *Passer* (Old World sparrows).

### The importance of file format

Text-based formats (CSV, JSON) are not suitable for large files. [Apache Parquet](https://parquet.apache.org/) is a binary, machine-optimized, column-oriented file format with efficient encoding and compression and it is considered the industry-standard file format for large tabular data.

I converted the file to Parquet and copied it to our training cluster at `/project/def-sponsor00/data/sa_birds.parquet`.

Here is how much smaller the Parquet file is:

|  ||| File type ||| Size |
| -- | -- | -- | -- | -- | -- | -- |
| File downloaded from GBIF ||| Zipped CSV ||| 2.2 GB |
| Uncompressed file ||| CSV ||| 12.3 GB |
| Ideal file format ||| [Parquet]{.emph} ||| [0.5 GB]{.emph} |

In addition to being **15 times (!!) smaller**, it is **a lot faster to read & write**. With its native support for the columnar Apache Arrow format, Polars is ideal to work with Parquet files.

Now, while that file is very small, once you read it in Python, it cannot remain compressed and it will return to its full size of 12 GB. That is a lot more memory than we have on the training cluster (we only have 3600 MB in our current JupyterHub session!)

### What are your options?

When the data is too big to fit in memory, you can:

- read in data only for the columns you are interested in,
- read and process the file in chunks and try to combine the results,
- [use the Polars lazy API]{.emph}.

### Create a LazyFrame

You can create a LazyFrame (no impact on memory, LazyFrame returned instantly):

```{.python}
df_pl_lazy = pl.scan_parquet('/project/def-sponsor00/data/sa_birds.parquet')
```

```{python}
#| echo: false

df_pl_lazy = pl.scan_parquet('sa_birds.parquet')
```

Run a query on it (no impact on memory, LazyFrame returned instantly):

```{python}
passer_df_lazy = df_pl_lazy.filter(
    pl.col('genus') == 'Passer'
).select(pl.col('species')).unique()
```

### Collect the result

Now, you collect the result (this uses memory and takes time to compute) and turn the DataFrame into a Python list:

```{python}
passer_ls = passer_df_lazy.collect().get_column('species').to_list()

passer_ls
```

With this method, as long as the data itself fits on a drive and the queries don't return huge subsets of data, you can run queries on giant datasets such as the 3 TB [eBird dataset](https://www.gbif.org/dataset/4fa7b334-ce0d-4e88-aaae-2e0c138d049e) with a very small amount of RAM.

### RAM actually needed

I did a little experiment on a cluster: I ran the previous code on a single CPU core and gradually reduced the amount of memory asked from Slurm until I got an OOM error.

[I got the result with as little as 150 MB of memory.]{.emph}
