---
title: Resources
author: Marie-Hélène Burle
---

:::{.def}

Here is a list of resources for Polars.

:::

### Polars website

- [Official documentation](https://docs.pola.rs/)
- [Polars API](https://docs.pola.rs/py-polars/html/reference/)
- [GitHub repo](https://github.com/pola-rs/polars)

### Book

[Kevin Heavey](https://github.com/kevinheavey) wrote [Modern Polars](https://kevinheavey.github.io/modern-polars/) following the model of the [Modern Pandas](http://tomaugspurger.net/posts/modern-8-scaling/) book. This is a great resource, although getting a little outdated for the scaling chapter since Polars is evolving so fast.

### Integration with other tools

- **NumPy**: \
  See the [documentation](https://docs.pola.rs/user-guide/expressions/numpy/), the [from_numpy](https://docs.pola.rs/py-polars/html/reference/api/polars.from_numpy.html) and [to_numpy](https://docs.pola.rs/py-polars/html/reference/dataframe/api/polars.DataFrame.to_numpy.html) functions, the [development progress of this integration](https://github.com/pola-rs/polars/issues/14334), and [performance advice](https://kevinheavey.github.io/modern-polars/performance.html#numpy-can-make-polars-faster).

- **Parallel computing**: \
  With [Ray](https://github.com/ray-project/ray/issues/26131) thanks to [this setting](https://docs.ray.io/en/latest/data/api/data_context.html#ray.data.DataContext); with Spark, Dask, and Ray thanks to [fugue](https://github.com/fugue-project/fugue/).

- **GPUs**: \
  With the [cuDF library](https://github.com/rapidsai/cudf) from [RAPIDS](https://rapids.ai/) (in development).

- **SQL**: \
  With [DuckDB](https://github.com/duckdb/duckdb).

- **Plotting**: \
  [A great section of the documentation](https://docs.pola.rs/user-guide/misc/visualization/) shows how Polars integrates with many Python plotting frameworks.

- **Publishing**: \
  [The documentation](https://docs.pola.rs/user-guide/misc/styling/) shows how to publish beautiful tables from Polars DataFrames with [Great Tables](https://posit-dev.github.io/great-tables/articles/intro.html).
