---
title: DataFrames inspection
author: Marie-Hélène Burle
---

:::{.def}

Once we have a DataFrame, it is important to quickly get some basic information about it. In this section, we will see how to do so.

:::

Let's use the [la_riots dataset](https://github.com/vega/vega-datasets/blob/main/datapackage.md#la_riots), an open-source dataset on fatalities during the civil unrest in Los Angeles in April and May 1992, provided by the plotting library [Vega-Altair](https://altair-viz.github.io/). The dataset is hosted online as a CSV file.

You can read in a CSV file (local or from the Internet) with [`polars.read_csv`](https://docs.pola.rs/api/python/stable/reference/api/polars.read_csv.html):

```{python}
import polars as pl

df = pl.read_csv("https://cdn.jsdelivr.net/npm/vega-datasets/data/la-riots.csv")
print(df)
```

## Printing a few rows

Print first rows (5 by default):

```{python}
print(df.head())
```

```{python}
print(df.head(2))
```

Print last rows (5 by default):

```{python}
print(df.tail(2))
```

Print random rows (this is very useful as the head and tail of your DataFrame may not be representative of your data):

```{python}
import random

print(df.sample(4))
```

## Structure

Overview of the DataFrame and its structure:

```{python}
df.glimpse()
```

:::{.note}

This is similar to the `str()` function in R.

:::

The list of columns (variable names) can be accessed with the `columns` attribute:

```{python}
print(df.columns)
```

To print a list of the data types of each variable, you can use:

```{python}
print(df.dtypes)
```

But the printing of a Polars DataFrame already gives you this information (along with the shape).

The schema of a Polars DataFrame sets the names of the variables (columns) and their data types:

```{python}
df.schema
```

## Summary statistics

The statistics (mean, standard deviation, min, max, and quartiles) may not be meaningful, depending on your data, but it will always give you one useful piece of information: the number of missing values for each variable. Here, additionally, it is useful for the `age` variable:

```{python}
print(df.describe())
```
