---
title: DataFrames on steroids with Polars
author: Marie-Hélène Burle
---

:::{.def}

[Polars](https://pola.rs/) is a modern open source and *very fast* DataFrame framework for Python, Rust, JS, R, and Ruby.

In this webinar, I will demo Polars for Python and show how much faster it is compared to [pandas](https://pandas.pydata.org/) while remaining just as convenient.

:::

[Slides](wb_polars_slides.qmd){.btn .btn-outline-primary} [(Click and wait: this reveal.js presentation may take a little time to load.)]{.inlinenote}
<br><br>

{{< video https://www.youtube.com/embed/U5Gl_X6Z7Lk>}}

<br>
*[Slides content](wb_polars_content.qmd) for easier browsing.*

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "LearningResource",
  "name": "DataFrames on steroids with Polars",
  "description": "[Polars](https://pola.rs/) is a modern open source and *very fast* DataFrame framework for Python, Rust, JS, R, and Ruby.\n\nIn this webinar, I will demo Polars for Python and show how much faster it is compared to [pandas](https://pandas.pydata.org/) while remaining just as convenient.",
  "url": "https://mint.westdri.ca/python/wb_polars",
  "learningResourceType": [
    "slides",
	"video"
  ],
  "inLanguage": "en",
  "license": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
  "provider": {
    "@type": "Organization",
    "name": "SFU Research Computing Group"
  },
  "keywords": "Python, DataFrame, Polars",
  "author": {
    "@type": "Person",
    "name": "Marie-Hélène Burle"
  },
  "educationalLevel": "beginner"
}
</script>
