---
title: Introduction to high performance research computing in Julia
author: Marie-Hélène Burle
---

## Logging on to the cluster

Open a terminal emulator:

Windows users: &emsp;launch [MobaXTerm](https://mobaxterm.mobatek.net/). \
MacOS users: &emsp;&emsp;launch Terminal. \
Linux users: &emsp;&emsp;&ensp;&nbsp;launch xterm or the terminal emulator of your choice.

Then access the cluster through secure shell:

```{.bash}
$ ssh <username>@<hostname>    # enter password
```

## Accessing Julia

This is done with the [Lmod](https://github.com/TACC/Lmod) tool through the [module](https://docs.computecanada.ca/wiki/Utiliser_des_modules/en) command. You can find the full documentation [here](https://lmod.readthedocs.io/en/latest/010_user.html) and below are the subcommands you will need:

```{.bash}
# get help on the module command
$ module help
$ module --help
$ module -h

# list modules that are already loaded
$ module list

# see which modules are available for Julia
$ module spider julia

# see how to load julia 1.3
$ module spider julia/1.3.0

# load julia 1.3 with the required gcc module first
# (the order is important)
$ module load gcc/7.3.0 julia/1.3.0

# you can see that we now have Julia loaded
$ module list
```

## Copying files to the cluster

We will create a `julia_workshop` directory in `~/scratch`, then copy our julia script in it.

```{.bash}
$ mkdir ~/scratch/julia_job
```

Open a new terminal window and from your local terminal (make sure that you are not on the remote terminal by looking at the bash prompt) run:

```{.bash}
$ scp /local/path/to/sort.jl <username>@<hostname>:scratch/julia_job
$ scp /local/path/to/psort.jl <username>@<hostname>:scratch/julia_job

# enter password
```

## Job scripts

We will not run an interactive session with Julia on the cluster: we already have julia scripts ready to run. All we need to do is to write job scripts to submit to Slurm, the job scheduler used by the Alliance clusters.

We will create 2 scripts: one to run Julia on one core and one on as many cores as are available.

:::{.exo}

:::{.yourturn}

Your turn:

:::

How many processors are there on our training cluster?

:::

We can run Julia with multiple threads by running:

```{.bash}
$ JULIA_NUM_THREADS=2 julia
```

or:

```{.bash}
$ julia -t 2
```

Once in Julia, you can double check that Julia does indeed have access to 2 threads by running:

```{.julia}
Threads.nthreads()
```

Save your job scripts in the files `~/scratch/julia_job/job_julia1c.sh` and `job_julia2c.sh` for one and two cores respectively.

Here is what our single core Slurm script looks like:

```{.bash}
#!/bin/bash
#SBATCH --job-name=julia1c			# job name
#SBATCH --time=00:01:00				# max walltime 1 min
#SBATCH --cpus-per-task=1           # number of cores
#SBATCH --mem=1000					# max memory (default unit is megabytes)
#SBATCH --output=julia1c%j.out		# file name for the output
#SBATCH --error=julia1c%j.err		# file name for errors
# %j gets replaced with the job number

echo Running NON parallel script
julia sort.jl
echo Running parallel script on $SLURM_CPUS_PER_TASK core
julia -t $SLURM_CPUS_PER_TASK psort.jl
```

:::{.exo}

:::{.yourturn}

Your turn:

:::

Write the script for 2 cores.

:::

Now, we can submit our jobs to the cluster:

```{.bash}
$ cd ~/scratch/julia_job
$ sbatch job_julia1c.sh
$ sbatch job_julia2c.sh
```

And we can check their status with:

```{.bash}
$ sq	  # This is an Alliance alias for `squeue -u $USER $@`
```

:::{.note}

`PD` stands for pending \
`R` stands for running

:::
