---
title: Deep learning in Julia with Flux
subtitle: Example classifying the MNIST database
aliases:
  - flux.html
author: Marie-Hélène Burle
---

:::{.def}

This webinar, aimed at users with no experience in deep learning, is an introduction to the basic concepts of neural networks, followed by a simple example—the classic classification of the [MNIST database](http://yann.lecun.com/exdb/mnist/) of handwritten digits—using the Julia package [Flux](https://fluxml.ai/).

:::

{{< video https://www.youtube.com/embed/9nhVaJSuMF8 >}}

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "LearningResource",
  "name": "Machine learning in Julia with Flux",
  "description": "This webinar, aimed at users with no experience in deep learning, is an introduction to the basic concepts of neural networks, followed by a simple example—the classic classification of the [MNIST database](http://yann.lecun.com/exdb/mnist/) of handwritten digits—using the Julia package [Flux](https://fluxml.ai/).",
  "url": "https://mint.westdri.ca/julia/wb_flux",
  "learningResourceType": "video",
  "inLanguage": "en",
  "license": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
  "provider": {
    "@type": "Organization",
    "name": "SFU Research Computing Group"
  },
  "keywords": "Julia, deep learning, Flux, MNIST",
  "author": {
    "@type": "Person",
    "name": "Marie-Hélène Burle"
  },
  "educationalLevel": "beginner"
}
</script>
