---
title: First dab at Julia
aliases:
  - firstdab.html
author: Marie-Hélène Burle
---

:::{.def}

Julia is fast: [just-in-time (JIT) compilation](https://en.wikipedia.org/wiki/Just-in-time_compilation) and [multiple dispatch](https://en.wikipedia.org/wiki/Multiple_dispatch) bring efficiency to interactivity. People often say that using Julia feels like running R or python with a speed *almost* comparable to that of C.

But Julia also comes with parallel computing and multi-threading capabilities.

In this webinar, after a quickly presentation of some of the key features of Julia's beautifully concise syntax, I will dive into using Julia for HPC.

:::

{{< video https://www.youtube.com/embed/XQsxn8OUXGA >}}

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "LearningResource",
  "name": "First dab at Julia",
  "description": "Julia is fast: just-in-time (JIT) compilation and multiple dispatch bring efficiency to interactivity. People often say that using Julia feels like running R or python with a speed almost comparable to that of C.\n\nBut Julia also comes with parallel computing and multi-threading capabilities.\n\nIn this webinar, after a quickly presentation of some of the key features of Julia’s beautifully concise syntax, I will dive into using Julia for HPC.",
  "url": "https://mint.westdri.ca/julia/wb_firstdab",
  "learningResourceType": "video",
  "inLanguage": "en",
  "license": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
  "provider": {
    "@type": "Organization",
    "name": "SFU Research Computing Group"
  },
  "keywords": "Julia, JIT, multiple dispatch",
  "author": {
    "@type": "Person",
    "name": "Marie-Hélène Burle"
  },
  "educationalLevel": "beginner"
}
</script>
