---
title: Makie
aliases:
  - makie.html
subtitle: A data visualization ecosystem for Julia
author: Marie-Hélène Burle
---

:::{.def}

There are several popular data visualization libraries for the Julia programming language (e.g. [Plots](https://github.com/JuliaPlots/Plots.jl), [Gadfly](https://github.com/GiovineItalia/Gadfly.jl), [VegaLite](https://github.com/queryverse/VegaLite.jl), [Makie](https://github.com/MakieOrg/Makie.jl)). They vary in their precompilation time, time to first plot, layout capabilities, ability to handle 3D data, ease of use, and syntax style. In this landscape, Makie focuses on high performance, fancy layouts, and extensibility.

Makie comes with multiple backends. In this webinar, we will cover:

- [GLMakie](https://docs.makie.org/stable/documentation/backends/glmakie/) (ideal for interactive 2D and 3D plotting)
- [WGLMakie](https://docs.makie.org/stable/documentation/backends/wglmakie/) (an equivalent that runs within browsers)
- [CairoMakie](https://docs.makie.org/stable/documentation/backends/cairomakie/) (best for high-quality vector graphics)

We will also see how to run Makie in the Alliance clusters.

:::

[Slides](wb_makie_slides.qmd){.btn .btn-outline-primary} [(Click and wait: this reveal.js presentation is heavy and takes some time to load.)]{.inlinenote}
<br><br>

{{< video https://www.youtube.com/embed/nmAv2bW9Y2I >}}

<br>
*[Slides content](wb_makie_content.qmd) for easier browsing.*

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "LearningResource",
  "name": "Makie: a data visualization ecosystem for Julia",
  "description": "There are several popular data visualization libraries for the Julia programming language (e.g. Plots, Gadfly, VegaLite, Makie). They vary in their precompilation time, time to first plot, layout capabilities, ability to handle 3D data, ease of use, and syntax style. In this landscape, Makie focuses on high performance, fancy layouts, and extensibility.\n\nMakie comes with multiple backends. In this webinar, we will cover:\n\n- GLMakie (ideal for interactive 2D and 3D plotting)\n\n- WGLMakie (an equivalent that runs within browsers)\n\n- CairoMakie (best for high-quality vector graphics)\n\nWe will also see how to run Makie in the Alliance clusters.",
  "url": "https://mint.westdri.ca/julia/wb_makie",
  "learningResourceType": "slides, video",
  "inLanguage": "en",
  "license": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
  "provider": {
    "@type": "Organization",
    "name": "SFU Research Computing Group"
  },
  "keywords": "Julia, Makie, plotting",
  "author": {
    "@type": "Person",
    "name": "Marie-Hélène Burle"
  },
  "educationalLevel": "beginner"
}
</script>
