---
title: Resources
aliases:
  - /ai/jx/fl_resources
author: Marie-Hélène Burle
---

:::{.def}

Here is a list of resources to get started with deep learning using JAX.

:::

## JAX

- [JAX GitHub repo](https://github.com/jax-ml/jax)
- [Official documentation](https://docs.jax.dev/en/latest/)

#### Other resources

- [Awesome JAX](https://github.com/n2cholas/awesome-jax) list of resources
- [JAX AI Stack tutorials](https://docs.jaxstack.ai/en/latest/tutorials.html)
- [Projects using the JAX AI Stack](https://docs.jaxstack.ai/en/latest/examples.html)

#### Q&A

- [JAX GitHub Discussions](https://github.com/jax-ml/jax/discussions)
- [Stack Overflow [jax] tag](https://stackoverflow.com/questions/tagged/jax)

## Data and pre-trained models

### Data loaders

- [Hugging Face Datasets GitHub repo](https://github.com/huggingface/datasets)
- [Hugging Face Datasets documentation and tutorials](https://huggingface.co/docs/datasets/index)
- [Grain GitHub repo](https://github.com/google/grain)
- [Grain official documentation](https://google-grain.readthedocs.io/en/latest/)
- [TorchData GitHub repo](https://github.com/pytorch/data)
- [TensorFlow Datasets GitHub repo](https://github.com/tensorflow/datasets)
- [TensorFlow Datasets official documentation](https://www.tensorflow.org/datasets)

### Data augmentation

- [TorchVision official documentation](https://pytorch.org/vision/stable/index.html)

### Models and pre-trained weights

- [Hugging Face Transformers GitHub repo](https://github.com/huggingface/transformers)
- [Hugging Face Transformers official documentation](https://huggingface.co/docs/transformers/index)
- [TorchVision official documentation](https://pytorch.org/vision/stable/index.html)

## Flax

#### Official documentation

- [Flax GitHub repo](https://github.com/google/flax)
- [Official documentation](https://flax.readthedocs.io/en/latest/index.html)
- [Flax API](https://flax.readthedocs.io/en/latest/api_reference/index.html)

#### Other resources

- [Projects using Flax](https://flax.readthedocs.io/en/latest/examples/index.html)

#### Q&A

- [Flax GitHub Discussions](https://github.com/google/flax/discussions)
- [Stack Overflow [flax] tag](https://stackoverflow.com/questions/tagged/flax)

#### Alliance

The Alliance wiki has [a page on Flax](https://docs.alliancecan.ca/wiki/Flax).

## Optax

- [Optax GitHub repo](https://github.com/google-deepmind/optax)
- [Official documentation](https://optax.readthedocs.io/en/latest/)

#### Q&A

- [Optax GitHub Discussions](https://github.com/google-deepmind/optax/discussions)

## Orbax

- [Orbax GitHub repo](https://github.com/google/orbax)
- [Official documentation](https://orbax.readthedocs.io/en/latest/)

#### Q&A

- [Orbax GitHub Discussions](https://github.com/google/orbax/discussions)
