---
title: Installation and access
author: Marie-Hélène Burle
---

:::{.def}

In this section, we will make sure that you can access Emacs on our remote cluster.

:::

## Installing Emacs on your machine

To download and install Emacs on your computer, [simply follow the instructions in the official documentation](https://www.gnu.org/software/emacs/download.html).

:::{.info}

If you are on Linux, make sure to install the version of Emacs with native compilation and [jansson](https://github.com/akheron/jansson) support.

Native compilation was added as an option to Emacs 28 and greatly speeds up Emacs, in particular startup time. You will need `libgccjit` installed on your system.

[Jansson](https://github.com/akheron/jansson) support was added as an option to Emacs 27 and speeds up anything that involves JSON files and makes [lsp-mode](https://github.com/emacs-lsp/lsp-mode) and [eglot](https://github.com/joaotavora/eglot) in particular much faster.

If you don't use Linux, you will have to install `libgccjit` and the version of [jansson](https://github.com/akheron/jansson) for your OS (could be called `libjansson`), then compile Emacs from source with the `--with-native-compilation` and `--with-json` flags.

:::

## Accessing Emacs on the Alliance clusters

To ensure that we are all working in the same environment, for this course, we will use Emacs in a training cluster. This will also prepare you for using it on the Alliance clusters.

All you need to do is to log in to our cluster through SSH. Emacs is then available without having to load any module.

Below are the steps to log in the clusters.

### Step 1: get the info

During the course, we will give you 3 pieces of information:

- a link to a list of usernames,
- the hostname for our temporary training cluster,
- the password to access that cluster.

### Step 2: claim a username

Add your first name or a pseudo next to a free username on the list to claim it.

[Your username is the name that was already on the list, NOT what you wrote next to it]{.emph} (which doesn't matter at all and only serves at signalling that this username is now taken).

Your username will look like `userxx`—`xx` being 2 digits—with **no space** and **no capital letter**.

### Step 3: run the ssh command

::: {.panel-tabset}

#### Linux and macOS users

Linux users: &ensp;&ensp;open the terminal emulator of your choice. \
macOS users: &nbsp;&nbsp;open "Terminal".

Then type:

```{.bash}
ssh userxx@hostname
```

and press `Enter`.

:::{.note}

- Replace `userxx` by your username (e.g. `user09`).
- Replace `hostname` by the hostname we will give you the day of the workshop.

:::

When asked:

> Are you sure you want to continue connecting (yes/no/[fingerprint])?

Answer: "yes".

#### Windows users

We suggest using [the free version of MobaXterm](https://mobaxterm.mobatek.net/download-home-edition.html), a software that comes with a terminal emulator and a GUI interface for SSH sessions.

Here is how to install MobaXterm:

- download the "Installer edition" to your computer (green button to the right),
- unzip the file,
- double-click on the `.msi` file to launch the installation.

Here is how to log in with MobaXterm:

- open MobaXterm,
- click on [Session]{.codelike} (top left corner),
- click on [SSH]{.codelike} (top left corner),
- fill in the [Remote host *]{.codelike} box with the cluster hostname we gave you,
- tick the box [Specify username]{.codelike},
- fill in the box with the username you selected (e.g. `user09`),
- press [OK]{.codelike},
- when asked `Are you sure you want to continue connecting (yes/no/[fingerprint])?`, answer: "yes".

:::{.note}

[Here](https://mobaxterm.mobatek.net/demo.html) is a live demo.

:::

:::

### Step 4: enter the password

When prompted, enter the password we gave you.

[You will not see anything happen as you type the password. This is normal and it is working, so keep on typing the password.]{.emph}

:::{.note}

This is called blind typing and is a Linux safety feature. It can be unsettling at first not to get any feed-back while typing as it really looks like it is not working. Type slowly and make sure not to make typos.

:::

Then press `Enter`.

### Am I logged in?

To know whether or not you are logged in, look at your prompt: it should look like the following (with your actual username):

```
[userxx@login1 ~]$
```

### Troubleshooting

Problems logging in are almost always due to typos. If you cannot log in, retry slowly, entering your password carefully.

### How do I log out?

You can log out by pressing [Ctl+d]{.codelike}.
