---
title: Chatbots & AI agents in Emacs
author: Marie-Hélène Burle
---

:::{.def}

[Large language models (LLMs)](https://en.wikipedia.org/wiki/Large_language_model) have become powerful tools for coding, writing, and research. Not surprisingly, they are increasingly becoming integrated into many software, including text editors.

Emacs is no exception and a number of packages have recently been developed to access models smoothly and directly. Of particular notice:

- [copilot.el](https://github.com/copilot-emacs/copilot.el) brings [GitHub Copilot](https://github.com/features/copilot)'s code completion to Emacs,
- [copilot-chat.el](https://github.com/chep/copilot-chat.el) allows to chat, write tests, explain, document, review, correct, and optimize code with [GitHub Copilot](https://github.com/features/copilot) in Emacs,
- [gptel](https://github.com/karthink/gptel) allows access to LLMs from any buffer,
- [chatgpt-shell](https://github.com/xenodium/chatgpt-shell) provides an Emacs shell to chat with LLMs,
- [mcp.el](https://github.com/lizqwerscott/mcp.el) provides an Emacs client for [MCP](https://modelcontextprotocol.io/),
- [aidermacs](https://github.com/MatthewZMD/aidermacs) brings [aider](https://github.com/Aider-AI/aider) to Emacs (so forget about Cursor 🙂).

In this webinar, I will demo these packages and show you how to install them and set things up.

:::

[Slides](wb_llms_slides.qmd){.btn .btn-outline-primary} [(Click and wait: this reveal.js presentation may take a little time to load.)]{.inlinenote}

:::{.note}

Info on [mcp.el](https://github.com/lizqwerscott/mcp.el) and its integration with [gptel](https://github.com/karthink/gptel) and [copilot-chat.el](https://github.com/chep/copilot-chat.el) was added after the webinar, so it is in the slides, but not in the video.

:::

{{< video https://www.youtube.com/embed/qUcHbOANVns >}}

<br>
*[Slides content](wb_llms_content.qmd) for easier browsing.*

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "LearningResource",
  "name": "Chatbots & AI agents in Emacs",
  "dateCreated": "2025-10-07",
  "description": "[Large language models (LLMs)](https://en.wikipedia.org/wiki/Large_language_model) have become powerful tools for coding, writing, and research. Not surprisingly, they are increasingly becoming integrated into many software, including text editors.\n\nEmacs is no exception and a number of packages have recently been developed to access models smoothly and directly. Of particular notice:\n\n- [copilot.el](https://github.com/copilot-emacs/copilot.el) brings [GitHub Copilot](https://github.com/features/copilot)'s code completion to Emacs,\n\n- [copilot-chat.el](https://github.com/chep/copilot-chat.el) allows to chat, write tests, explain, document, review, correct, and optimize code with [GitHub Copilot](https://github.com/features/copilot) in Emacs,\n\n- [gptel](https://github.com/karthink/gptel) allows access to LLMs from any buffer,\n\n- [chatgpt-shell](https://github.com/xenodium/chatgpt-shell) provides an Emacs shell to chat with LLMs,\n\n- [mcp.el](https://github.com/lizqwerscott/mcp.el) provides an Emacs client for [MCP](https://modelcontextprotocol.io/),\n\n- [aidermacs](https://github.com/MatthewZMD/aidermacs) brings [aider](https://github.com/Aider-AI/aider) to Emacs (so forget about Cursor 🙂).\n\nIn this webinar, I will demo these packages and show you how to install them and set things up.",
  "url": "https://mint.westdri.ca/emacs/wb_llms",
  "learningResourceType": [
    "slides",
	"video"
  ],
  "inLanguage": "en",
  "license": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
  "provider": {
    "@type": "Organization",
    "name": "SFU Research Computing Group"
  },
  "keywords": "Emacs, text editor, AI agent, chatbot, MCP, LLM",
  "author": {
    "@type": "Person",
    "name": "Marie-Hélène Burle"
  },
  "educationalLevel": "beginner"
}
</script>
