---
title: Modern Emacs
subtitle: All those new tools that make Emacs better and faster
aliases:
  - wb_emacs_new_tools
author: Marie-Hélène Burle
---

:::{.def}

Emacs might have been created in the 70s, but development is alive and well:

- 10 years ago version 24 brought huge speedups with lexical binding.

- In 2022, version 28 added—among other things—just-in-time native compilation for elisp code for improved performance.

- Version 29 last year brought countless exciting new additions such as official [tree-sitter](https://tree-sitter.github.io/tree-sitter/) support and built-in [Eglot](https://github.com/joaotavora/eglot) and [use-package](https://github.com/jwiegley/use-package?tab=readme-ov-file#installing-use-package).

- In addition to Emacs itself, a profusion of modern packages have emerged over the past few years (e.g. the [vertico](https://github.com/minad/vertico)/[consult](https://github.com/minad/consult)/[orderless](https://github.com/oantolin/orderless)/[marginalia](https://github.com/minad/marginalia/)/[embark](https://github.com/oantolin/embark/) completion system; [corfu](https://github.com/minad/corfu) and [cape](https://github.com/minad/cape) for at point completion) bringing great speed and sleekness to the user experience.

**All these features are optional however and you need to learn about them to take advantage of their huge benefits.** This webinar intends to get you started making Emacs *really fast*.

:::

[Slides](wb_new_tools_slides.qmd){.btn .btn-outline-primary} [(Click and wait: this reveal.js presentation may take a little time to load.)]{.inlinenote}
<!-- <br><br> -->

{{< video https://www.youtube.com/embed/SOxlQ7ogplA >}}
