---
title: Full Python IDE in Emacs
author: Marie-Hélène Burle
---

:::{.def}

There are quite a few options to turn Emacs into a Python IDE.

[elpy](https://github.com/jorgenschaefer/elpy), now unmaintained, was a popular but heavy do-it-all package until [LSP (Language Server Protocol)](https://en.wikipedia.org/wiki/Language_Server_Protocol) became the norm.

[lsp-mode](https://github.com/emacs-lsp/lsp-mode/) (and the optional [lsp-ui](https://github.com/emacs-lsp/lsp-ui) for a more exciting interface) is a good option to get code completion, debugging, code navigation, and many helpers. To use it with Python, one can use [lsp-pyright](https://github.com/emacs-lsp/lsp-pyright) which brings the static type checkers for Python [pyright](https://github.com/microsoft/pyright) or [basedpyright](https://github.com/DetachHead/basedpyright).

Since version 29 however, Emacs comes with a built-in LSP client: [eglot](https://github.com/joaotavora/eglot) (Emacs Polyglot). And when it comes to Python type checkers and language servers, [ty](https://github.com/astral-sh/ty)—written in Rust—is currently by far the fastest. Good news: `ty` works very well with `eglot`.

You can add to this the modern and ultra fast Python linter and code formatter [ruff](https://github.com/astral-sh/ruff) (also written in Rust of course and much faster than [flake8](https://github.com/PyCQA/flake8), [black](https://github.com/psf/black), etc.). `ruff` also runs nicely in `eglot`.

Finally, on the REPL side, [py-vterm-interaction.el](https://github.com/vale981/py-vterm-interaction.el) runs your favourite Python shell (Python REPL, [ipython](https://github.com/ipython/ipython), [ptpython](https://github.com/prompt-toolkit/ptpython), or ptipython) in a much improved Emacs terminal emulator.

*In this webinar, I will demo running `ty` and `ruff` in `eglot` and give tips on how to set it all up with [flycheck](https://github.com/flycheck/flycheck) (nicely styled with [flyover](https://github.com/konrad1977/flyover)) and [eldoc-box](https://github.com/casouri/eldoc-box) to tame `eldoc`.*

:::

*Coming up in fall 2026.*
<!-- [Slides](wb_python_slides.qmd){.btn .btn-outline-primary} [(Click and wait: this reveal.js presentation may take a little time to load.)]{.inlinenote} -->
<!-- <br><br> -->

<!-- {{< video https://www.youtube.com/embed/ >}} -->
