---
title: So, you are stuck … now what?
subtitle: How to get help from the online community
author: Marie-Hélène Burle
---

:::{.def}

[Stack Overflow](https://stackoverflow.com/), [Stack Exchange](https://stackexchange.com/), [Discourse forums](https://www.discourse.org/), and other online platforms ... the internet is a treasure trove of online communities where you can find solutions to your coding problems. To have a positive experience and get the answers you need however, you have to know where to ask, how to ask, and when not to ask: if countless people are willing to give you their time for free, they usually expect that you do your part.

In this workshop, I will present key online sites, their functioning, and their culture; then I will go over the magic trick to get answers to your questions: knowing how to create minimum reproducible examples. I will not focus on any particular language as the principles (how to create a minimal dataset, how to deal with private data, how to create self-sufficient code, how to reproduce the problem, etc.) can apply to any language.

:::

[Slides](help_slides.qmd){.btn .btn-outline-primary} [(click and wait: my reveal.js presentations are heavy and take some time to load...)]{.inlinenote}
<br><br>

{{< video https://www.youtube.com/embed/mZjyf84Gbhg >}}

<!-- <br> -->
<!-- <script src="https://giscus.app/client.js" -->
<!-- data-repo="WestDRI/arc-training" -->
<!-- data-repo-id="R_kgDOIk69QA" -->
<!-- data-category-id="DIC_kwDOIk69QM4CS9oA" -->
<!-- data-mapping="url" -->
<!-- data-strict="1" -->
<!-- data-reactions-enabled="0" -->
<!-- data-emit-metadata="0" -->
<!-- data-input-position="bottom" -->
<!-- data-theme="preferred_color_scheme" -->
<!-- data-lang="en" -->
<!-- crossorigin="anonymous" -->
<!-- async> -->
<!-- </script> -->
