---
title: "A great Git UI: lazygit"
author: Marie-Hélène Burle
---

:::{.def}

While it is important to know how to use Git from the command line, this makes for an austere experience: a series of commands are required to gather information on the state of the working tree, see changes to files, or get a schematic of the commit history. Committing sections of files interactively and other operations are just awkward affairs. On the other hand, the many graphic interfaces for Git are often buggy, slow, and limiting.

One option is [to write exciting functions](../bash/wb_tools1.qmd) with tools such as [fzf](https://github.com/junegunn/fzf) to make things more friendly and visual. A simpler and more polished option is to use an already built user interface for Git that runs directly in the command line. [lazygit](https://github.com/jesseduffield/lazygit) is one such open source tool. After years of development, it is a mature, beautiful tool that allows to perform any Git operation in the command line in a convenient, fast, and visual fashion.

In this webinar, I will demo how I use lazygit in my daily workflow to run routine as well as more complex Git commands.

:::

[Slides](wb_lazygit_slides.qmd){.btn .btn-outline-primary} [(Click and wait: this reveal.js presentation may take a little time to load.)]{.inlinenote}
<br><br>

{{< video https://www.youtube.com/embed/1a2nrwfqNGI >}}

<br>
*[Slides content](wb_lazygit_content.qmd) for easier browsing.*

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "LearningResource",
  "name": "lazygit: a fast visual interface for Git",
  "description": "While it is important to know how to use Git from the command line, this makes for an austere experience: a series of commands are required to gather information on the state of the working tree, see changes to files, or get a schematic of the commit history. Committing sections of files interactively and other operations are just awkward affairs. On the other hand, the many graphic interfaces for Git are often buggy, slow, and limiting.\n\nOne option is [to write exciting functions](../bash/wb_tools1.qmd) with tools such as [fzf](https://github.com/junegunn/fzf) to make things more friendly and visual. A simpler and more polished option is to use an already built user interface for Git that runs directly in the command line. [lazygit](https://github.com/jesseduffield/lazygit) is one such open source tool. After years of development, it is a mature, beautiful tool that allows to perform any Git operation in the command line in a convenient, fast, and visual fashion.\n\nIn this webinar, I will demo how I use lazygit in my daily workflow to run routine as well as more complex Git commands.",
  "url": "https://mint.westdri.ca/tools/wb_lazygit",
  "learningResourceType": [
    "slides",
	"video"
  ],
  "inLanguage": "en",
  "license": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
  "provider": {
    "@type": "Organization",
    "name": "SFU Research Computing Group"
  },
  "keywords": "lazygit, Git, version control, TUI, UI, command line",
  "author": {
    "@type": "Person",
    "name": "Marie-Hélène Burle"
  },
  "educationalLevel": "intermediate"
}
</script>
