---
title: "The new R Markdown:"
aliases:
  - quarto_webinar.html
subtitle: Authoring dynamic scientific documents with Quarto
author: Marie-Hélène Burle
---

:::{.def}

This webinar will show you how to easily create beautiful publications (webpages, pdf, websites, presentations, books…)—complete with formatted text, dynamic code and figures with Quarto.

[Quarto](https://quarto.org/) is the successor to [R Markdown](https://rmarkdown.rstudio.com/). By combining the powers of Jupyter or knitr with Pandoc, it works with R, but also with Python and Julia code blocks and it adds new functionalities to the old tool.

:::

[Slides](wb_quarto_slides.qmd){.btn .btn-outline-primary} [(Click and wait: this reveal.js presentation may take a little time to load.)]{.inlinenote}
<br><br>

{{< video https://www.youtube.com/embed/0NtyFuA_yNU >}}

<br>
*[Slides content](wb_quarto_content.qmd) for easier browsing.*

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "LearningResource",
  "name": "Quarto: the new R Markdown",
  "description": "This webinar will show you how to easily create beautiful publications (webpages, pdf, websites, presentations, books…)—complete with formatted text, dynamic code and figures with Quarto.\n\nQuarto is the successor to R Markdown. By combining the powers of Jupyter or knitr with Pandoc, it works with R, but also with Python and Julia code blocks and it adds new functionalities to the old tool.",
  "url": "https://mint.westdri.ca/tools/wb_quarto",
  "learningResourceType": "slides, video",
  "inLanguage": "en",
  "license": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
  "provider": {
    "@type": "Organization",
    "name": "SFU Research Computing Group",
  },
  "keywords": "Quarto, markup, R Markdown, publishing",
  "author": {
    "@type": "Person",
    "name": "Marie-Hélène Burle"
  }
}
</script>
