---
title: Hardening your system in the age of AI
author: Marie-Hélène Burle
---

:::{.def}

Autonomous AI will make the coming few years interesting when it comes to cybersecurity ... whether we are talking about malicious bots unleashed on the web or about your own agents roaming your system!

It is time to think about hardening your machine and adopting better practices.

In this webinar, I will:

- go over basic safety rules,
- explain key concepts of filesystem permissions, secure shells (key pairs, SSH agents), and public key cryptography (key structure, OpenPGP, GPG agents),
- and finally demo several open source tools for data encryption and password management (e.g. Sequoia-PGP, KeePassXC, gocryptfs).

:::

<!-- [Slides](wb_security_slides.qmd){.btn .btn-outline-primary} [(Click and wait: this reveal.js presentation may take a little time to load.)]{.inlinenote} -->
<!-- <br><br> -->

<!-- {{< video https://www.youtube.com/embed/ >}} -->

<!-- <br> -->
<!-- *[Slides content](wb_security_content.qmd) for easier browsing.* -->

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "LearningResource",
  "name": "Hardening your system in the age of AI",
  "dateCreated": "2026-10-13",
  "description": "",
  "url": "https://mint.westdri.ca/tools/wb_security",
  "learningResourceType": [
    "slides",
	"video"
  ],
  "inLanguage": "en",
  "license": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
  "provider": {
    "@type": "Organization",
    "name": "SFU Research Computing Group"
  },
  "keywords": "cybersecurity, SSH, OpenPGP, encryption",
  "author": {
    "@type": "Person",
    "name": "Marie-Hélène Burle"
  },
  "educationalLevel": "beginner"
}
</script>
