---
title: Fun tools to simplify your life in the shell
aliases:
  - tools1.html
author: Marie-Hélène Burle
---

:::{.def}

Working in the command-line has many advantages and it is often necessary, but can it be fun?

In this webinar, aimed at any command-line user, I intend to demonstrate that yes, it can! by introducing three free and open source utilities which make navigating your system and your outputs a lot easier:

- [fzf](https://github.com/junegunn/fzf) is a simple, yet extremely powerful interactive fuzzy finder allowing for incremental completion and narrowing selection of any command line output. I will show you how to build simple shell functions which harvest its power to instantly refresh your memory on your custom keybindings or aliases, navigate your command history, find and kill processes, and explore and checkout your git commits. After this, you will be able to use fzf for any number of other applications in your work in the command-line.

- [autojump](https://github.com/wting/autojump) lets you jump anywhere you want in your directories in just a few keystrokes (no more of this painful navigation writing down long paths).

- With the [ranger](https://github.com/ranger/ranger) file manager, you can browse (with preview!), open, copy, move, delete, etc. your files and directories in a friendly way from the command line. Added bonus: you can use fzf and autojump within ranger!

***Warning: too much fun in the command-line can lead to addiction and geek behaviours. Use in moderation.***

:::

{{< video https://www.youtube.com/embed/BFKT7aj-i80 >}}

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "LearningResource",
  "name": "Fun tools to simplify your life in the shell",
  "dateCreated": "2020-02-19",
  "description": "Working in the command-line has many advantages and it is often necessary, but can it be fun?\n\nIn this webinar, aimed at any command-line user, I intend to demonstrate that yes, it can! by introducing three free and open source utilities which make navigating your system and your outputs a lot easier:\n\n- [fzf](https://github.com/junegunn/fzf) is a simple, yet extremely powerful interactive fuzzy finder allowing for incremental completion and narrowing selection of any command line output. I will show you how to build simple shell functions which harvest its power to instantly refresh your memory on your custom keybindings or aliases, navigate your command history, find and kill processes, and explore and checkout your git commits. After this, you will be able to use fzf for any number of other applications in your work in the command-line.\n\n- [autojump](https://github.com/wting/autojump) lets you jump anywhere you want in your directories in just a few keystrokes (no more of this painful navigation writing down long paths).\n\n- With the [ranger](https://github.com/ranger/ranger) file manager, you can browse (with preview!), open, copy, move, delete, etc. your files and directories in a friendly way from the command line. Added bonus: you can use fzf and autojump within ranger!\n\n***Warning: too much fun in the command-line can lead to addiction and geek behaviours. Use in moderation.***",
  "url": "https://mint.westdri.ca/tools/wb_tools1",
  "learningResourceType": "video",
  "inLanguage": "en",
  "license": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
  "provider": {
    "@type": "Organization",
    "name": "SFU Research Computing Group"
  },
  "keywords": "fzf, autojump, ranger, TUI, CLI, command line, Bash, Zsh, Unix shell",
  "author": {
    "@type": "Person",
    "name": "Marie-Hélène Burle"
  },
  "educationalLevel": "intermediate"
}
</script>
