---
title: A new markup typesetting system
frontpic: img/logo_typst_full.png
frontpicwidth: 35%
author: Marie-Hélène Burle
date: 2026-04-21
date-format: long
execute:
  freeze: auto
  cache: true
  error: true
  echo: true
format:
  revealjs:
    <!-- embed-resources: true -->
    theme: [default, ../revealjsserif.scss]
    logo: /img/favicon_sfudrac.png
    highlight-style: vim-dark
    code-line-numbers: false
    template-partials:
      - ../title-slide.html
    pointer:
      color: "#b5111b"
      pointerSize: 32
    link-external-newwindow: true
    footer: <a href="wb_typst.qmd"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="rgb(29,175,119)" class="bi bi-arrow-90deg-up" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M4.854 1.146a.5.5 0 0 0-.708 0l-4 4a.5.5 0 1 0 .708.708L4 2.707V12.5A2.5 2.5 0 0 0 6.5 15h8a.5.5 0 0 0 0-1h-8A1.5 1.5 0 0 1 5 12.5V2.707l3.146 3.147a.5.5 0 1 0 .708-.708l-4-4z"/></svg>&nbsp;Back to webinar page</a>
    auto-stretch: false
revealjs-plugins:
  - pointer
---

## Markup languages {.center}

Markup languages define the formatting of documents. They are rendered by software

:::{.example}

Examples of markup languages:

:::

- [HTML](https://en.wikipedia.org/wiki/HTML) (HyperText Markup Language) is a declarative, static markup language for creating web documents
- [TeX](https://en.wikipedia.org/wiki/TeX) is a procedural, Turing complete markup language for typesetting PDF documents ([LaTeX](https://en.wikipedia.org/wiki/LaTeX) is a set of macros built on it, making it easier to use)
- [Markdown](https://en.wikipedia.org/wiki/Markdown) is a more recent, simple, easy to read and write markup language that can be used for both web and PDF. It is more limited than either HTML or LaTeX, but it can incorporate raw HTML and LaTeX code

## Example LaTeX {.center}

```{.latex}
\documentclass{article}
\title{My title}
\author{My name}
\usepackage{datetime}
\newdate{date}{24}{11}{2022}
\date{\displaydate{date}}
\begin{document}
 \maketitle
 \section{First section}
 Some text in the first section.
\end{document}
```

## Example HTML {.center}

```{.html}
<!DOCTYPE html>
<html lang="en-US">
  <head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width" />
	<title>My title</title>
	<address class="author">My name</address>
	<input type="date" value="2022-11-24" />
  </head>
  <h1>First section</h1>
  <body>
	Some text in the first section.
  </body>
</html>
```

## Typst {.center}

Typst is a new markup language for typesetting documents

Exports to PDF, HTML, PNG, SVG

Mostly a LaTeX replacement

Allows for live preview thanks to its [extremely fast open-source cross-platform compiler written in Rust]{.emph} and to [incremental compilation]{.emph} (LaTeX that recompiles whole documents)

It is much closer to a programming language than TeX (modules, functions, variables, arrays)

Supported by [pandoc](https://github.com/jgm/pandoc)

<!-- [Cool post](https://jbirnick.net/posts/typesetting-comparison/) by Johann Birnick -->

<!-- [A good comparison](https://www.underleaf.ai/blog/typst-vs-latex) by the popular [Underleaf AI](https://www.underleaf.ai/) company (which has no business interest in promoting Typst!) -->

[Informative and actionable error messages!]{.emph}

## Equivalent of previous example in Typst {.center}

```{.typ}
#set document(
	title: "My title",
	author: "My name",
	date: datetime(year: 2022, month: 11, day: 24)
)

= First section

Some text in the first section.
```

## How to use Typst {.center}

Typst comes with [a web app](https://typst.app/). It requires sign in and provides previews, syntax highlighting, and autocompletion. I won't use it though and will instead use the [open-source CLI utility](https://github.com/typst/typst)

[Download the binaries or install it via your package manager or via Rust's `cargo`](https://github.com/typst/typst#installation)

Write text files with `.typ` extension in your favourite text editor and run either of:

```{.bash}
typst compile <your_file.typ>  # creates PDF
```

```{.bash}
typst watch <your_file.typ>	   # also recompiles PDF on changes
```

Check `typst help`and `typst <command> help` (e.g. `typst watch help`) for options

## Limitations {.center}

:::{.emph}

One current limitation is that few journals accept Typst documents

:::

Package ecosystem smaller than for LaTeX

Increasing integration with [MathML](https://en.wikipedia.org/wiki/MathML) but no direct equivalent to [MathJax](https://github.com/mathjax/MathJax) that allows to use Typst math as is for HTML. [This thread](https://forum.typst.app/t/does-mathjax-katex-like-math-typesetting-for-the-web-but-with-typst-math-syntax-exist/5557/6) has suggestions and regular updates on this

## Markup syntax {.center}

::::{.columns}

:::{.column width="49%"}

```{.typ}
= Header level 1
== Header level 2
=== Header level 3
_italic_, *bold*, `monospace`

// Full-line comment
Some text  // End of line comment

Adding a \
line break
```

:::

:::{.column width="2%"}
:::

:::{.column width="49%"}

```{.typ}
Inline equation: $e^(-2 pi i x xi)$

Block equation: $ e^(-2 pi i x xi) $

+ Numbered list item 1
+ Numbered list item 2
	- Nested unnumbered item
	- Nested unnumbered item
		- More nesting unnumbered
		- More nesting unnumbered
```

:::

::::

## Turing complete<br>with programming language syntax {.center}



## Automatic PDF refresh {.center}

If you use a PDF viewer that does not automatically refresh on changes, you can force it to do so

Here is an example Bash function that opens a file with `mupdf` (replace by the viewer of your choice) and automatically refreshes:

```{.bash}
livepdf () {
	mupdf "$1" &
	echo "$1" | entr -p pkill -HUP mupdf
}
```

Use it with:

```{.bash}
livepdf your_pdf.pdf
```

## Templates {.center}



## Presentations packages {.center}

[polylux](https://github.com/polylux-typ/polylux)

[touying](https://github.com/touying-typ/touying)

## Resources {.center}

[Official documentation](https://typst.app/docs/) \
[Templates](https://typst.app/universe/search/?kind=templates) \
[Packages](https://typst.app/universe/search/?kind=packages) \
[Discourse forum](https://forum.typst.app/) \
[Discord](https://discord.com/invite/typst-1054443721975922748) \
[Awesome-typst repo](https://github.com/qjcg/awesome-typst) \
Usage in Emacs: [typst-ts-mode](https://codeberg.org/meow_king/typst-ts-mode); preview with [typst-preview.el](https://github.com/havarddj/typst-preview.el) or [tip](https://git.sr.ht/~mafty/tip) \
[Tinymist](https://github.com/Myriad-Dreamin/tinymist): integrated language service for Typst
