---
title: Typst
subtitle: A new markup typesetting system
author: Marie-Hélène Burle
---

:::{.def}

[Typst](https://github.com/typst/typst) is a new open-source markup typesetting system which aims to be as powerful as [LaTeX](https://en.wikipedia.org/wiki/LaTeX) with a much faster compiler, a much simpler installation, much fewer moving parts, and a much easier learning curve.

The straightforward and unobtrusive syntax allows for math formulae, tables, graphs, bibliography management, and presentation mode.

Scripting (conditionals, loops, functions, and methods) as well as data loading produce reactive documents with automatically updated tables or plots.

Finally, Typst [integrates perfectly with Quarto](https://quarto.org/docs/reference/formats/typst.html).

While this tool is new and still in active development, it already has close to 50k stars on GitHub and a contributors pool of close to 400 people, making it a very popular tool embraced by the scientific community.

If you are using a word processing program (e.g. MS Word) to write your thesis, articles, and other scientific documents, Typst can easily allow you to switch to a text-based approach with all the benefits that this entails (version control with Git, use of a powerful text editor, embedding code in documents, etc.).

:::

*Coming up in spring 2026.*
<!-- [Slides](wb_typst_slides.qmd){.btn .btn-outline-primary} [(Click and wait: this reveal.js presentation may take a little time to load.)]{.inlinenote} -->
<!-- <br><br> -->

<!-- {{< video https://www.youtube.com/embed/ >}} -->
