---
title: Modern shell utilities
author: Marie-Hélène Burle
---

:::{.def}

In recent years, a number of open-source utilities for the Unix shell have emerged. Some are meant as replacements for classic tools with improved performance, better defaults, or nicer-looking outputs; others add novel functionality. Several of them were recently installed on the Alliance clusters.

In this webinar I will cover a selection of tools that are very popular, well-maintained, and that have served me well in my daily workflows:

- `ls` in colours: [eza](https://github.com/eza-community/eza),
- smart `cd`: [zoxide](https://github.com/ajeetdsouza/zoxide),
- a `cat` with wings: [bat](https://github.com/sharkdp/bat),
- RIP `grep`: [ripgrep](https://github.com/BurntSushi/ripgrep),
- faster `find`: [fd](https://github.com/sharkdp/fd),
- fuzzy finder: [fzf](https://github.com/junegunn/fzf),
- file system TUIs.

I will also talk about three useful [Zsh](https://www.zsh.org/) plugins:

- [a syntax highlighter](https://github.com/zsh-users/zsh-syntax-highlighting),
- [autosuggestions](https://github.com/zsh-users/zsh-autosuggestions),
- [an improved history searcher](https://github.com/zsh-users/zsh-history-substring-search).

For each tool/plugin, I will talk about installation on a personal computer and on the Alliance clusters and I will give live demos.

:::

[Slides](wb_tools3_slides.qmd){.btn .btn-outline-primary} [(Click and wait: this reveal.js presentation may take a little time to load.)]{.inlinenote}
<br><br>

{{< video https://www.youtube.com/embed/Vqg6B5fVkD0 >}}

<br>
*[Slides content](wb_tools3_content.qmd) for easier browsing.*

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "LearningResource",
  "name": "Modern shell utilities",
  "description": "In recent years, a number of open-source utilities for the Unix shell have emerged. Some are meant as replacements for classic tools with improved performance, better defaults, or nicer-looking outputs; others add novel functionality. Several of them were recently installed on the Alliance clusters.\n\nIn this webinar I will cover a selection of tools that are very popular, well-maintained, and that have served me well in my daily workflows:\n\n- `ls` in colours: [eza](https://github.com/eza-community/eza),\n\n- smart `cd`: [zoxide](https://github.com/ajeetdsouza/zoxide),\n\n- a `cat` with wings: [bat](https://github.com/sharkdp/bat),\n\n- RIP `grep`: [ripgrep](https://github.com/BurntSushi/ripgrep),\n\n- faster `find`: [fd](https://github.com/sharkdp/fd),\n\n- fuzzy finder: [fzf](https://github.com/junegunn/fzf),\n\n- file system TUIs.\n\nI will also talk about three useful [Zsh](https://www.zsh.org/) plugins:\n\n- [a syntax highlighter](https://github.com/zsh-users/zsh-syntax-highlighting),\n\n- [autosuggestions](https://github.com/zsh-users/zsh-autosuggestions),\n\n- [an improved history searcher](https://github.com/zsh-users/zsh-history-substring-search).\n\nFor each tool/plugin, I will talk about installation on a personal computer and on the Alliance clusters and I will give live demos.",
  "url": "https://mint.westdri.ca/tools/wb_tools3",
  "learningResourceType": [
    "slides",
	"video"
  ],
  "inLanguage": "en",
  "license": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
  "provider": {
    "@type": "Organization",
    "name": "SFU Research Computing Group"
  },
  "keywords": "ls, eza, cd, zoxide, cat, bat, grep, ripgrep, rg, find, fd, fzf, TUI, ranger, nnn, yazi, Bash, Zsh, Unix shell",
  "author": {
    "@type": "Person",
    "name": "Marie-Hélène Burle"
  },
  "educationalLevel": "intermediate"
}
</script>
