---
title: Introduction
author: Marie-Hélène Burle
---

```{r}

```

:::{.def}

This section explains what Bash is, why it is useful to know how to use it, and how we are going to run it in this workshop.

:::

## Unix shells

Bash is a Unix shell. What are they?

Unix shells are command line interpreters: the user enters commands as text—interactively in the command line or in scripts—and the shell passes them to the operating system.

### Types of Unix shells

[Bash (<em>Bourne Again SHell</em>)](https://en.wikipedia.org/wiki/Bash_(Unix_shell))—released in 1989—is part of the GNU Project and is the default Unix shell on many systems (although MacOS recently changed its default to [Zsh](https://en.wikipedia.org/wiki/Z_shell)).

Prior to Bash, the default was the [Bourne shell (sh)](https://en.wikipedia.org/wiki/Bourne_shell).

A new and popular shell (backward compatible with Bash) is [Zsh](https://en.wikipedia.org/wiki/Z_shell). It extends Bash's capabilities.

Another shell in the same family is the [KornShell (ksh)](https://en.wikipedia.org/wiki/KornShell).

All these shells are quite similar. The [C shell (csh)](https://en.wikipedia.org/wiki/C_shell) however was modeled on the C programming language.

Bash is the most common shell and the one which makes the most sense to learn as a first Unix shell. It is also the one used by default on the Alliance clusters.

## Why use a shell?

While automating GUI operations is really difficult, it is easy to rerun a script (a file with a number of commands). Unix shells thus allow the creation of reproducible workflows and the automation of repetitive tasks.

They are powerful to launch tools, modify files, search text, or combine commands.

They also allow to work on remote machines and HPC systems.

## Running Bash

Since Bash is a Unix shell, you need a Unix or Unix-like operating system. This means that people on Linux or MacOS can use Bash on their machine, but it is more problematic for Windows users. On Windows, there are various options:

- Using [Windows Subsystem for Linux (WSL)](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux)
- Using a Bash emulator (e.g. [Git BASH](https://gitforwindows.org/)), but those only have a subset of the usual Bash utilities
- Using a Unix-like environment for Windows (e.g. [Cygwin](https://en.wikipedia.org/wiki/Cygwin))
- Using a Unix [Virtual machine](https://en.wikipedia.org/wiki/Virtual_machine)

### How we will use Bash today

Today, we will connect to a remote HPC system via SSH (secure shell). HPC systems always run Linux.

Those on Linux or MacOS can alternatively use Bash directly on their machine.

:::{.note}

On MacOS, the default is now [Zsh](https://en.wikipedia.org/wiki/Z_shell) (you can see that by typing `echo $SHELL` in Terminal), but Zsh is fully compatible with Bash commands, so it is totally fine to use it instead. If you really want to use Bash, simply launch it by typing in Terminal: `bash`.

:::

## Connecting to a remote HPC system via SSH

### Usernames and password

We will give you a link to an etherpad during the workshop. Add your name next to a free username to claim it.

We will also give you the password for our training cluster. When prompted, enter it.

:::{.note}

Note that you will not see any character as you type the password: this is called blind typing and is a Linux safety feature. Type slowly and make sure not to make typos. It can be unsettling at first not to get any feed-back while typing.

:::

### Linux and MacOS users

Linux users: open the terminal emulator of your choice.\
MacOS users: open "Terminal".

Then type:

```{.bash}
ssh userxx@hostname
```

:::{.note}

- Replace `userxx` by your username (e.g. `user09`)
- Replace `hostname` by the hostname we will give you the day of the workshop.

:::

### Windows users

We suggest using [the free version of MobaXterm.](https://mobaxterm.mobatek.net/download.html)

MobaXterm comes with a terminal emulator and a GUI interface for SSH sessions.

Open MobaXterm, click on "Session", then "SSH", and fill in the Remote host name and your username. [Here](https://mobaxterm.mobatek.net/demo.html) is a live demo.
