---
title: Resources for HPC in R
aliases:
  - resources_hpc.html
author: Marie-Hélène Burle
---

:::{.def}

This section contains resources specific to high-performance R. For introductory/general R resources, see [this page](https://mint.westdri.ca/r/resources.html) instead.

:::

### CRAN Task Views

:::{.hnote}

[CRAN Task Views](https://cran.r-project.org/web/views/) give information on packages relevant to certain topics.

:::

- The [High-Performance and Parallel Computing with R](https://cran.r-project.org/web/views/HighPerformanceComputing.html) task view lists a lot of packages useful for HPC in R.

### Running R on the Alliance clusters

:::{.hnote}

The [Alliance wiki](https://docs.alliancecan.ca/wiki/Technical_documentation) contains a lot of documentation on how to run code on the Alliance clusters. Here are pages particularly relevant for HPC in R:

:::

- [Getting started](https://docs.alliancecan.ca/wiki/Getting_started): how to get started using the Alliance supercomputers.
- [Running jobs](https://docs.alliancecan.ca/wiki/Running_jobs): how to launch Slurm jobs.
- [Running R](https://docs.alliancecan.ca/wiki/R): how to use R on the Alliance supercomputers.
- [Technical support](https://docs.alliancecan.ca/wiki/Technical_support): what to do if you are stuck running code on one of the Alliance clusters.

If you are still having issues after reading the documentation, you can open a ticket by emailing <support@tech.alliancecan.ca>.

### Online books

- [Advanced R](https://adv-r.hadley.nz/)
- [Efficient R programming](https://csgillespie.github.io/efficientR/)

### Rcpp

- [Documentation and examples](http://dirk.eddelbuettel.com/code/rcpp.html)
