---
title: Data manipulation
author: Marie-Hélène Burle
---

:::{.def}

Once we know what is in our data, we can start playing with it. Let's manipulate the `us_contagious_diseases` dataset from the [dslabs package](https://cran.r-project.org/web/packages/dslabs/index.html).

:::

## Load packages

```{r}
library(dslabs)
library(dplyr)
```

## Selecting data

```{r}
us_contagious_diseases |>
  filter(state == "California")
```

```{r}
us_contagious_diseases |>
  filter(state == "California" & year > 2000)
```

```{r}
us_contagious_diseases |>
  filter(state == "California" & year > 2000) |>
  arrange(year)
```

```{r}
us_contagious_diseases |>
  filter(state == "California" & year > 2000) |>
  arrange(count)
```

```{r}
us_contagious_diseases |>
  filter(state == "California" & year > 2000) |>
  arrange(desc(count))
```

```{r}
us_contagious_diseases |>
  filter(state == "California" & year > 2000 & disease == "Hepatitis A") |>
  select(year, count, population)
```

<!-- ## Grouping data -->

<!-- ```{r} -->
<!-- us_contagious_diseases |> -->
<!--   group_by(state) |> -->
<!--   summarise( -->
<!--     ratio = count / population -->
<!--   ) -->
<!-- ``` -->
