---
title: Resources
aliases:
  - resources.html
author: Marie-Hélène Burle
---

:::{.def}

The R community is dynamic and offers a lot of online resources, from IDEs to Q&A, to workshops, books, or publications.

This section provides a selection of useful sites.

:::

### Main sites

- [R website](https://www.r-project.org/)
- [Comprehensive R Archive Network (CRAN)](https://mirror.rcg.sfu.ca/mirror/CRAN/): R versions and packages

### Posit and RStudio IDE

- [Posit website](https://posit.co/) *(Posit was formerly called RStudio Inc.)*
- [Posit cheatsheets](https://posit.co/resources/cheatsheets/)

### Forums and Q&A

- [Stack Overflow [r] tag wiki](https://stackoverflow.com/tags/r/info)
- [Stack Overflow [r] tag questions](https://stackoverflow.com/questions/tagged/r?sort=newest)
- [Posit Discourse](https://community.rstudio.com/)

### Documentation as pdf

- [Contributed documentation](https://cran.r-project.org/other-docs.html)
- [Intro books](https://github.com/ProjectMOSAIC/LittleBooks)

### Software Carpentry online workshops

- [Programming with R](http://swcarpentry.github.io/r-novice-inflammation/)
- [R for Reproducible Scientific Analysis](https://swcarpentry.github.io/r-novice-gapminder/)
- [Data analysis using R in the digital humanities](https://uomresearchit.github.io/r-tidyverse-digital-humanities/)

### Online books

- [R for Data Science](https://r4ds.had.co.nz/index.html) (heavily based on the [tidyverse](https://www.tidyverse.org/))
- [Advanced R](https://adv-r.hadley.nz/)
- [R Packages](https://r-pkgs.org/index.html) (how to create packages)
- [R Programming for Data Science](https://bookdown.org/rdpeng/rprogdatascience/)
- [Mastering Software Development in R](https://bookdown.org/rdpeng/RProgDA/)

### R research

- [The R Journal](https://journal.r-project.org/board.html)
