---
title: "R: why and for whom?"
aliases:
  - why.html
author: Marie-Hélène Burle
---

:::{.def}

There are other high level programming languages such as Python or Julia, so when might it make sense for you to turn to R?

:::

## Why R?

Here are a number of reasons why you might want to consider using R:

- Free and open source
- High-level and easy to learn
- Large community
- Very well documented
- Unequalled number of statistics and modelling packages
- Integrated package manager
- Easy connection with fast compiled languages such as C and C++
- Powerful IDEs (e.g. [RStudio](https://posit.co/download/rstudio-desktop/), [ESS](https://ess.r-project.org/), [Jupyter](https://jupyter.org/))

## For whom?

For whom is R particularly well suited?

- Fields with heavy statistics, modelling, or Bayesian analysis such as biology, linguistics, economics, or statistics
- Data science using a lot of tabular data

## Downsides of R

Of course, R also has its downsides:

- Inconsistent syntax full of quirks
- Slow
- Large memory usage
