---
title: High-performance computing in R
aliases:
  - intro_hpc.html
author: Marie-Hélène Burle
---

:::{.def}

R is not famous for its speed. With code optimization and parallelization, it can however be used for heavy computations.

This webinar will introduce you to working with R from the command line on the Alliance clusters with a focus on performance. We will discuss code benchmarking and various parallelization techniques.

:::

[Slides](wb_hpc_slides.qmd){.btn .btn-outline-primary} [(Click and wait: this reveal.js presentation may take a little time to load.)]{.inlinenote}
<br><br>

{{< video https://www.youtube.com/embed/mxkhOHdN2Hw >}}

<br>
*[Slides content](wb_hpc_content.qmd) for easier browsing.*

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "LearningResource",
  "name": "High-performance computing in R",
  "description": "R is not famous for its speed. With code optimization and parallelization, it can however be used for heavy computations.\n\nThis webinar will introduce you to working with R from the command line on the Alliance clusters with a focus on performance. We will discuss code benchmarking and various parallelization techniques.",
  "url": "https://mint.westdri.ca/r/wb_hpc",
  "learningResourceType": [
    "slides",
	"video"
  ],
  "inLanguage": "en",
  "license": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
  "provider": {
    "@type": "Organization",
    "name": "SFU Research Computing Group"
  },
  "keywords": "R, HPC, optimization, parallel programming",
  "author": {
    "@type": "Person",
    "name": "Marie-Hélène Burle"
  },
  "educationalLevel": "intermediate"
}
</script>
