---
title: A little demo of programming in R
aliases:
  - ws_r_demo
author: Marie-Hélène Burle
---

:::{.def}

R is a free and open-source programming language with a large collection of packages for statistical computing, modeling, and graphics. It is extremely popular in several academic fields including statistics, biology, economics, data mining, data analysis, and linguistics.

This high-level presentation will give you a sense of what R can be used for through a series of examples (data visualization, web scraping, and GIS). I will also talk about the strengths and weaknesses of R and who would benefit most from learning it.

:::

[Slides](ws_demo_slides.html){.btn .btn-outline-primary} [(Click and wait: the presentation might take a few instants to load)]{.inlinenote}
<br><br>

{{< video https://www.youtube.com/embed/ZDDiuRfYD-Y >}}

<br>
*[Slides content](ws_demo_content.qmd) for easier browsing.*

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "LearningResource",
  "name": "A little demo of programming in R",
  "description": "R is a free and open-source programming language with a large collection of packages for statistical computing, modeling, and graphics. It is extremely popular in several academic fields including statistics, biology, economics, data mining, data analysis, and linguistics.\n\nThis high-level presentation will give you a sense of what R can be used for through a series of examples (data visualization, web scraping, and GIS). I will also talk about the strengths and weaknesses of R and who would benefit most from learning it.",
  "url": "https://mint.westdri.ca/r/ws_demo",
  "learningResourceType": "slides, video",
  "inLanguage": "en",
  "license": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
  "provider": {
    "@type": "Organization",
    "name": "SFU Research Computing Group"
  },
  "keywords": "R, plotting, GIS, web scraping, demo, ggplot2",
  "author": {
    "@type": "Person",
    "name": "Marie-Hélène Burle"
  },
  "educationalLevel": "beginner"
}
</script>
